### ISSUE TITLE
the way to find root cause of kv error

### ISSUE THREAD

**Issue by jaczuo** [pingcap/tidb#10101]
I have plenty kv errors in my tidb cluster while I don't find any information to help find root cause in tidb.log and tikv.log. I'm wondering is there anyway to dig what happen there?

TiDB version: 2.0

![kv error](https://user-images.githubusercontent.com/8065066/55858008-28918b00-5ba1-11e9-8203-3ee2ed46fdb7.png)

Thanks

**Comment by lysu** [comment]
Thanks for feedback @jaczuo 

retry, backoff and lock resolve is normal operation in TiDB, from you monitor that's ok and don't mean error.

"resolve lock" means the number of errors related to transaction conflicts https://pingcap.com/docs/op-guide/tidb-dashboard-info/#key-metrics-description

"txnLockFast" is "resolve lock" happens in read request. tikv detect conflict tidb will handle them in by itself via retry.

those metrics is useful when we found TiDB's latency become bad and check whether caused by transaction conflict question.

if you don't see "Server-Failed Query OPM" value with good latancy metric in grafana that's ok.

**Comment by jaczuo** [comment]
Thanks for you answer @lysu. That really release my confusion.
