### ISSUE TITLE
myloader report error when loading the dumped file

### ISSUE THREAD

**Issue by Junkie0901** [pingcap/tidb#10130]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
mydumper -h localhost \
         -P 3306 \
         -u root \
         -p ******\
         -t 16 \
         -F 16 \
         -B ****db\
         --no-locks \
         --skip-tz-utc \
         -o /data/application/mysql/sql

myloader -h 10.18.1.81 \
		 -P 4000 \
		 -t 16 \
		 -checkpoint-schema  "tidb_loader" \
		 -d /data/application/tidb/sql

2. What did you expect to see?
no error appear and data import to tidb fully.

3. What did you see instead?
** (myloader:90597): CRITICAL **: 10:27:17.577: Error switching to database ****db whilst restoring table table1_*****
** (myloader:90597): CRITICAL **: 10:27:17.577: Error switching to database ****db whilst restoring table table2*****

** (myloader:90597): CRITICAL **: 10:27:17.835: Error restoring ***db.table_***** from file db**.ticket_order.00019.sql: transaction too large, len:300001

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.6
Git Commit Hash: 66e639e8e127f71662f37287eb984dd84d169cba
Git Branch: HEAD
UTC Build Time: 2019-03-15 09:09:07
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by morgo** [comment]
This error looks to be caused by `mydumper` creating an insert that exceeds [300K key-value pairs](https://pingcap.com/docs/sql/transaction-model/#large-transactions):
```
** (myloader:90597): CRITICAL : 10:27:17.835: Error restoring db.table_ from file db**.ticket_order.00019.sql: transaction too large, len:300001
```
I suspect it might be because `db.table_` is not very wide, so the -F 16 (files of 16MiB) is actually a very large number of rows. Did you mind trying to set this to a lower number such as -F 8 to verify?

Backup restore-ability is very important, so we will look if there is a more permanent fix that can be made to mydumper.

PTAL @kennytm

**Comment by shenli** [comment]
@Junkie0901 Please use `loader` instead of `myloader`. 
https://github.com/pingcap/docs/blob/master/v2.1/op-guide/backup-restore.md#restore-data-into-tidb

**Comment by nullnotnil** [comment]
I am going to close this issue, since it has gotten stale while other improvements were made:

* TiDB 4.0 now sets much larger per-transaction limits
* dumpling/lightning are now recommended over mydumper/myloader, but there is also a built-in backup/restore.

Please feel free to re-open it if you have any further questions. Thanks!
