### ISSUE TITLE
The 'order by' result does not respect to chinese pinyin order

### ISSUE THREAD

**Issue by ghost** [pingcap/tidb#10192]
## Bug Report

1. 创建如下测试表，插入3条测试记录
```sql
CREATE table table_a(
	`name` varchar(20)
);
insert into table_a(`name`) values('专业'),('人生'),('999');
```

2. 执行查询语句
```sql
SELECT * FROM table_a order by `name`;
```

3. 查询结果为

name |
------------ |
999  |
专业 |
人生 |

4. 期望得到的结果为

name |
------------ |
999 |
人生 |
专业 |

5. 在mysql中可以通过使用 `order by convert(col_name using gbk) ` 实现中文拼音排序，但tidb不支持gbk

6. 使用的tidb版本
```
Release Version: v3.0.0-beta.1-83-g1c21151b1
Git Commit Hash: 1c21151b1193a9d1416377dfd6b3743126ac8bfc
Git Branch: master
UTC Build Time: 2019-04-09 05:31:05
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by tiancaiamao** [comment]
This is a known issue,  the cause is that collation is not well-supported in TiDB @GuaiShu

**Comment by bb7133** [comment]
Hi @GuaiShu , the request of order can be archived by:

1. Explicitly changing the character set of the key (`convert ... using GBK`) as the example you gave, because Chinese character is encoded in the order of their pronunciations in GBK.
2. Explicitly changing the collation of the key, which is exactly the function of `collation`. However, for now, there's no built-in `utf8` collation in which Chinese character is ordered in their pronunciations in MySQL/TiDB, but we can create one named like `utf8_cn_pinyin_ci` and use it to meet your request. In such way, the SQL can be written as `SELECT * FROM table_a order by name COLLATE utf8_cn_pinyin_ci;`.

For now, the support of `GBK` is not planned in TiDB, so option 2 is more applicable in TiDB and it is not complicated. It would be great if you can contribute a new collation to TiDB.

The related issues/documents may be helpful:

- The support of collation `utf8mb4_unicode_ci`: https://github.com/pingcap/tidb/issues/17596
- [The official documents about character set and collation](https://docs.pingcap.com/tidb/v4.0/character-set-and-collation#character-set-and-collation)
- The [DDL and character set special interests group](https://github.com/pingcap/community/tree/master/special-interest-groups/sig-ddl) for TiDB community, feel free to join our [Slack channel](https://slack.tidb.io/invite?team=tidb-community&channel=sig-ddl&ref=pingcap-community) and ask any question there.

**Comment by zz-jason** [comment]
@wangggong We need more discussion about whether to introduce a new `utf8_cn_pinyin_ci` collation or support the `GBK`(gb18030) character set and its collations.

Reference to MySQL: [Asian Character Sets](https://dev.mysql.com/doc/refman/8.0/en/charset-asian-sets.html)

**Comment by zz-jason** [comment]
cc @ilovesoup

**Comment by nullnotnil** [comment]
GBK support is being tracked in https://github.com/pingcap/tidb/issues/10760 Thanks!

**Comment by zimulala** [comment]
This feature is already supported on the master, so you can try it out

```
tidb> CREATE table table_b( `name` varchar(20) ) charset = gbk;
Query OK, 0 rows affected (0.00 sec)

tidb> insert into table_b(`name`) values('专业'),('人生'),('999');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

tidb>  SELECT * FROM table_b order by `name`;
+--------+
| name   |
+--------+
| 999    |
| 人生   |
| 专业   |
+--------+
3 rows in set (0.00 sec)
```
