### ISSUE TITLE
tidb 3.0 'tikv-server -V' returns "illegal instruction"

### ISSUE THREAD

**Issue by hwinsCK** [pingcap/tidb#11046]
TiDB Version: TiDB 3.0 
Software:  http://download.pingcap.org/tidb-3.0.0-linux-amd64.tar.gz
./tikv-server  -V
Illegal instruction (core dumped)

The cpu info for the virtual machine:
vendor_id: GenuineIntel
model name: QEMU Virtual CPU
flags: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscal nx lm rep_good nopl pni cx16 x2apic popcnt hypervisor lahf_lm

**Comment by Connor1996** [comment]
Could you show gdb tikv-server core -batch -ex "disassemble"

**Comment by hwinsCK** [comment]
[gdb.txt](https://github.com/pingcap/tidb/files/3359764/gdb.txt)

**Comment by Connor1996** [comment]
same as https://github.com/tikv/tikv/issues/4999, it mainly because the distributed release includes AVX operations that your CPU doesn't support. It will be okay for the next release, but for now, you can download tikv source code https://github.com/tikv/tikv/archive/v3.0.0.tar.gz and run make dist_release on your own machine to build the binary fitting for your CPU flags.

**Comment by fzhedu** [comment]
close it due to no response for a long time.
