### ISSUE TITLE
Column information in error message is missing.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11145]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
SELECT  `col_float_signed` AS field1  FROM `table50_int_autoinc` GROUP BY GET_FORMAT( DATETIME, 'ISO' );
```

2. What did you expect to see?

```
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'randgen_test.table50_int_autoinc.col_float_signed' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

3. What did you see instead?

The column information is missing.
```
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column '' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

fdbc149b72db7034d024acf1209e455c0ad4ca9d

**Comment by gaoxingliang** [comment]
I'm working on this issue. and I will add some UT cases for this

**Comment by gaoxingliang** [comment]
Hi @SunRunAway  I looked more into this issue. Do we need to append the dbName.tableName.colName into the description?
I found the root cause is in the [parser.y](https://github.com/pingcap/parser/blob/master/parser.y#L3534) file:
here when it has an AsName (grammar like `select id as t from s`), then the text field is not set.
```
		if last.Expr != nil && last.AsName.O == "" {
			lastEnd := parser.endOffset(&yyS[yypt-1])
			last.SetText(parser.src[last.Offset:lastEnd])
		}
```
and the message is appended here `planner/core/logical_plan_builder.go#checkOnlyFullGroupByWithGroupClause`


So here I have two solutions:
1. give an explicit solution by using the `sel.Fields.Fields[errExprLoc.Offset].Name.ColumnNameExpr` but it seems it not public. 
2. or give an non-explicit answer by changing the parser.y by setting the text to the string contains the AS.

I would suggest Option 1.
