### ISSUE TITLE
Question about docker and kubernetes deployment

### ISSUE THREAD

**Issue by jinares** [pingcap/tidb#11890]
阅读文档时觉得tidb 更多的是引导使用Ansible 部署。有两个问题：

- 1、不推荐在生产环境使用docker部署，why?(因为数据安全问题？网络问题？)

- 2 、Kubernetes 部署tidb有版本要求吗？docker的部问题应该同样存在吧

**Comment by lamxTyler** [comment]
Thanks for your feedback! PTAL @xiaojingchen

**Comment by xiaojingchen** [comment]
@jinares  

1. Directly use docker deploy TiDB is not recommended because docker is only a container management tool and does not provide deployment and maintenance functions for distributed databases. Secondly, data security and network problems do exist in the container environment. It needs some experience and technical accumulation to avoid them.

2. Considering the incompatibility of the old version configuration, the new version of TiDB (v2.0) is recommended for Kubernetes deployment. In addition, Kubernetes is a distributed basic platform, which naturally supports distributed systems. In addition, the TiDB Operator project has made deep integration and custom for TiDB running on Kubernetes, implement automation of deployment and daily operation and maintenance, and also realized fault recovery. So compared with docker, it is more convenient and reliable. 
Specifically, please refer to: https://pingcap.com/docs-cn/v3.0/tidb-in-kubernetes/tidb-operator-overview/

**Comment by jinares** [comment]
@xiaojingchen  Thanks
