### ISSUE TITLE
rocksdb io not stable

### ISSUE THREAD

**Issue by junplus** [pingcap/tidb#12215]
![image](https://user-images.githubusercontent.com/28999107/65005439-6a81e280-d932-11e9-86fc-06d9c642281a.png)

as above,  io may reach to a relatively high value at a time point, i wonder how to make the rocksdb thread io stable

**Comment by you06** [comment]
The relatively high values are caused by memtable flush and compaction. You can look up into `Compaction flow`, `Number files at each level` panels in `TiKV-Details -> RocksDB-kv`. If the compaction and memtable flush time(large amount of level 0 files) charts match `Threads IO` high points, it's OK.

Compaction is a feature of RocksDB, the io is usually not stable. If you give a higher the write ops, `Threads IO` will be more stable.
