### ISSUE TITLE
How to create unique rowID on multiple node TiDB

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tidb#12218]
I read your [blog](https://medium.com/@PingCAP/tidb-internal-ii-computing-2f97bdc09f0c), I have a question: `How will the rowID be created on multiple TiDB nodes if the table's primary key is not an int?` Because rowID is unique for each table, but we have multiple node TiDB.

![image](https://user-images.githubusercontent.com/38773351/65020525-8e0b5400-d957-11e9-98ad-af327f316e5d.png)

**Comment by at15** [comment]
I got the same question and [dig into the code a bit](https://github.com/at15/gegecece/blob/master/doc/log/2020-02/2020-02-03-design.md#how-tidb-generate-rowid), I am not sure it's all correct but here is what I found

- [AddRecord](https://github.com/pingcap/tidb/blob/source-code/table/tables/tables.go#L345) requires to create new record id(s) if the record does not have a int primary key
- [allocator allocates ids using a tikv transaction](https://github.com/pingcap/tidb/blob/source-code/meta/autoid/autoid.go#L152), so you get unique id across entire system instead of a local counter
- also rowid may not be a mono id based on [Complex hotspot problem](https://pingcap.com/docs/stable/reference/best-practices/high-concurrency/#complex-hotspot-problem)

**Comment by XuHuaiyu** [comment]
Close this issue due to no feedback for a long time.
Feel free to reopen it if you need any further help.
