### ISSUE TITLE
Support adding unique index on a column that contains duplicated data and make sure the following inserted data will not be duplicated

### ISSUE THREAD

**Issue by github-zuoyan** [pingcap/tidb#13987]
## Feature Request
对于有重复的存量数据字段添加唯一索引不会丢数据，同时保证增量数量不会重复
**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

对于有重复的存量数据字段添加唯一索引不会丢数据，同时保证增量数量不会重复
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by shenli** [comment]
@github-zuoyan Is this feature supported by any RDMS?

**Comment by nullnotnil** [comment]
I think it is better to handle this in the application since I suspect a not-fully-unique UNIQUE index makes it hard for the optimizer to plan things successfully.

There are a couple of things you can do to manage this:

1. Before you add the unique index, run `SELECT <unique-key>, COUNT(*) FROM your_table GROUP BY <unique-key> HAVING COUNT > 1`. Then attempt to fix these records.

2. Add a new column to the unique key. So for example if the unique key was supposed to be on `user_id`, make the key `user_id, version_id` instead. `version_id` is defined as `INT NOT NULL DEFAULT 1;` You can use the HAVING query from above, to set some of the duplicate rows to be a `version_id` greater than 1. New records inserted will only be version_id 1 by default.
