### ISSUE TITLE
Support for typed system variables when running SELECT @@foreign_key_checks

### ISSUE THREAD

**Issue by chaosue** [pingcap/tidb#15131]
when client queries variable 'foreign_key_checks', tidb sends string value 'OFF' to them. But mysql server always sends '0' or '1' in spite of versions. So any client tools won't raise any exception when talks to mysql server and can parse the value of 'foreign_key_checks' to an integer, while tidb's response will lead to a failure on parsing.
_below are the tcpdump captures:_

**tidb latest**

> 17:21:13.365154 IP 121-36-228-111.4000 > 192.168.0.156.49446: Flags [P.], seq 2183:2280, ack 1663, win 251, options [nop,nop,TS val 2768261666 ecr 2298205247], length 97
E.....@.?..o...,.......&.....<9............
..R"...?.....>....def....@@foreign_key_checks.@@foreign_key_checks...........................OFF....

**mysql server 5.7**

> 17:23:46.235028 IP chaoswork.mysql > chaoswork.57500: Flags [P.], seq 2113:2181, ack 1681, win 512, options [nop,nop,TS val 3449871429 ecr 3449871429], length 68
E..x.[@.@.W"..................)......l.....
...E...E.....*....def....@@foreign_key_checks..?................0...........

**flyway encountered an exception**
>org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to determine value for 'foreign_key_checks' variable
     -----------------------------------------------------------
SQL State  : 22018
Error Code : 0
Message    : Cannot determine value type from string 'OFF' at org.flywaydb.core.internal.database.mysql.MySQLConnection.getIntVariableValue(MySQLConnection.java:64) ~[flyway-core-6.2.4.jar!/:na]
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.<init>(MySQLConnection.java:56) ~[flyway-core-6.2.4.jar!/:na]

**Comment by IOhacker** [comment]
I got the same issue working with Flyway 6.3.2 and MySQL Connector J's

************************************************************************
And with CONNECTOR J VERSION 5.1.48 
************************************************************************

Caused by: java.sql.SQLException: Invalid value for getInt() - 'OFF' in column 1
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
at com.mysql.jdbc.ResultSetImpl.getIntFromString(ResultSetImpl.java:2624)
at com.mysql.jdbc.ResultSetImpl.getNativeInt(ResultSetImpl.java:3920)
at com.mysql.jdbc.ResultSetImpl.getNativeInt(ResultSetImpl.java:3819)
at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2550)
at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:150)
at org.flywaydb.core.internal.database.mysql.MySQLConnection.getIntVariableValue(MySQLConnection.java:62)

************************************************************************
And with CONNECTOR J VERSION 8.0.19
************************************************************************
Caused by: java.sql.SQLDataException: Cannot determine value type from string 'OFF'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:96)
at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1382)
at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:786)
at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:150)

I have tried to set:

mysql> set global foreign_key_checks = 0;
Query OK, 0 rows affected (0.05 sec)

mysql> SET FOREIGN_KEY_CHECKS=0;
Query OK, 0 rows affected (0.04 sec)

mysql> SET GLOBAL FOREIGN_KEY_CHECKS=0;
Query OK, 0 rows affected (0.05 sec)

mysql> set global foreign_key_checks = 0;
Query OK, 0 rows affected (0.04 sec)

mysql> set foreign_key_checks = 0;
Query OK, 0 rows affected (0.04 sec)

mysql> SHOW Variables WHERE Variable_name='foreign_key_checks';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| foreign_key_checks | OFF   |
+--------------------+-------+
1 row in set (0.04 sec)

But it is not working. 

Is there any workaround ?

Regards

Victor

**Comment by wwar** [comment]
Here is a test case to show the issue. First in MySQL:
```
mysql [localhost:8019] {msandbox} ((none)) > select @@foreign_key_checks;
+----------------------+
| @@foreign_key_checks |
+----------------------+
|                    1 |
+----------------------+
1 row in set (0.00 sec)

mysql [localhost:8019] {msandbox} ((none)) > SHOW VARIABLES LIKE 'foreign_key_checks';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| foreign_key_checks | ON    |
+--------------------+-------+
1 row in set (0.00 sec)
```

Then in TiDB:
```
tidb> select @@foreign_key_checks;
+----------------------+
| @@foreign_key_checks |
+----------------------+
| OFF                  |
+----------------------+
1 row in set (0.00 sec)

tidb> SHOW VARIABLES LIKE 'foreign_key_checks';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| foreign_key_checks | OFF   |
+--------------------+-------+
1 row in set (0.00 sec)
```

The problem isn't specifically that TiDB has a different default, it's that MySQL with an `@@` will return a numeric representation of a boolean. In other contexts it will show the string representation.

**Comment by InfotecMexico** [comment]
I think is related to this PR https://github.com/pingcap/tidb/pull/8358

**Comment by nullnotnil** [comment]
I took a look at fixing this. I think it's a bit harder than it looks. For example, I can get it to return "1" in the context of an `@@` operator with this patch:
```
diff --git a/sessionctx/variable/sysvar.go b/sessionctx/variable/sysvar.go
index 6ff201575..5715ecedf 100644
--- a/sessionctx/variable/sysvar.go
+++ b/sessionctx/variable/sysvar.go
@@ -77,11 +77,19 @@ func BoolToIntStr(b bool) string {
        return "0"
 }
 
+// OnOffToBoolStr converts "OFF/ON" to "0/1"
+func OnOffToBoolStr(s string) string {
+       if strings.ToUpper(s) == "OFF" {
+               return "0"
+       }
+       return "1"
+}
+
 func boolToOnOff(b bool) string {
        if b {
-               return "on"
+               return "ON"
        }
-       return "off"
+       return "OFF"
 }
 
 // BoolToInt32 converts bool to int32
diff --git a/sessionctx/variable/varsutil.go b/sessionctx/variable/varsutil.go
index d8b036bb6..96fd24214 100644
--- a/sessionctx/variable/varsutil.go
+++ b/sessionctx/variable/varsutil.go
@@ -102,6 +102,11 @@ func GetSessionSystemVar(s *SessionVars, key string) (string, error) {
                return "", err
        }
        s.systems[key] = gVal
+       // MySQL will return "1" or "ON" for a bool sysvar
+       // depending on the context.
+       if gVal == "ON" || gVal == "OFF" {
+               gVal = OnOffToBoolStr(gVal)
+       }
        return gVal, nil
 }
```

But if you look closer at how MySQL does this, an `@@foreign_key_checks` will also return a typed value:
```sql
mysql [localhost:8021] {msandbox} ((none)) >  select @@foreign_key_checks;
Field   1:  `@@foreign_key_checks`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     1
Max_length: 1
Decimals:   0
Flags:      BINARY NUM 


+----------------------+
| @@foreign_key_checks |
+----------------------+
|                    1 |
+----------------------+
1 row in set (0.00 sec)

mysql [localhost:8021] {msandbox} ((none)) >  select @@innodb_version;
Field   1:  `@@innodb_version`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     24
Max_length: 6
Decimals:   31
Flags:      


+------------------+
| @@innodb_version |
+------------------+
| 8.0.21           |
+------------------+
1 row in set (0.00 sec)
```

In TiDB, both sysvars and user variables are not typed - they are always strings. So if someone who uses flyway wants to test my patch, we can create a PR.. but I don't have confidence it will work in all scenarios.
