### ISSUE TITLE
Chaning default TiDB system variable values seems not working.

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#15437]
## General Question

Hi, I'm trying to change the tidb system variable default values and meet a problem. 
Here is my step:

1.  changing the value of `DefTiDBHashJoinConcurrency` from 5 to 6
 
https://github.com/pingcap/tidb/blob/ad63c03e5090e9fed17d39e05938630f895a53b1/sessionctx/variable/tidb_vars.go#L414

2. run `make server` to build tidb-server binary

3. execute the binary with no extra starting args 

4. query the `@@tidb_hash_join_concurrency;` value and it returend as followed:

```sh
mysql> select @@tidb_hash_join_concurrency;
+------------------------------+
| @@tidb_hash_join_concurrency |
+------------------------------+
| 5                            |
+------------------------------+
1 row in set (0.00 sec)
``` 

It seems the default value is still 5 instead of 6 which makes me confused.

I'm wondering is this anything wrong in my steps or I just misunderstand the `DefTiDBHashJoinConcurrency`

**Comment by lysu** [comment]
@Yiasaer you can try this sql:

```
select * from mysql.global_variables where variable_name = 'tidb_hash_join_concurrency'\G;
```

if you see result is `5`, it's reasonable.

because `tidb_hash_join_concurrency` is globle variable, so it will persist default value `5` into `global_variables` table(in tikv) when you first time startup tidb, then you modify code to change `DefTiDBHashJoinConcurrency` will be no affact due to there are exists value `5` in storage and no need use def.

so:

- if you want to change the  tidb_hash_join_concurrency value, please don't change code just execute `set globla tidb_hash_join_concurrency = x` and reconnect to tidb
- if you want to change the default value of tidb_hash_join_concurrency, you need change code to let `DefTiDBHashJoinConcurrency = 6 `(this works for new setup cluster) and add a boostrap upgrade job like this https://github.com/pingcap/tidb/blob/1b3b6f0e80b462e32182ef0cbb8ba66d2fb41604/session/bootstrap.go#L917 to modify exists cluster's value

**Comment by Yisaer** [comment]
@lysu  Thanks for your answering. But I' afraid you haven't answered all my question.

I'm wondering, after I change the code then re-compile the binary and start the binary with no start args. (which means it started as a new cluster and I think there is no persistence, right?)
So in this case, why the default value of `DefTiDBHashJoinConcurrency` is 5 and where this value come from?

**Comment by Yisaer** [comment]
Thanks for @SunRunAway 's explain. The tidb binary would persist the data into `/tmp/tidb`, that's why the default value is not changing.

**Comment by lysu** [comment]
yes, mocktikv will use /tmp/tidb
