### ISSUE TITLE
[beego-orm]Support Like binary

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#164]
https://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html#operator_like

The following two statements illustrate that string comparisons are not case sensitive unless one of the operands is a case sensitive (uses a case-sensitive collation or is a binary string):

mysql> SELECT 'abc' LIKE 'ABC';
        -> 1
mysql> SELECT 'abc' LIKE _latin1 'ABC' COLLATE latin1_general_cs;
        -> 0
mysql> SELECT 'abc' LIKE _latin1 'ABC' COLLATE latin1_bin;
        -> 0
mysql> SELECT 'abc' LIKE BINARY 'ABC';
        -> 0

**Comment by morgo** [comment]
The syntax described here works in TiDB with the limitation that TiDB does not yet support case-insensitive collations.  Since there is [an existing issue open for case sensitive collations](https://github.com/pingcap/tidb/issues/7519), I am going to close this issue for now.

Please feel free to re-open if you have any followup questions.  Thanks!
