### ISSUE TITLE
TiDB takes the unstable TSO

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tidb#17482]
Hi all.
I am currently using TiDB version 3.0.11. I deploy by model: 3 node TiDB on 3 servers, 5 node TiKV on 5 servers, and 5 node PD on the same server of TiKV.

I monitor the time of taking TSO of TiDB and it is unstable. 

![image](https://user-images.githubusercontent.com/38773351/83109331-6fb34600-a0eb-11ea-80a1-10fee378c370.png)

I read [issue](https://github.com/pingcap/tidb/issues/8323) about get timestamp too slow. I am not sure if the network affects latency. There are panels:

![image](https://user-images.githubusercontent.com/38773351/83109700-0da71080-a0ec-11ea-88d4-65be4d2d7ebb.png)
![image](https://user-images.githubusercontent.com/38773351/83109719-14358800-a0ec-11ea-9f1e-7c1b3571a109.png)
 
Note: PD Client CMD Duration is metric of **tso_async_wait**.

Metric **Start TSO Wait duration** includes the network and the **processing time of the PD**. So we cannot confirm due to the latency network. And I also checked the network and it was ok. 

And I check CPU of TiDB, PD and it was not unusual.

![image](https://user-images.githubusercontent.com/38773351/83110895-f49f5f00-a0ed-11ea-8cda-f085f7e2d630.png)

**What reason did the taking of TSO so unstable ?**

**Comment by phamtai97** [comment]
@tiancaiamao

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/pd/blob/ea2b748f6ee26f2b4a1a4f2e7995f27507954904/client/client.go#L596

If `tso_async_wait`is slow, it means parse or compile takes a lot of time.
You can check the `parse` and `compile` duration to figure out why.

Strictly speaking, TSO should only be affected by the RPC, but it involves so many other factors and the metrics are unstable.

I think it can be divided into two major parts:

1. RPC

RPC means the duration between tidb sending out the request and recving the response.
This is affected by the network quality and PD server handle duration.

Note that the PD server periodically dump data to the disk (etcd), so this duration is unstable.
The network may also be unstable, of course.

2. WAIT

This part is more complex, and is highly implementation related, the user has to know many details to understand it.

```
sql -> parse -> compile -> execute
                 \->      tso           ->  /
```

Get TSO runs parallelly with parse&compile.
Before executing, if the TSO result is not ready, the statement need to WAIT.

- This wait may happen because RPC is slow and the result is not ready.
- This wait may also happen because parse&compile is slow, so TSO result is ready but the call doesn't use it, here you see the `async_wait` metric.
- This wait may happen even because of the runtime schedule, if the load of the machine is heavy.

B.T.W, for general questions like this, you could post at [asktug](https://asktug.com/), someone maybe on duty  and you will get a quick response.

**Comment by tiancaiamao** [comment]
Sorry, asktug is a **Chinese** forum, you may join the [Slack Channel](https://pingcap.com/tidbslack/) to comminute with the engineers.

**Comment by phamtai97** [comment]
Oh thank you.
