### ISSUE TITLE
Could tidb support fetch function

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17504]
## Feature Request

**Describe the feature you'd like:**

Could we support fetch function?
Such as: DECLARE cursor_name CURSOR FOR SELECT_statement;OPEN cursor_name;FETCH cursor_name

**Describe alternatives you've considered:**

With above feathure, It will easy to traverse data. 

https://asktug.com/t/topic/34614/2

**Comment by zz-jason** [comment]
The main request of this issue is the support for [Cursors](https://dev.mysql.com/doc/refman/5.7/en/cursors.html) in MySQL:

> MySQL supports cursors inside stored programs. The syntax is as in embedded SQL. Cursors have these properties:
>
> - Asensitive: The server may or may not make a copy of its result table
> - Read only: Not updatable
> - Nonscrollable: Can be traversed only in one direction and cannot skip rows

To fully support it, make it usable, we need to support at least these statements:

- [Cursor DECLARE Statement](https://dev.mysql.com/doc/refman/5.7/en/declare-cursor.html)
- [Cursor OPEN Statement](https://dev.mysql.com/doc/refman/5.7/en/open.html)
- [Cursor FETCH Statement](https://dev.mysql.com/doc/refman/5.7/en/fetch.html)
- [Cursor CLOSE Statement](https://dev.mysql.com/doc/refman/5.7/en/close.html)

The fundamental statement is cursor `FETCH` statements:

```sql
FETCH [[NEXT] FROM] cursor_name INTO var_name [, var_name] ...
```

> This statement fetches the next row for the SELECT statement associated with the specified cursor (which must be open), and advances the cursor pointer. If a row exists, the fetched columns are stored in the named variables. The number of columns retrieved by the SELECT statement must match the number of output variables specified in the FETCH statement.
>
> If no more rows are available, a No Data condition occurs with SQLSTATE value '02000'. To detect this condition, you can set up a handler for it (or for a NOT FOUND condition). For an example, see Section 13.6.6, “Cursors”.

Another question is, how to handle the `SQLSTATE value '02000'`. To detect this condition, we need to support the flow control statements in the stored program.

Seems it's more complicated than only support the Cursor Statements.

**Comment by zz-jason** [comment]
As mentioned above, it's hard to make this feature usable for the applications without the support of flow control statements in the stored program. Considered there isn't a plan to support the stored program in TiDB, this feature request is closed and marked as rejected.
