### ISSUE TITLE
Could TiDB support JSON Partial Updates

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17514]
## Feature Request

**Describe the feature you'd like:**
Could TiDB support JSON Partial Updates. Such as Mysql : https://dev.mysql.com/doc/refman/8.0/en/json.html#json-partial-updates

**Describe alternatives you've considered:**
Improve TiDB support JSON performance.

https://asktug.com/t/topic/34614/22

**Comment by wwar** [comment]
This question relates a lot to the InnoDB storage engine, which works quite differently from TiKV.

InnoDB performs an update in place, with a relocation of the old data (for MVCC) to a temporary space called undo. In TiKV/RocksDB, there is no undo but instead rows are written as new. The data files (.sst) are read-only by design.

There are advantages to both approaches, but it will make this specific feature difficult to add to TiKV.

**Comment by scsldb** [comment]
Difficult to implement technology, no solution yet.

We need to sort out the missing JSON features and optimization levels before we continue the discussion.

**Comment by zz-jason** [comment]
It's hard to fully support the JSON features and makes it compatible with MySQL due to the architecture and implementation differences. At present, TiDB encodes and stores the whose JSON attribute and other attributes of a table into the value part of key-value pair in TiKV. There isn't a plan to support this feature to update a JSON attribute.
