### ISSUE TITLE
I am looking for a lite tidb version , replace with sqlite.

### ISSUE THREAD

**Issue by ghost** [pingcap/tidb#17656]
Hello, I am looking for lite TiDB version, replace with sqlite.
For single container instance, Or Mobile app development.
None tcp/ip stack. just embedded , or localhost listen and serve.
Low resource cosumption, the same protocol and performace still good.

Embedded  mysql protocl , no client/server architecture.

So it can be replaced sqlite, and easy to migrate to tidb production cluster(if needed)

**Comment by djshow832** [comment]
TiDB doesn't support SQLite protocol yet, it only support MySQL protocol.
Do you mean to deploy a single node TiDB cluster? TiUP may help you to deploy. 
I suggest v4.0.0 for TiDB.

**Comment by netroby** [comment]
https://github.com/WangXiangUSTC/tidb-lite

This is close to my request. but
 still not satisified with my needed. 

Sqlite is an emmbed database. we need the same . no C/S , just embbed it.

**Comment by netroby** [comment]
英文表达可能不太清晰，翻译成中文： 我在找一个嵌入式的mysql 协议的实现，等价于sqlite一样的。 这样小企业，个人用户，可以无痛体验TiDB的科技，可以用于小型数据库场景，数据量大了，再上集群。
二十年前，我们学asp, access数据库，后面，学php sqlite，嵌入式数据库始终有它的价值。特别适合小型应用场景。

如果tidb有 嵌入式数据库，那么很有可能可以无缝迁移到集群版本，（只要设计上共享相同的协议层）。

吸引新用户，企业无缝加入TiDB 大家庭。

**Comment by malaschitz** [comment]
Exactly what I need. For small web applications I often just need sqlite. It's easier than using some noSQL database (especially when the data is relational) or worrying about some mysql database. sqlite is a really fantastic library but it has two shortcomings:
- you have to worry about the hassle of compiling the application for different platforms. 
- everything only runs in a single thread. You have to have db.SetMaxConn(1). This doesn't matter in principle, but you can't forget about it and have some transaction that would take too long because it will lock up your whole server.

**Comment by jebter** [comment]
Maybe you can try serverless:https://tidb.cloud/?utm_source=google&utm_medium=cpc&utm_campaign=plg_search_Serverless_LP_02&utm_id=701BV000000APCKYA4&gad_source=1.I will close this issue. If there are any updates, you can reopen it.
