### ISSUE TITLE
TiDB doesn't lock non-existent unique-key when select for update from TiFlash

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tidb#17851]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table:
`create table if not exists txn0 (id  int not null primary key, val text); `

create tiflash replica and wait for the replica become available:
`alter table txn0 set tiflash replica 1;`

in the first terminal, type the following sql:
`set @@session.tidb_isolation_read_engines = "tiflash";`
`begin pessimistic;`
`select val from txn0 where id = 25 for update;`

in the second terminal, type the following sql:
`insert into txn0 (id, val) values (25, '5');`

### 2. What did you expect to see? (Required)
The insert statement will get stuck.
### 3. What did you see instead (Required)
The insert statement succeed.
### 4. Affected version (Required)
v4.0.0,v3.1.0

**Comment by ilovesoup** [comment]
For 4.0 GA we added warning in TiFlash doc for not to use it in select for update since this scenarios is not thoroughly tested and other bugs exists. This case seems rare, at least non of current users use like this according to my knowledge. If this cannot be fixed by 4.0.2, we will confirm docs include sufficient warning message for it.

**Comment by zanmato1984** [comment]
Decided to go with "forbid tiflash in write transaction".
