### ISSUE TITLE
having for aggregate field alias name bug 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#179]
```
create table t1 (a int, b int) engine=innodb;
insert into t1 values (1,2), (1,3), (2,3), (2,4), (2,5), (3,4), (4,5), (4,100);

mysql> select a, sum(b) as b from t1 group by a having b > 4;
+------+------+
| a    | b    |
+------+------+
|    1 |    5 |
|    2 |   12 |
|    4 |  105 |
+------+------+
```

but we only get one row result.

**Comment by xwb1989** [comment]
A simpler test case is:
`select a as b from t1 having b > 4;`
mysql gives 
`empty set`
but TiDB gives
```
+---+
| b |
+---+
| 2 |
| 4 |
| 4 |
+---+
```

**Comment by qiuyesuifeng** [comment]
@xwb1989 Thanks for report.
Yes, that is a problem.
I will fix it later.

**Comment by xwb1989** [comment]
Following is problematic in `HavingRset.CheckAndUpdateSelectList`, :
```	
if field.ContainFieldName(name, selectList.ResultFields, field.OrgFieldNameFlag) {
    continue
}		
if field.ContainFieldName(name, selectList.ResultFields, field.FieldNameFlag) {
    if field.ContainFieldName(name, tableFields, field.OrgFieldNameFlag) {
        selectList.CloneHiddenField(name, tableFields)
    }
    continue
}
```
not having enough time to really dig into yet, but commenting out 
```
    if field.ContainFieldName(name, tableFields, field.OrgFieldNameFlag) {
        selectList.CloneHiddenField(name, tableFields)
    }
```
Can solve this particular problem(but might break others :( 

Just FYI

**Comment by qiuyesuifeng** [comment]
@xwb1989 
Thanks for your suggestion.

We used hidden fields for having fields which not in select or group by fields, and we have not distinguished aggregate and none aggregate fields, so we have the problem as @siddontang mentioned.

As for `select a as b from t1 having b > 4;`, because some having conditions has some confused results, like `select a as b from t1 having b + 1` or  `select a as b from t1 having a + b` or `select a + b as b from t1 having a + b > 0` and so on, now we only process alias field as origin field first,  so `select a as b from t1 having b > 4;`  may equal to  `select a from (select a, b from t1 having b > 4) c;`.

Later we will discuss and fix this problem.
Thanks again.

**Comment by qiuyesuifeng** [comment]
@xwb1989 
We have fixed this problem, u can update master branch and have a try:)

**Comment by xwb1989** [comment]
Thank you for letting me know :)

**Comment by xwb1989** [comment]
I could confirm that the test cases mentioned above is passing.

**Comment by siddontang** [comment]
Cool @xwb1989
