### ISSUE TITLE
Roadmap is 404

### ISSUE THREAD

**Issue by linvis** [pingcap/tidb#18215]
## General Question

the roadmap url in README.md is 404
![image](https://user-images.githubusercontent.com/10113087/85663611-dd9f5d00-b6eb-11ea-9320-b39c0594f934.png)

**Comment by linvis** [comment]
[known compatibility differences](https://pingcap.com/docs/v3.0/reference/mysql-compatibility/), [Adapter](https://docs.pingcap.com/adopters/), [QuickStart](https://docs.pingcap.com/QUICKSTART) are also 404.

**Comment by lilin90** [comment]
@linvis Thanks for your feedback. Since we have been migrating docs to [a new docs website](https://docs.pingcap.com/tidb/v4.0) recently, this causes some 404 links temporarily. Now the following original links (in the [README.md](https://github.com/pingcap/tidb/blob/master/README.md) file) have worked well:

- Roadmap: https://pingcap.com/docs/ROADMAP
- Known compatibility differences: https://pingcap.com/docs/v3.0/reference/mysql-compatibility/
- Adopters: https://pingcap.com/docs/adopters/
- Quick Start: https://pingcap.com/docs/QUICKSTART
- English docs: https://pingcap.com/docs
- 简体中文: https://pingcap.com/docs-cn

**Comment by linvis** [comment]
> @linvis Thanks for your feedback. Since we have been migrating docs to [a new docs website](https://docs.pingcap.com/tidb/v4.0) recently, this causes some 404 links temporarily. Now the following original links (in the [README.md](https://github.com/pingcap/tidb/blob/master/README.md) file) have worked well:
> 
> * Roadmap: https://pingcap.com/docs/ROADMAP
> * Known compatibility differences: https://pingcap.com/docs/v3.0/reference/mysql-compatibility/
> * Adopters: https://pingcap.com/docs/adopters/
> * Quick Start: https://pingcap.com/docs/QUICKSTART
> * English docs: https://pingcap.com/docs
> * 简体中文: https://pingcap.com/docs-cn

English docs and 简体中文 look like something wrong.
English docs(https://pingcap.com/docs) links to  a chinese page, and  简体中文(https://pingcap.com/docs-cn)
