### ISSUE TITLE
empty or negative `actRows` in explain analyze results

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#18528]
## Development Task
As shown below, if the number of rows in the outer side of `Join` or `IndexLookUp` is zero, the `actRows` in the inner side may be empty or negative(-1), which are inappropriate and may confuse users.
It's better to use `0` in these cases.
```
mysql> create table t (a int, b int, index (a));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values (1, 1);
Query OK, 1 row affected (0.01 sec)

mysql> explain analyze select * from t t1, t t2 where t1.b = t2.a and t1.b = 2333;
+------------------------------------+----------+---------+-----------+----------------------+----------------------------------------------------------------------+---------------------------------------------------+-----------+---------+
| id                                 | estRows  | actRows | task      | access object        | execution info                                                       | operator info                                     | memory    | disk    |
+------------------------------------+----------+---------+-----------+----------------------+----------------------------------------------------------------------+---------------------------------------------------+-----------+---------+
| HashJoin_8                         | 100.00   | 0       | root      |                      | time:224.935µs, loops:1, Concurrency:5, probe collision:0, build:0s  | CARTESIAN inner join                              | 0 Bytes   | 0 Bytes |
| ├─IndexLookUp_18(Build)            | 10.00    | 0       | root      |                      | time:137.949µs, loops:1                                              |                                                   | 140 Bytes | N/A     |
| │ ├─IndexRangeScan_16(Build)       | 10.00    |         | cop[tikv] | table:t2, index:a(a) | time:0s, loops:0                                                     | range:[2333,2333], keep order:false, stats:pseudo | N/A       | N/A     |
| │ └─TableRowIDScan_17(Probe)       | 10.00    |         | cop[tikv] | table:t2             | time:0s, loops:0                                                     | keep order:false, stats:pseudo                    | N/A       | N/A     |
| └─TableReader_12(Probe)            | 10.00    | 0       | root      |                      | time:180.865µs, loops:1                                              | data:Selection_11                                 | 131 Bytes | N/A     |
|   └─Selection_11                   | 10.00    |         | cop[tikv] |                      | time:0ns, loops:0                                                    | eq(test.t.b, 2333)                                | N/A       | N/A     |
|     └─TableFullScan_10             | 10000.00 |         | cop[tikv] | table:t1             | time:0s, loops:0                                                     | keep order:false, stats:pseudo                    | N/A       | N/A     |
+------------------------------------+----------+---------+-----------+----------------------+----------------------------------------------------------------------+---------------------------------------------------+-----------+---------+
7 rows in set (0.00 sec)
```

**Comment by rebelice** [comment]
When use mockstore, cop tasks' attribute actRows will be empty, just like
`MySQL [test]> explain analyze select * from t t1, t t2 where t1.b = t2.a and t1.b = 2333;
+------------------------------------+----------+---------+-----------+----------------------+------------------------------------------------------------------------+---------------------------------------------------+-----------+---------+
| id                                 | estRows  | actRows | task      | access object        | execution info                                                         | operator info                                     | memory    | disk    |
+------------------------------------+----------+---------+-----------+----------------------+------------------------------------------------------------------------+---------------------------------------------------+-----------+---------+
| HashJoin_8                         | 100.00   | 0       | root      |                      | time:2.805754ms, loops:1, Concurrency:5, probe collision:0, build:0s   | CARTESIAN inner join                              | 0 Bytes   | 0 Bytes |
| ├─IndexLookUp_18(Build)            | 10.00    | 0       | root      |                      | time:1.661693ms, loops:1, rpc num: 1, rpc time:254.059µs, proc keys:0  |                                                   | 142 Bytes | N/A     |
| │ ├─IndexRangeScan_16(Build)       | 10.00    |         | cop[tikv] | table:t2, index:a(a) | time:0ns, loops:0                                                      | range:[2333,2333], keep order:false, stats:pseudo | N/A       | N/A     |
| │ └─TableRowIDScan_17(Probe)       | 10.00    |         | cop[tikv] | table:t2             | time:0ns, loops:0                                                      | keep order:false, stats:pseudo                    | N/A       | N/A     |
| └─TableReader_12(Probe)            | 10.00    | 0       | root      |                      | time:576.711µs, loops:1, rpc num: 1, rpc time:1.186567ms, proc keys:0  | data:Selection_11                                 | 137 Bytes | N/A     |
|   └─Selection_11                   | 10.00    |         | cop[tikv] |                      | time:0ns, loops:0                                                      | eq(test.t.b, 2333)                                | N/A       | N/A     |
|     └─TableFullScan_10             | 10000.00 |         | cop[tikv] | table:t1             | time:0ns, loops:0                                                      | keep order:false, stats:pseudo                    | N/A       | N/A     |
+------------------------------------+----------+---------+-----------+----------------------+------------------------------------------------------------------------+---------------------------------------------------+-----------+---------+
`
The reason is that the return value of GetExecutionSummaries() is nil, even if the value of CollectExecutionSummaries is true.  So mockstore may go wrong.

**Comment by qw4990** [comment]
PTAL @bobotu The accuracy of `actRows` is important when testing and debugging the optimizer.

**Comment by qw4990** [comment]
Close since it is resolved.
