### ISSUE TITLE
memory_quota: lost connection in the next sql after out of memory quota

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#18540]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

oom-action=cancel
```
drop table if exists t;
create table t(a int);
insert into t values(1), (-1), (0);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert /*+ memory_quota(1 MB) */ into t select * from t;
insert /*+ memory_quota(2 MB) */ into t select * from t;
insert /*+ memory_quota(14 MB) */ into t select * from t;
insert /*+ memory_quota(15 MB) */ into t select * from t;
select count(*) from t;
```

### 2. What did you expect to see? (Required)
```
mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
|   393216 |
+----------+
1 row in set (3.38 sec)
```
### 3. What did you see instead (Required)
```
mysql> select count(*) from t;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
### 4. Affected version (Required)

```
Release Version: v4.0.2-23-g89e34b707
Edition: Community
Git Commit Hash: 89e34b707fdfeb1bcac5b3ecd13f5614bd2f0291
Git Branch: release-4.0
UTC Build Time: 2020-07-14 06:30:07
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by XuHuaiyu** [comment]
For `/*+ memory_quota(1 MB) */` and `/*+ memory_quota(2 MB) */`
1. The connection will not be closed, thus the next query can run successfully without a break
2. The connection will not be closed because of that the panic is triggered [here](https://github.com/pingcap/tidb/blob/master/executor/adapter.go#L352)  and recovered [here](https://github.com/pingcap/tidb/blob/master/executor/adapter.go#L273-L290). 

For `/*+ memory_quota(14 MB) */` and `/*+ memory_quota(15 MB) */`
1. The connection will be closed, thus the next query will get the `Lost connection` message
2. The connection will be closed because of that the panic is triggered [here](https://github.com/pingcap/tidb/blob/master/session/session.go#L676) and recovered [here](https://github.com/pingcap/tidb/blob/master/server/conn.go#L661-L679)

**Comment by XuHuaiyu** [comment]
To fix this problem, we can recover the panic [here](https://github.com/pingcap/tidb/blob/master/session/session.go#L1182) to avoid losing connection.
