### ISSUE TITLE
Can't connect to TiDB via 8.0.13 ODBC

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tidb#18642]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

* 8.0.13 MySQL ODBC
* v4.0.2 TiDB
![image](https://user-images.githubusercontent.com/12085878/87644950-622b4b80-c77f-11ea-93fa-51ac3313a6e1.png)
![image](https://user-images.githubusercontent.com/12085878/87644984-6fe0d100-c77f-11ea-8145-0abb6c6e0134.png)

* use 5.3 MySQL ODBC can connect to TiDB successfully.
![image](https://user-images.githubusercontent.com/12085878/87645079-96067100-c77f-11ea-935f-fd3f2ba301af.png)

### 2. What did you expect to see? (Required)
Connect to TiDB via 8.0 MySQL ODBC.

### 3. What did you see instead (Required)
Can't connect to TiDB via 8.0 MySQL ODBC.

### 4. Affected version (Required)
v4.0.2

**Comment by nullnotnil** [comment]
This is documented in the [TIDB FAQ here](https://docs.pingcap.com/tidb/stable/tidb-faq#how-is-tidb-compatible-with-mysql).

The reason is because MySQL 8.0 connectors will attempt to use `caching_sha2_password` as the authentication plugin, which TiDB does not yet support (see: https://github.com/pingcap/tidb/issues/9411).

**Comment by Win-Man** [comment]
OK, thank you.
