### ISSUE TITLE
The case the Index is not used !  

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#18720]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
![2](https://user-images.githubusercontent.com/9397764/88145115-86c66e00-cc2c-11ea-8bdd-c34e3fe27354.png)

the index is not used, so that there is very slow to execute sql. 

### 2. What did you expect to see? (Required)
![1](https://user-images.githubusercontent.com/9397764/88145073-74e4cb00-cc2c-11ea-915f-e58efb0e3a85.png)

### 3. What did you see instead (Required)
I think  that is easy to judge what index by used. but tidb is not accurate enough.

### 4. Affected version (Required)
v4.0.2

**Comment by nullnotnil** [comment]
@474420502 Thank you for the bug report.

Can you please provide:
- The output of `SHOW CREATE TABLE source_openrec`.
- A [dump of the statistics](https://docs.pingcap.com/tidb/stable/statistics#import-and-export-statistics) from source_openrec. 
- The execution time with and without using the index.

Also, just to confirm it is not out of date statistics - what happens when you run `ANALYZE TABLE source_openrec` and then `EXPLAIN` the query again. Does TiDB start using the index?

Thank you in advance.

**Comment by 474420502** [comment]
![image](https://user-images.githubusercontent.com/9397764/88248255-17f02000-ccd3-11ea-9b15-809543d7fff7.png)
very strange!
i redo that without that run ANALYZE TABLE source_openrec  , but the result is different to yesterday.   
the index is used. 
table is not changed, but the data was deleted.

``` sql
CREATE TABLE IF NOT EXISTS `source_openrec` (
	uid bigint AUTO_INCREMENT COMMENT '自增UID',

	`streamer_id` bigint DEFAULT NULL ,
	`url` text NOT NULL ,
	`source` longtext DEFAULT NULL ,
	`ext` json DEFAULT NULL COMMENT '扩展字段',
	`serialize` blob DEFAULT NULL ,
	`update_time` Timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
	`error_msg` text DEFAULT NULL ,

	`target_type` varchar(64) NOT NULL ,
	`operator` int DEFAULT 0,
	PRIMARY KEY(`uid`),
	KEY `operator_idx` (`operator`),
	KEY `update_time_idx` (`update_time`),
	KEY `target_type_idx` (`target_type`)
 );
```

**Comment by nullnotnil** [comment]
@474420502 I believe the root cause is that the statistics degraded, but perhaps not enough to trigger auto-analyze yet.

There is a new feature in TiDB 4.0 which can be used to see the health of an index called [SHOW STATS_HEALTHY](https://docs.pingcap.com/tidb/dev/sql-statement-show-stats-healthy). The manual now has an example that shows how stats can get out of date following a bulk delete.

If the statistics degrade too frequently, you can consider modifying tidb_auto_analyze_ratio or using Plan Binding / Hints.
