### ISSUE TITLE
关于TIDB的系统变量tidb_force_priority 

### ISSUE THREAD

**Issue by buptxiaomiao** [pingcap/tidb#18989]
File: [/tidb-specific-system-variables.md](undefined/zh/tidb/v3.0/tidb-specific-system-variables)

参见文档https://docs.pingcap.com/zh/tidb/v3.0/tidb-specific-system-variables#tidb_force_priority

文档中描述tidb_force_priority为session级的变量

实际在tidb 3.0.12版本中
默认为NO_PRIORITY

按时间顺序：
sessionA执行 set session tidb_force_priority = ‘LOW_PRIORITY’;

sessionB中
show variables like ‘tidb_force_priority’ 显示为 ‘LOW_PRIORITY’，
show session variables like ‘tidb_force_priority’ 显示为 ‘LOW_PRIORITY’，
show GLOBAL VARIABLES like ‘tidb_force_priority’ 显示为 ‘NO_PRIORITY’

请问

1. 这个变量是session级的吗，查看当前session的优先级，应该以哪个为准？

2. 通过设置的语句执行的优先级，有监控可以看吗？ TiKV-detail的dashboard–scheduler–scheduler_priority_command 里显示的优先级是否是这个tidb_force_priority这个变量控制的？ 我这边虽然设置了LOW_PRIORITY，但是监控上的LOW_PRIORITY没有数据

3. tidb_force_priority 这个变量设置的优先级，背后的原理是？ （是具体影响了哪些操作而达到设置优先级的目的？）

**Comment by nullnotnil** [comment]
I believe the reason why this is broken, is because `tidb_force_priority` is intended to be of instance scope, but the configuration system doesn't natively handle such.

i.e. if you issue `SET GLOBAL`, it propagates to all other TiDB servers in the cluster, which does not really make sense for setting priority. But when you set it to `SET SESSION`, it also applies to other sessions on the same instance :( 

I think the fix will require https://github.com/pingcap/tidb/issues/9298 to be added first.

**Comment by Defined2014** [comment]
We already changed it to `instance` from v6.1.x, so close this issue.
