### ISSUE TITLE
Result of an in-transaction query is incorrect

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#19136]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
-- init
create table t ( c_int int, c_str varchar(40), primary key(c_int, c_str) );
-- txn
begin;
insert into t values (1, 'amazing almeida'), (2, 'boring bardeen'), (3, 'busy wescoff');
select c_int, (select t1.c_int from t t1 where t1.c_int = 3 and t1.c_int > t.c_int order by t1.c_int limit 1) x from t;
commit;
select c_int, (select t1.c_int from t t1 where t1.c_int = 3 and t1.c_int > t.c_int order by t1.c_int limit 1) x from t;
```

### 2. What did you expect to see? (Required)

Both selection should return:
```
+-------+------+
| c_int | x    |
+-------+------+
|     1 |    3 |
|     2 |    3 |
|     3 | NULL |
+-------+------+
```

### 3. What did you see instead (Required)

```
mysql> begin;
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t values (1, 'amazing almeida'), (2, 'boring bardeen'), (3, 'busy wescoff');
Query OK, 3 rows affected (0.08 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select c_int, (select t1.c_int from t t1 where t1.c_int = 3 and t1.c_int > t.c_int order by t1.c_int limit 1) x from t;
+-------+------+
| c_int | x    |
+-------+------+
|     1 |    3 |
|     2 | NULL |
|     3 | NULL |
+-------+------+
3 rows in set (0.05 sec)

mysql> commit;
Query OK, 0 rows affected (0.05 sec)

mysql> select c_int, (select t1.c_int from t t1 where t1.c_int = 3 and t1.c_int > t.c_int order by t1.c_int limit 1) x from t;
+-------+------+
| c_int | x    |
+-------+------+
|     1 |    3 |
|     2 |    3 |
|     3 | NULL |
+-------+------+
3 rows in set (0.06 sec)

```

### 4. What is your TiDB version? (Required)

release-4.0 @ 3948c7ba7b5d4a081abf2162b791ab67fe650882

**Comment by cfzjywxk** [comment]
There are two problems need to fix:
1. The `UnionScanExec` should reset `addedRows`, `cursor4AddRows`, `snapshotRows` and `cursor4SnapshotRows` doing `Close` operation. Otherwise the apply executor may open and close union scan operator and the returned data is wrong.
For v4.0 release branch, after fixing this, the result is correct.

2. On the master branch, besides the problem above, [17578](https://github.com/pingcap/tidb/pull/17578) seems to have introduced some problems and evaluating the condition expressions in `UnionScanExec`. The `datum` value for the correlated column is incorrect doing the valuation of these condition expressions.

**Comment by ichn-hu** [comment]
> 1. For v4.0 release branch, after fixing this, the result is correct.

Have you fixed them? If so, is there any related PR?
