### ISSUE TITLE
Support select for update WAIT

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#19579]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Example:

```sql
select
   student_last_name
from
   student
where student_id = 12345
FOR UPDATE WAIT 15;
```

From https://docs.oracle.com/en/database/oracle/oracle-database/20/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6

> NOWAIT | WAIT
>
> The NOWAIT and WAIT clauses let you tell the database how to proceed if the SELECT statement attempts to lock a row that is locked by another user.
> * Specify NOWAIT to return control to you immediately if a lock exists.
> * Specify WAIT to instruct the database to wait integer seconds for the row to become available and then return control to you.
> If you specify neither WAIT nor NOWAIT, then the database waits until the row is available and then returns the results of the SELECT statement.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nullnotnil** [comment]
Note that this syntax is not offered by MySQL, but it is [in MariaDB](https://mariadb.com/kb/en/wait-and-nowait/). MySQL can achieve similar with a hint, although it applies to  `SELECT` statements only. This should work with TiDB too, but it looks like there is a bug:

Session 1:
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (id int not null primary key, pad1 varchar(100));
INSERT INTO t1 (id) values (1);
START TRANSACTION;
UPDATE t1 SET pad1='newvalue' WHERE id = 1;
# leave open, don't commit or rollback
```
Session 2:
```sql
START TRANSACTION;
SELECT /*+ MAX_EXECUTION_TIME(1000) */ * FROM t1 WHERE id = 1 FOR UPDATE;
```

In MySQL, session 2 will generate an error after 1000ms:
```sql
mysql [localhost:8021] {msandbox} (test) > START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

mysql [localhost:8021] {msandbox} (test) > SELECT /*+ MAX_EXECUTION_TIME(1000) */ * FROM t1 WHERE id = 1 FOR UPDATE;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
```

This doesn't work in TiDB. It takes a full 50 seconds (`innodb_lock_wait_timeout`) to timeout:
```sql
mysql> SELECT /*+ MAX_EXECUTION_TIME(1000) */ * FROM t1 WHERE id = 1 FOR UPDATE;
ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction
```

May I suggest that if you do add this with `WAIT n`, you also fix it with the hint version? I realize that the hint version is for full execution time (including lock acquisition), but I actually like it more because I think ms is a better unit of measurement for this.
