### ISSUE TITLE
Need the default order , without using order by in TiDB

### ISSUE THREAD

**Issue by SE-Bin** [pingcap/tidb#19818]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Because of Mysql InnoDB using the IOT, the result is ordered according to the index which is used.
 In TiDB, when the result involves more than 2 regions, the returned result is out of order.

**Describe the feature you'd like:**

The result can be ordered default by the index which is used without using order by .

**Describe alternatives you've considered:**

Modify the business SQLs ，add the order by. 

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nullnotnil** [comment]
I recommend addressing these issues with [SPM](https://docs.pingcap.com/tidb/stable/sql-plan-management). The problem with forcing order on TiDB, is that it will force sub-optimal query plans.

With MySQL this order is never guaranteed, even if it is often stable due to clustered index+single-threaded execution. As new optimizations are added, the order often changes. We can see from their bugs database that requests for stable behavior when the query is ambiguous are rejected:

* https://bugs.mysql.com/bug.php?id=72076
* https://bugs.mysql.com/bug.php?id=69732
* https://bugs.mysql.com/bug.php?id=75750

**Comment by zz-jason** [comment]
Agree with @nullnotnil, if there is no `order by` clause in the query, it's expected that the order is unstable.

Maybe we can add a query hint or instance variable like `reserve_index_order()`, by default it's false, to reserve the data order gathered from all the coprocessor tasks. But it has the following drawbacks:

- If this variable is enabled, the query latency might be increased as @nullnotnil mentioned above.
- The result may still unstable if there is a physical operator using hash table, for example, Hash Join, Hash Aggregate. If we wish to further keep order, we'd better combine other query hints to not choose Hash Join, Hash Aggregate, or extend this variable to make the query optimizer not choose Hash Join or Hash Aggregate. Both methods increase the query latency.

**Comment by zz-jason** [comment]
@SunRunAway Could you assign someone to add a FAQ in the [SQL FAQs](https://docs.pingcap.com/tidb/stable/sql-faq#sql-faqs) document?
