### ISSUE TITLE
change tidb_enable_change_column_type to include global | session scope

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tidb#20234]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> create table test.tb(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> alter table test.tb modify column a smallint;
ERROR 8200 (HY000): Unsupported modify column: length 6 is less than origin 11, and tidb_enable_change_column_type is false
mysql> set @@global.tidb_enable_change_column_type=1;
Query OK, 0 rows affected (0.00 sec)

mysql> alter table test.tb modify column a smallint;
ERROR 8200 (HY000): Unsupported modify column: length 6 is less than origin 11, and tidb_enable_change_column_type is false
mysql> exit
```
after reconnect to TiDB
```
mysql> alter table test.tb modify column a smallint;
Query OK, 0 rows affected (0.02 sec)
```

### 2. What did you expect to see? (Required)
tidb_enable_change_column_type effects for the current connection
### 4. What is your TiDB version? (Required)

```
mocktikv

Release Version: v4.0.0-beta.2-1288-g10fd83446-dirty
Edition: Community
Git Commit Hash: 10fd834463ea6f44b187993e2ea189e3d5c72097
Git Branch: master
UTC Build Time: 2020-09-24 14:04:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by bb7133** [comment]
This issue should be a 'feature request' rather than a 'bug report' because by definition, `GLOBAL` variable does not affect the current session.

So I believe that you want to make 'tidb_enable_change_column_type' available as a session variable.

**Comment by cncal** [comment]
I'd like to enhance it.

**Comment by zz-jason** [comment]
To be compatible with MySQL, changing the global variable in a session does not take effect in the current session.

We have two methods to achieve this:

1. specially handle `tidb_enable_change_column_type`.
2. provide a SQL syntax to explicitly refresh the current variable to reflect new changes to the global variable. for example, the SQL syntax can be `admin refresh global variables`

Since the first method breaks the rule that 'changing the global variable in a session does not take effect in the current session', I think the second method is more acceptable. @nullnotnil what's your opinion?

@cncal Thanks for the contribution. However, this feature request needs more discussion. let's begin the coding work after the feature and implementation method has been settled.

**Comment by nullnotnil** [comment]
@zz-jason as you note in your edit, it looks like from the patch this is just a change to add sessionscope to a sysvar. But to answer your question:

There is not a standard way to tell a session (or all sessions) to pick up a new value of a particular sysvar. This has caused problems in the last in MySQL with the `long_query_time` sysvar. If you are using a connection pool, it's not possible to drop the long query time in all sessions in order to collect a sample of all queries. Percona had a fix for this, but it was not a generic way: https://www.percona.com/doc/percona-monitoring-and-management/2.x/manage/conf-mysql-ps-slow-query-log-use-global-control.html

I think we can defer this problem for now and figure out the syntax when we need to cross this bridge later.
