### ISSUE TITLE
support hierarchical queries

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#20278]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

like [Oracle Hierarchical Queries](https://docs.oracle.com/cd/B19306_01/server.102/b14200/queries003.htm)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nullnotnil** [comment]
The more standard way to do this is with a recursive CTE. See: https://github.com/pingcap/tidb/issues/6824

**Comment by zz-jason** [comment]
After going through the examples listed in Oracle Hierarchical Query and MySQL Recursive Common Table Expression, I agree with @nullnotnil that they can both achieve the same application requirements. [This answer](https://stackoverflow.com/a/33737203) from stack overflow also provides several alternatives and explanations about how to achieve a hierarchical query.

From Wikipedia's explanation of [Hierarchical and recursive queries in SQL](https://en.wikipedia.org/wiki/Hierarchical_and_recursive_queries_in_SQL):

> In standard SQL:1999 hierarchical queries are implemented by way of recursive common table expressions (CTEs). Unlike Oracle's earlier connect-by clause, recursive CTEs were designed with fixpoint semantics from the beginning.[1] Recursive CTEs from the standard were relatively close to the existing implementation in IBM DB2 version 2.[1] Recursive CTEs are also supported by Microsoft SQL Server (since SQL Server 2008 R2),[2] Firebird 2.1,[3] PostgreSQL 8.4+,[4] SQLite 3.8.3+,[5] IBM Informix version 11.50+, CUBRID, MariaDB 10.2+ and MySQL 8.0.1+,[6]. Tableau has documentation describing how CTEs can be used. TIBCO Spotfire does not support CTEs, while Oracle 11g Release 2's implementation lacks fixpoint semantics.

I think it's better to support recursive common table expression other this `connect by` feature in Oracle since recursive CTE is both in SQL-99 standard and widely implemented and used by database and database applications.

**Comment by zz-jason** [comment]
There is also a proposal about recursive CTE: https://github.com/pingcap/tidb/pull/19253

**Comment by zz-jason** [comment]
I'm going to reject and close this feature request. feel free to reopen it if the current solution can not fulfill the application requirements.
