### ISSUE TITLE
Support graceful shutdown API

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb#20619]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When upgrading or scaling in tidb-server, users usually send `TERM` signal to tidb-server, and tidb-server will close the port 4000 listener, and handles the existing request, then wait a timeout and then close existing connections.

In general, users will run a load balancer in front of multiple tidb-servers. The load balancer will probe the tidb-server with an interval (eg. 5s), and only when several consecutive probe fails (eg. 3), the load balancer will stop forwarding traffic to the tidb-server. So there will be a gap between tidb-server close the port 4000 listener and the load balancer stop forwording traffic to it. During this time, the client request will fail. This has bigger impact to short connections as short connections usually don't have retry logic, for example PHP applications.

**Describe the feature you'd like:**

Add an API to request tidb-server fail health check to allow users gracefully shutdown tidb-server behind a load balancer.

**Describe alternatives you've considered:**

Reusing `TERM` signal to accomplish graceful shutdown. But on k8s, the `TERM` signal is triggered by deleting pod. When a pod is marked deleted, the endpoint will be removed and the node port will be closed like tidb-server itself, thus causing tidb-server unable to graceful shutdown behind an external load balancer.

xref:
* https://github.com/kubernetes/enhancements/pull/1607
* https://github.com/kubernetes/kubernetes/issues/85643

**Teachability, Documentation, Adoption, Migration Strategy:**

tidb-operator and tiup need to support graceful shutdown. /cc @lonng

**Comment by nullnotnil** [comment]
I think this is easy to implement. See my [comment here](https://github.com/pingcap/tidb/issues/13808#issuecomment-682324003):

> On issuing `SHUTDOWN GRACEFULLY`, TiDB immediately reports itself as unhealthy (but still accepts connections, and behaves the same).
> After a timeout, TiDB starts refusing new connections and forcefully terminates existing connections.
> TiDB then exits

I suggest that the default timeout can be 30 seconds. Does this work for you @tennix ?

**Comment by tennix** [comment]
> I think this is easy to implement. See my [comment here](https://github.com/pingcap/tidb/issues/13808#issuecomment-682324003):
> 
> > On issuing `SHUTDOWN GRACEFULLY`, TiDB immediately reports itself as unhealthy (but still accepts connections, and behaves the same).
> > After a timeout, TiDB starts refusing new connections and forcefully terminates existing connections.
> > TiDB then exits
> 
> I suggest that the default timeout can be 30 seconds. Does this work for you @tennix ?

Yes, it works. We need issuing `SHUTDOWN GRACEFULLY` an API instead of unix signal as the unix signal is bound to pod deletion in k8s environment. And pod deletion is coupled with other controller operations.

**Comment by zz-jason** [comment]
IMO, issuing `SHUTDOWN GRACEFULLY` is a critical operation:
- users may need a super privilege to do it to prevent attacks
- TiDB may record an audit log for this operation as well

I think it's better to use SQL commands instead of an HTTP API in the status port.

**Comment by tennix** [comment]
> IMO, issuing `SHUTDOWN GRACEFULLY` is a critical operation:
> 
>     * users may need a super privilege to do it to prevent attacks
> 
>     * TiDB may record an audit log for this operation as well
> 
> 
> I think it's better to use SQL commands instead of an HTTP API in the status port.

Shutting down is a bit scary, in fact we only need to let tidb-server fail the status check to tell external LB to not route traffic to this tidb-server.

**Comment by zz-jason** [comment]
> we only need to let tidb-server fail the status check to tell external LB to not route traffic to this tidb-server.

how about this:

1. A sends `TERM` signal to tidb-server process via `kill`
2. B queries a status HTTP API in tidb-server to check whether the server is in graceful shutdown progress periodically
3. B removes that tidb from the load balancer once the query result is positive.

**Comment by tennix** [comment]
Yeah, `TERM` signal would be the optimal option. But k8s has special handling logic to this. With this KEP (https://github.com/kubernetes/enhancements/pull/1607) implemented, I think it would not be a problem using `TERM` signal. I'll investigate if there is a workaround for this.

So at least TiDB needs to fail status check first instead of closing port 4000 listener when receiving `TERM` signal.

**Comment by nullnotnil** [comment]
> IMO, issuing `SHUTDOWN GRACEFULLY` is a critical operation:
> 
> * users may need a super privilege to do it to prevent attacks
> * TiDB may record an audit log for this operation as well
> 
> I think it's better to use SQL commands instead of an HTTP API in the status port.

There is actually a privilege specific to [`SHUTDOWN`](https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_shutdown).

This is already implemented correctly in TiDB:

```sql
mysql@root> create user u1;
Query OK, 0 rows affected (0.06 sec)

mysql@u1> shutdown;
ERROR 8121 (HY000): privilege check fail

mysql@root> grant shutdown on *.* to u1;
Query OK, 0 rows affected (0.03 sec)

mysql@u1> shutdown;
Query OK, 0 rows affected (0.00 sec)

mysq@u1l> select 1;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

When `SIGTERM` is received it currently handles server shutdown the same way as `SHUTDOWN`, but maybe we can move it to point to the `SHUTDOWN GRACEFULLY` implementation. My only concern is that most processes clean up and shutdown much faster than 30s. Because the load balancer is external, you can not end the timeout early if you observe no new connections either; it might just be a low traffic app.

**Comment by zz-jason** [comment]
> So at least TiDB needs to fail status check first instead of closing port 4000 listener when receiving TERM signal.

In my opinion, the correct step should be:

1. remove the tidb-server from the load balancer
2. gracefully shutdown that tidb-server

instead of implementing a `delayed` graceful shutdown:

1. gracefully shutdown that tidb-server
2. tidb should wait x seconds to process the graceful shutdown command, it fails the status check during this period
3. the load balancer detected the tidb-server is going to process the graceful shutdown command
4. remove the tidb-server from the load balancer

**Comment by cfzjywxk** [comment]
@tiancaiamao What do you think of this?

**Comment by zz-jason** [comment]
how other distributed database handles this scenario?

**Comment by nullnotnil** [comment]
> > So at least TiDB needs to fail status check first instead of closing port 4000 listener when receiving TERM signal.
> 
> In my opinion, the correct step should be:
> 
> 1. remove the tidb-server from the load balancer
> 2. gracefully shutdown that tidb-server

This makes sense, but it is hard to automate because users may have different load balancers. There is no standard way to remove a node from a load balancer, but the concept of a HTTP health check is standard.

> how other distributed database handles this scenario?

[CockroachDB does it with a delayed graceful period](https://www.cockroachlabs.com/docs/stable/remove-nodes.html) (they describe it as a load balancer drain period, which is also fine):

"After all range replicas have been transferred, a graceful shutdown is initiated by sending SIGTERM, during which the node is drained of SQL clients, distributed SQL queries, and range leases. Meanwhile, the /health?ready=1 monitoring endpoint starts returning a 503 Service Unavailable status response code so that load balancers stop directing traffic to the node"

The configuration setting is called `server.time_until_store_dead`.

**Comment by nullnotnil** [comment]
I took a look at this, and have a PR available. The `SHUTDOWN` sql command actually just calls `kill` on the server's process, so to add `SHUTDOWN GRACEFULLY`, logically there would need to be `SIGTERM` handling first.
