### ISSUE TITLE
shutdown tidb-server gracefully when got signal

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#2120]
When get signal to quit, we should first stop listening on the port and then finish the running jobs.

**Comment by morgo** [comment]
Related: https://github.com/pingcap/tidb/issues/5046

**Comment by nullnotnil** [comment]
This was partially fixed in https://github.com/pingcap/tidb/pull/8711

There is a known bug where it is not guaranteed that ongoing requests would finish: https://github.com/pingcap/tidb/issues/13369

I am going to close this issue as a duplicate, as https://github.com/pingcap/tidb/issues/13369 supersedes this with a similar request.
