### ISSUE TITLE
[DML]: select id + 1 from mytest group by id + 1 having id + 1> 0, it shows unknown column id in having clause

### ISSUE THREAD

**Issue by xiaobogaga** [pingcap/tidb#21579]
Hi tidb team, I have a question regarding to the following queries:
```sql
use test;
create table mytest (id int, name varchar(20), age int);
select id + 1 from mytest group by id + 1 having id + 1> 0;
```
in tidb playground: https://play.pingcap.com, after I run such query, it shows error message: `[planner:1054]Unknown column 'id' in 'having clause'`.

This error message looks like consistent with mysql(with version 8.0.22).

But I feel this message is not user-friendly, because the id is not an unknown column.

And I feel maybe this one is a bug, the query should be okay, but since the group by type check is very ambiguous, so I'm not so sure.

Am I correct? and will you guys change it to a better message (means it won't be consistent with mysql)?

Anyway, I feel this one doesn't have much impact to usage.

**Comment by kele1997** [comment]
`select id+1 as tmp from mytest group by tmp having tmp > 0` works   
This is my guessing: 
Maybe the `group by id+1` generate a temporary column like t1, then `having id+1 ` generate a temporary column like t2, and the column name in `group by` and `having` is different, so that not work as you want.   
And when we use alias , we can use the same temporary column in `group by` and `having`

**Comment by xiaobogaga** [comment]
@kele1997  thank you kele. Year, what you given is a possible cause for the issue here.
