### ISSUE TITLE
In pessimistic transaction, select for update is different on partition tables and non-partition tables

### ISSUE THREAD

**Issue by zhenjiaogao** [pingcap/tidb#22244]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

* Partiton Table
![image](https://user-images.githubusercontent.com/26379799/103781949-dfba7f00-5071-11eb-9026-a71e2dc0c702.png)

* Non-partition Table
![image](https://user-images.githubusercontent.com/26379799/103781135-e0064a80-5070-11eb-9389-eb551da28d41.png)

### 2. What did you expect to see? (Required)

In pessimistic transaction, select for update is the same on partition and non-partition tables

### 4. What is your TiDB version? (Required)

```log
mysql> select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v4.0.9 |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by zyguan** [comment]
TiDB may acquire unnecessary locks https://github.com/pingcap/tidb/issues/21688, thus we get lock wait timeout for the case of non-partitioned table. For the partitioned table version, I think it because the query condition doesn't match any of partitions, if we create an partition which include '2020-11-30', it gets blocked too.

**Comment by zyguan** [comment]
dup of #21688
