### ISSUE TITLE
indexScan is not used `where in ()`

### ISSUE THREAD

**Issue by TheNorthMemory** [pingcap/tidb#2408]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

  ```sql
CREATE TABLE `test` (
  `a` varchar(20) NOT NULL,
  `b` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB;
```

2. What did you expect to see?

   - 2.1 execute `explain select * from test where a in ('x', 'y', 'z')` use indexScan;
   - 2.2 execute `explain select * from test where a in ( select 'x' from dual)` should use indexScan as well.

3. What did you see instead?

   - 2.2 uses tableScan instead

4. What version of Go are you using (`go version`)?

golang 1.6

**Comment by shenli** [comment]
@TheNorthMemory Thanks for your feedback!
@hanfei1991 PTAL

**Comment by hanfei1991** [comment]
Because you didn't create an index.
See:
mysql> create table tt(c int);
Query OK, 0 rows affected (0.00 sec)

mysql> create index cc on tt(c);
Query OK, 0 rows affected (0.01 sec)

mysql> explain select * from tt where c in (1,2,3);
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| ID          | Json                                                                                                                                                                                                                                                                                                                                                                                      | ParentID |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| IndexScan_5 | {
    "db": "test",
    "table": "tt",
    "index": "cc",
    "ranges": "[[1,1] [2,2] [3,3]]",
    "desc": false,
    "out of order": true,
    "double read": false,
    "push down info": {
        "limit": 0,
        "access conditions": [
            "in(test.tt.c, 1, 2, 3)"
        ],
        "index filter conditions": null,
        "table filter conditions": null
    }
} |          |
+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
1 row in set (0.00 sec)

For `explain select * from test where a in ( select 'x' from dual)`, we will change it to semi-join and apply hash join algorithm. @TheNorthMemory Any more question ?

**Comment by TheNorthMemory** [comment]
@hanfei1991 The column `a` was the primary key  in the `test` table, so i think the usage should be fine.  i'm just waiting for usage indexScan of the `select * from test where a in ( select 'x' from dual)` implementation.

**Comment by hanfei1991** [comment]
Well, your case is pretty seldom, because (select 'x' from dual) will only return 'x'. Most times a `In` subquery should return different records.

**Comment by kaiwu** [comment]
@hanfei1991 another example

## create table like these 
```sql
CREATE TABLE `test` (
  `a` varchar(20) NOT NULL,
  `b` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB;

CREATE TABLE `demo` (
  `x` varchar(20) NOT NULL,
  `y` int(11) NOT NULL,
 PRIMARY KEY (`y`)
) ENGINE=InnoDB;

```

## queries

```sql
explain 
select demo.*
from demo 
inner join test
on demo.y = test.b
where test.a = 'abc'
```

which equals to 

```sql
explain
select demo.*
from demo
where demo.y IN (
select b from test
where test.a = 'abc'
)
```

the question is that there is an index on `demo.y`  (primary key) but the index is not used in either query above, and table scan is applied, it's becoming quite slow if table `demo` has thousands of rows, any suggestions ?

**Comment by kaiwu** [comment]
in the original example one could use

```sql
explain 
select * from test 
where a in ( 
select 'x' from dual
union 
select 'y' from dual
) 
```

and the result is no different: the index on `test.a` is not used

**Comment by hanfei1991** [comment]
@kaiwu  Index look up Join is very inefficient for distributed computing. So we always use hash join. If the table in `In` subquery is always small, we can do index look-up join, this is in our roadmap.

**Comment by kaiwu** [comment]
@hanfei1991 , ok i see, thanks for your feedback

**Comment by hanfei1991** [comment]
@kaiwu We have supported index look up join. See https://github.com/pingcap/docs-cn/blob/master/sql/tidb-specific.md
