### ISSUE TITLE
The result of `select round(1e3, 2)` is wrong

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#2409]
1. What did you do?
If possible, provide a recipe for reproducing the error.
select round(1e3, 2);

2. What did you expect to see?
+---------------+
| round(1e3, 2) |
+---------------+
|       1000.00 |
+---------------+
1 row in set (0.01 sec)

3. What did you see instead?
+---------------+
| round(1e3, 2) |
+---------------+
|          1000 |
+---------------+
1 row in set (0.00 sec)

**Comment by zyguan** [comment]
I think it's because we always use `-1` as the prec arg of `strconv.AppendFloat` [here](https://github.com/pingcap/tidb/blob/master/server/util.go#L330).

To fix it, we need to know the real prec first. However, it seems that the float datum hasn't provide such information yet. Is it ok to reuse an another field defined in `Datum` to store such info?

BTW, the mysql-workbench shows that the result of `select round(1e3, 2);` has 'Display Size' of 19 and 'Precision' of 5. Do these values matter a lot?

**Comment by zimulala** [comment]
You are right, it because we always use `-1` as the argument. 
It has the field of `decimal` to store precision information in `Datum`. We can use `Frac()` to get precision information.
There is to be compatible with MySQL.
@zyguan Could you try to fix it?

**Comment by zyguan** [comment]
Sure @zimulala , I would like to try :)

**Comment by zhexuany** [comment]
@zimulala This is already fixed. Please close this issue.
