### ISSUE TITLE
Does PointGet work on TiDB and TiKV only?

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#24117]
https://github.com/pingcap/tidb/blob/05bb31b81120197681196c6f54f8ac262f0d97c5/planner/core/find_best_task.go#L701

if so, we should write as

```go
canConvertPointGet := len(path.Ranges) > 0 && (path.StoreType == kv.TiKV || path.StoreType == kv.TiDB)
```

for further store type extension.

**Comment by tisonkun** [comment]
cc @eurekaka @qw4990

**Comment by winoros** [comment]
PointGet is using the `Get`/`BatchGet` protocol of the TiKV.

See the `Getter` and `BatchGetter` in `kv/kv.go`

It's used since the `Get` operation is lighter than the coprocessor layer in TiKV. When the number of the scanned rows are just one or other small number. The RPC cost will be reduced a lot compared with the coprocessor protocol.

**Comment by winoros** [comment]
But, yes, we need to change the checking condition to `path.StoreType == TiKV` for further extenstion.

**Comment by tisonkun** [comment]
@winoros thanks for your information. FYI https://github.com/pingcap/tidb/pull/24178

**Comment by coocood** [comment]
@tisonkun 
The reason point-get doesn't work on TiFlash is that TiFlash doesn't have any index.
