### ISSUE TITLE
count multiple expression doesn't return error.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#2429]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

`select count(a, b) from t`

2. What did you expect to see?

return a error.

3. What did you see instead?

executed successfully.

4. What version of Go are you using (`go version`)?

**Comment by idlesummerbreeze** [comment]
Hi @hanfei1991,

I found a test written by you and the count(a, b) is used:

`
result = tk.MustQuery("select count(distinct c,d), count(c,d) from t")
result.Check(testkit.Rows("5 6"))
` 
I think that @winoros is right about it. The `count(a,b)` should run into error.

If it is a bug, i will give it a try. I think that the problem comes from `parse.y.`

Regards,
Yu

**Comment by hanfei1991** [comment]
@idlesummerbreeze Yes, it's a bug. Thank you !

**Comment by ngaut** [comment]
@idlesummerbreeze Could you try to fix it? Feel free to ask any questions if you need help.
