### ISSUE TITLE
v5.0.1 - tidb_enable_async_commit and tidb_enable_1pc cannot be displayed

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#24411]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
![image](https://user-images.githubusercontent.com/21033020/116953460-df4c9080-acbf-11eb-807f-e093479fc1cd.png)

### 2. What did you expect to see? (Required)
tidb_enable_async_commit and tidb_enable_1pc can be displayed through `show variables`
like
![image](https://user-images.githubusercontent.com/21033020/116953505-03a86d00-acc0-11eb-89f3-448cf3bd41e9.png)

### 4. What is your TiDB version? (Required)
`mysql> \s
--------------
mysql  Ver 14.14 Distrib 5.6.48-88.0, for Linux (x86_64) using  6.2

Connection id:		5
Current database:	
Current user:		root@172.16.4.107
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.25-TiDB-v5.0.1 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible
Protocol version:	10
Connection:		172.16.4.107 via TCP/IP
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	utf8
Conn.  characterset:	utf8
TCP port:		24000
Uptime:			0 sec

Threads: 0  Questions: 0  Slow queries: 0  Opens: 0  Flush tables: 0  Open tables: 0  Queries per second avg: 0.000
--------------
`

**Comment by glkappe** [comment]
![image](https://user-images.githubusercontent.com/21033020/116953658-67329a80-acc0-11eb-9b26-4fe4411005e6.png)



How should I understand this phenomenon！

**Comment by morgo** [comment]
@glkappe This is intentional, you can se a list of the variables that are hidden here:

https://github.com/pingcap/tidb/blob/1145e347d3469d8e89f88dce86f6926ca44b3cd8/sessionctx/variable/tidb_vars.go#L699-L713

I am not a fan of it personally. In MySQL all variables always show up in the `SHOW VARIABLES` list.

**Comment by youjiali1995** [comment]
`tidb_enable_async_commit` and `tidb_enable_1pc` are hidden because they are switches for temporary use. For example, if there are some bugs, we may want to turn off them. And during the rolling upgrade, we can't turn them on because they are not compatible with the old version TiDB and use these variables to turn them on after the upgrade.  Normally, these features should be on at all times and we don't want users to use them.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
