### ISSUE TITLE
Enable pushdown for json_unquote

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb#24415]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For some reason, https://github.com/pingcap/tidb/pull/13837/commits/721782d9c11f739b5b38901427803581634498ec "forbid json unquote push down".

There's no indication of *why* it was necessary to forbid this or whether there is any feasible fix for the issue. We should address this limitation so that json_unquote can be pushed down.

**Comment by kolbe** [comment]
@lonng can you provide any additional information about why it was necessary to forbid pushdown of json_unquote to the coprocessor?

**Comment by lonng** [comment]
@kolbe I forbade the `json_unquote` pushdown switcher because I found the implementation inconsistent between TiKV and TiDB when I develop the `copr-test` testing framework last year. I just simply comment the `json_unquote` to make the subsequent works going on because I have no time to take an investigation at that time.

I am not sure does this inconsistent have been fixed in the last year. So I think we can uncomment the `json_unquote` to check the `copr-test` result.

And it's time to take an investigation if the `json_unquote` function if it's necessary for some scenarios.

**Comment by guo-shaoge** [comment]
The pushdown of json_unquote will be enabled after this [PR](https://github.com/tikv/tikv/pull/10177) is merged.

**Comment by kolbe** [comment]
@guo-shaoge can we demonstrate that this passes any set of tests to verify correctness? Are there any MySQL or MariaDB tests we can adopt?

**Comment by guo-shaoge** [comment]
> @guo-shaoge can we demonstrate that this passes any set of tests to verify correctness? Are there any MySQL or MariaDB tests we can adopt?

We have some tests for json_unquote in [copr-test](https://github.com/tikv/copr-test) and I verified that these cases are passed.

But the test coverage is very small(just 50 SQL). So maybe we should only enable the pushdown on master branch. And make more tests on json_XXX before next release.
