### ISSUE TITLE
Insert partition table error under NO_UNSIGNED_SUBTRACTION sql mode

### ISSUE THREAD

**Issue by zhuo-zhi** [pingcap/tidb#25437]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is a related issue to #24880, and should be fixed after [Pull/25435](https://github.com/pingcap/tidb/pull/25435).

```
SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
PARTITION p0 VALUES LESS THAN (-5),
PARTITION p1 VALUES LESS THAN (0),
PARTITION p2 VALUES LESS THAN (5),
PARTITION p3 VALUES LESS THAN (10),
PARTITION p4 VALUES LESS THAN (MAXVALUE)
);
INSERT INTO tu VALUES(0);
```

### 2. What did you expect to see? (Required)

Insert successfully.

MySQL behaves so.

### 3. What did you see instead (Required)

ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '(tu.c1 - 10)'

### 4. What is your TiDB version? (Required)

Master Branch

**Comment by zhuo-zhi** [comment]
The cause is as follows. 

Currently the partition expression used to locate partitions uses a mock context instead of the current context, and thus it cannot do unsigned subtraction producing negative results under NO_UNSIGNED_SUBTRACTION SQLMode. See [source code](https://github.com/pingcap/tidb/blob/master/table/tables/partition.go#L116). 

The fun `buildInsert` and all the following logic use the InfoSchema to get the partition table instance, but the InfoSchema generated never considers the current session context including sqlmode.

![image](https://user-images.githubusercontent.com/38810401/122387877-e692d980-cfa1-11eb-9659-6154c906613f.png)

@wjhuang2016 PTAL

**Comment by mjonss** [comment]
MySQL is not affected by sql_mode = 'NO_UNSIGNED_SUBTRACTION' for the insert, it works without warnings both with and without it, while TiDB failed both with and without it.
Simple test case:
```sql
DROP TABLE IF EXISTS tu;
SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
PARTITION p0 VALUES LESS THAN (0),
PARTITION pMax VALUES LESS THAN (MAXVALUE)
);
INSERT INTO tu VALUES(1);
show warnings;
SET @@sql_mode='';
INSERT INTO tu VALUES(2);
show warnings;
SELECT * FROM tu PARTITION (p0);
SELECT * FROM tu PARTITION (pMax);
DROP TABLE tu;
```
No errors or warnings for MySQL and errors for TiDB:
```ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '(tu.c1 - 10)'```

**Comment by mjonss** [comment]
I don't think we should implement a fix for this, since even MySQL is broken in this case.
```sql
SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
DROP TABLE IF EXISTS tu;
CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
PARTITION p0 VALUES LESS THAN (-5),
PARTITION pMax VALUES LESS THAN (MAXVALUE)
);
SET @@sql_mode='';
FLUSH TABLES;
SELECT * FROM tu;
DROP TABLE tu;
```
Where the `SELECT * FROM tu;` fails:
```sql
+-------+------+--------------------------------------------------------+
| Level | Code | Message                                                |
+-------+------+--------------------------------------------------------+
| Error | 1563 | Partition constant is out of partition function domain |
| Error | 1033 | Incorrect information in file: './mjtest/tu.frm'       |
+-------+------+--------------------------------------------------------+
```
due to the it tries to reparse the CREATE statement when opening the table, but with a different sql_mode. (Also notice the bug mentioning the non-existent tu.frm file, which was removed with the new data dictionary in MySQL 8.0)
I.e. MySQL needs sql_mode='NO_UNSIGNED_SUBTRACTION' when opening the table for it to work, and I don't think we should allow such dependency of sql_mode!
Also I don't see the real use case, since it also limits the practical usage of the `bigint unsigned` range. In this specific case is the partitioning expression `PARTITION BY (partitioning_expression)` and the partition values `PARTITION p0 VALUES LESS THAN (partition_value)` in fact `bigint` and not `bigint unsigned`.

**Comment by mjonss** [comment]
> The cause is as follows.
> ...
@zhuo-zhi I think this is a good thing, since metadata should never depend on sql_mode (that allows bugs as I described above in MySQL).

If we really want to fix this issue (which I would consider a minor bug, if a bug at all?) we could check if the partition function will return `bigint` or `bigint unsigned` together with if there are any negative partition values and if both signed and there are negative partition values, set the context to have `NO_UNSIGNED_SUBTRACTION` sql_mode.

I would propose that we keep things simple and not involving sql_mode more than absolutely necessary:
- Revert https://github.com/pingcap/tidb/pull/25435
- Closing this bug as 'Won't fix'
- Add to the documentation that we do not support negative partition values if partition column(s) are unsigned.

For the ones having a valid use case for negative partition values there is an easy workaround, add an offset to the partitioning expression so the result range is non-negative.

**Comment by bb7133** [comment]
I agree with @mjonss for 'keeping it simple(and clear)' and there is a workaround for negative partition values.
