### ISSUE TITLE
tidb_enable_strict_double_type_check default value is diff when upgrade from v4.0.x or v5.0.x

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#25607]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. tidb_enable_strict_double_type_check is added in v5.0.0-rc,
when upgrade from v4.0.x, tidb_enable_strict_double_type_check is off by default,
but when upgrade from v5.0.x, tidb_enable_strict_double_type_check is on by default.

2. tidb_merge_join_concurrency  is also added in v5.0.0-rc,
but it's default value is same when upgrade from v4.0.x and v5.0.x
3. tidb_enable_exchange_partition added in v5.0.0,
it's default value is same when upgrade from v4.0.x and v5.0.x

so the behavior for handle these params should be same, right?

### 4. What is your TiDB version? (Required)

v5.1.0

**Comment by seiya-annie** [comment]
same problem in enable-cross-table-merge and tidb_allow_batch_cop
for enable-cross-table-merge, default value is diff when upgrade from 4.0 or 5.0
for tidb_allow_batch_cop, default value is diff when upgrade from v4.0.0-v4.0.2 or v4.0.3-v5.0.2

**Comment by wshwsh12** [comment]
For tidb_enable_strict_double_type_check, the behavior is by design..  https://github.com/pingcap/tidb/blob/v5.0.2/session/bootstrap.go#L1194
For enable-cross-table-merge, the default value is changed in v5.0.2 ..  Release Note: https://docs.pingcap.com/tidb/stable/release-5.0.0#configuration-file-parameters
For tidb_allow_batch_cop, the default value is changed in v4.0.3.  Release Note: https://docs.pingcap.com/tidb/stable/release-4.0.3#improvements
@seiya-annie  PTAL
