### ISSUE TITLE
UPDATE result is not compatible with MySQL 

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#25645]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table companies(id bigint primary key, ida bigint);
insert into companies values(14, 14);
UPDATE companies SET id = id + 1, ida = id * 2;
```

### 2. What did you expect to see? (Required)
in the mysql, you can see
![image](https://user-images.githubusercontent.com/3427324/122853573-05e48a80-d345-11eb-9568-11bd872fa303.png)

### 3. What did you see instead (Required)
but in the tidb
![image](https://user-images.githubusercontent.com/3427324/122853658-26144980-d345-11eb-86fe-569a84741fbc.png)

### 4. What is your TiDB version? (Required)

Release Version: v5.2.0-alpha-122-g3132b5940-dirty
Edition: Community
Git Commit Hash: 3132b59402179fe6859dd17f84fec0a7173624b0
Git Branch: master

**Comment by tiancaiamao** [comment]
Yes, this behaviour is incompatible with MySQL.

However, if we change this behaviour, we will be incompatible with the old TiDB releases,
that would affect more customers who are running TiDB in their produce environment.

There are trade-offs, since this behaviour difference is not a real bug, we choose not to fix it.
I've add a `won't fix` tag.

**Comment by tiancaiamao** [comment]
I'll update the document for this

**Comment by tiancaiamao** [comment]
Introduced by https://github.com/pingcap/tidb/pull/20493
