### ISSUE TITLE
Support telemetry in local temporary tables

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#25942]

**Comment by lcwangchao** [comment]
We should discuss that what metrics should be added to telemetry for temporary tables. We can add a metric `LocalTemporaryTableExists` to indicate if feature local temporary table is used but it depends on instances and sessions. Because local temporary table only exists in session, we can find this value is true in some instances and false in other instances in the same cluster.

**Comment by Defined2014** [comment]
I think "telemetry" is no longer used, maybe we can close this issue. If I'm wrong, please reopen it.
