### ISSUE TITLE
Question for WrapCastForAggArgs: which aggregate function returns datetime, timestamp, duration

### ISSUE THREAD

**Issue by jiaohu** [pingcap/tidb#25962]
## General Question

HELP! In expression/aggregation/base_func.go, there is a code to wrap the args of an aggregate function with a cast function. However, i could not find a aggregate function to test the cases about `types.ETDatetime`, `types.ETTimestamp` ,`types.ETDuration`.  Could you please give me a sample?
```go
func (a *baseFuncDesc) WrapCastForAggArgs(ctx sessionctx.Context) {
	if len(a.Args) == 0 {
		return
	}
	if _, ok := noNeedCastAggFuncs[a.Name]; ok {
		return
	}
	var castFunc func(ctx sessionctx.Context, expr expression.Expression) expression.Expression
	switch retTp := a.RetTp; retTp.EvalType() {
	case types.ETInt:
		castFunc = expression.WrapWithCastAsInt
	case types.ETReal:
		castFunc = expression.WrapWithCastAsReal
	case types.ETString:
		castFunc = expression.WrapWithCastAsString
	case types.ETDecimal:
		castFunc = expression.WrapWithCastAsDecimal
	case types.ETDatetime, types.ETTimestamp:
		castFunc = func(ctx sessionctx.Context, expr expression.Expression) expression.Expression {
			return expression.WrapWithCastAsTime(ctx, expr, retTp)
		}
	case types.ETDuration:
		castFunc = expression.WrapWithCastAsDuration
	case types.ETJson:
		castFunc = expression.WrapWithCastAsJSON
	default:
		panic("should never happen in baseFuncDesc.WrapCastForAggArgs")
	}
...
}
```

**Comment by ljluestc** [comment]
```
CREATE TABLE test_table (
  id INT,
  datetime_column DATETIME,
  timestamp_column TIMESTAMP,
  duration_column TIME
);

INSERT INTO test_table VALUES
(1, '2023-07-22 12:34:56', '2023-07-22 12:34:56', '12:34:56'),
(2, '2023-07-23 01:23:45', '2023-07-23 01:23:45', '01:23:45'),
(3, '2023-07-24 23:59:59', '2023-07-24 23:59:59', '23:59:59');

```
Aggregate function with types.ETDatetime:
```
SELECT MAX(DATE(datetime_column)) FROM test_table;
```
This query will find the maximum date value from the datetime_column. The aggregate function MAX will be wrapped with the cast function expression.WrapWithCastAsTime because the datetime_column is of type DATETIME.

Aggregate function with types.ETTimestamp:
```
SELECT MAX(timestamp_column) FROM test_table;
```
This query will find the maximum timestamp value from the timestamp_column. The aggregate function MAX will be wrapped with the cast function expression.WrapWithCastAsTime because the timestamp_column is of type TIMESTAMP.

Aggregate function with types.ETDuration:
```
SELECT SUM(DURATION(duration_column)) FROM test_table;
```
This query will find the sum of the duration values from the duration_column. The aggregate function SUM will be wrapped with the cast function expression.WrapWithCastAsDuration because the duration_column is of type TIME.
