### ISSUE TITLE
Tracking issue for Cardinality Estimation Enhancement

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#26085]
## Enhancement
We're investigating flaws in our cardinality estimation logic and trying to fix them. And we're also trying to improve our cardinality estimation mechanism. This issue is for tracking the developments.

- [x] #26086
- [x] #26088
- [x] #26089
- [x] #26281 
- [x] #26282
- [x] #26283

**Comment by tangwz** [comment]
May I have a try?

**Comment by time-and-fate** [comment]
> May I have a try?

Thank you for that.
But some details of these items are still under discussion and we also have to complete them quickly. So I think we probably need to complete them internally.

**Comment by tisonkun** [comment]
> > May I have a try?
> 
> Thank you for that.
> But some details of these items are still under discussion and we also have to complete them quickly. So I think we probably need to complete them internally.

@time-and-fate is there a design document or pre-RFC? We may avoid discuss privately if unnecessary.

**Comment by qw4990** [comment]
Here are two simple discussion documents about these in this issue: https://docs.google.com/document/d/1IyxlOJAQY-lFpcId0nRJy4aVgm4Be1K5CUESsqSZNWk/edit?usp=sharing, https://docs.google.com/document/d/16sn1aoTfzQXBWR3QAztTpu-JnIzg8r23lMkRT8ua4Ck/edit?usp=sharing.
Since these items are found from our customers' feedbacks, they are relatively urgent and confidential, so we decided to complete them internally.
After finishing these urgent items, we'll publish more improvement items about Cardinality Estimation next sprint. Thanks for your understanding ~~~~ @tisonkun @tangwz

**Comment by tisonkun** [comment]
@time-and-fate @qw4990  is there any ongoing issues? If all subtasks closed, it should be a conclusion about the status of the tracking issue.

I'd like to ask for a design document or brief description about this "enhancement". Otherwise we implement feature secretly and hard to trace back even by ourselves.

**Comment by time-and-fate** [comment]
The tasks for this staged have been completed and the design docs are contained in the links above.
We are still planning about the next stage to see what needs to be done and their priority. We'll update this issue if there's any progress.

**Comment by tisonkun** [comment]
@time-and-fate the document above is private to PingCAP org. I'd prefer to see a brief description public in this PR or as a design document.

**Comment by qw4990** [comment]
Close since all tasks have been finished.
