### ISSUE TITLE
migrate test-infra to testify for `util/stmtsummary` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26420]

**Comment by feitian124** [comment]
i am alomst finish, see https://github.com/feitian124/tidb/tree/issue-26420
but i must fix  2 failed unit test.

```shell
❯ go test ./... --count=1
--- FAIL: TestPrevSQL (0.00s)
    statement_summary_test.go:1308: 
                Error Trace:    statement_summary_test.go:1308
                Error:          Not equal: 
                                expected: 2
                                actual  : 1
                Test:           TestPrevSQL
--- FAIL: TestAccessPrivilege (0.00s)
    statement_summary_test.go:1403: 
                Error Trace:    statement_summary_test.go:1403
                Error:          Not equal: 
                                expected: 32
                                actual  : 2
                Test:           TestAccessPrivilege
FAIL
FAIL    github.com/pingcap/tidb/util/stmtsummary        0.032s
FAIL
```

the orignal test implemented in `gocheck suite`, means 2 side effects:
- whole suite share one `stmtSummaryByDigestMap` instance
- the tests within a suite run in alphabetical order

while migrated to testify, i did not use suite, so it very likely the failed 2 is caused by shared states and order.

i need some dig, maybe for simple use suite too.
https://github.com/stretchr/testify/issues/194

could you please give some advise? thanks .  @tisonkun

**Comment by tisonkun** [comment]
You don't have to rely on global variable and just create ssmap for each test. Also in this way you can run test in parallel.

We don't keep bad smell legacy code and do mechanically migration.

You can take a look at [patch.diff.txt](https://github.com/pingcap/tidb/files/6910502/patch.diff.txt).

**Comment by tisonkun** [comment]
part 0 won't close this issue, will update PR description
