### ISSUE TITLE
AUTO_INCREMENT value can be adjusted small

### ISSUE THREAD

**Issue by Zhang-Chang-yu** [pingcap/tidb#26914]
## Feature Request

**Is your feature request related to a problem? Please describe:**
AUTO_INCREMENT value can be adjusted small

**Describe the feature you'd like:**
For example, 
table:test  AUTO_INCREMENT=141486388858,
alter table test AUTO_INCREMENT=2000000;
table:test  AUTO_INCREMENT=2000000.

[https://asktug.com/t/topic/94725/18](url)

**Comment by tangenta** [comment]
Currently, TiDB does not support alter the `auto_increment` ID to a smaller value. The only workaround is to recreate the whole table.

https://github.com/pingcap/tidb/pull/25868 supports this behavior:
```sql
ALTER TABLE `t` FORCE AUTO_INCREMENT = 3;
```
But it is unlikely to backport 5.0, 5.1 or 4.x. It will be usable in the next minor TiDB version(v5.3.0).

Please also attention: the FORCE keyword should be only used to recover metadata. All the write workload on the target table should be stopped and the ID should be the largest existing ID plus one(select max(id)+1 from t). Otherwise, it may lose row data.

**Comment by tangenta** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/25400.
