### ISSUE TITLE
Dependabot alerts introduced by merge BR into TiDB

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26983]
Shall we integrate with Dependabot to automatically create fix PR?

cc @haohaoxuex2005 @3pointer @zhouqiang-cl

**Comment by haohaoxuex2005** [comment]
There are two dependent components in pr (br/web/package-lock.json). The version is low and there is a security problem.
Remediation
Upgrade lodash to version 4.17.21 or later. For example:

"dependencies": {
  "lodash": ">=4.17.21"
}
or…
"devDependencies": {
  "lodash": ">=4.17.21"
}
------------------------------------------
Upgrade browserslist to version 4.16.5 or later. For example:

"dependencies": {
  "browserslist": ">=4.16.5"
}
or…
"devDependencies": {
  "browserslist": ">=4.16.5"
}

**Comment by s3nt3** [comment]
A brief analysis of the vulnerability alert:
1. The vulnerability of the browserlis module is a client denial of service with limited impact;
2. The vulnerability of the lodash module may cause more serious problems such as xss, so it is recommended to update to a version that is not affected by the vulnerability;

I want to express my thoughts on vulnerability management of third-party modules here. Currently we are facing the following problems:
1. How to collect vulnerability information of third-party modules. The vulnerability information of third-party modules is very fragmented, with various disclosure channels, no CVE numbers, and some are not even regarded as vulnerabilities, such as some performance optimization issues, which may be denial of service vulnerabilities in special scenarios;
2. Lack of analysis of the impact of vulnerabilities, which may cause some problems, because some third-party module vulnerabilities assessed as medium-risk or low-risk may actually have the impact of high-risk vulnerabilities;
3. Frequent module upgrades (there may be compatibility issues, so the R&D team needs to check) will bring additional costs to the R&D and testing teams;

I think enabling dependabot is a good solution. It can help us complete part of the vulnerability information collection and early alert work and part of the vulnerability fix work. But dependabot does not currently support Golang module vulnerability alerts.

On top of this, we can establish a third-party vulnerability fix process. For example, at first, the vulnerability alert information is processed by the security team to evaluate the impact of the vulnerability. If it can be determined that the risk of vulnerabilities is low, these low-risk vulnerabilities can be aggregated by the security team and delivered to the R&D team. The R&D team can update these vulnerable modules regularly, and regular updates can reduce the cost of updates. If the vulnerability may cause a high risk, the security team will notify the R&D team to urgently carry out a dependency upgrade.

**Comment by tisonkun** [comment]
closed by https://github.com/pingcap/tidb/pull/27729
