### ISSUE TITLE
TIDB_TRX can not parse CURRENT_SQL_DIGEST_TEXT where use two tidb

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#27058]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

drop table if exists t;
create table t (a int primary key, b int);
insert into t values (1, 10), (2, 20), (3, 30);
/* tidb0 */ begin;
/* tidb0 */ update t set b=11 where a =1;
/* tidb1 session1*/ update t set b=12 where a =1; ---block
/* tidb1 session2*/ select * from TIDB_TRX\G ---check result

### 2. What did you expect to see? (Required)

parse CURRENT_SQL_DIGEST and  CURRENT_SQL_DIGEST_TEXT correctly;

### 3. What did you see instead (Required)
parse CURRENT_SQL_DIGEST correctly, but CURRENT_SQL_DIGEST_TEXT is null,as follow:

mysql> select * from TIDB_TRX\G
*************************** 1. row ***************************
                     ID: 426921474408841217
             START_TIME: 2021-08-10 06:16:21.064000
     CURRENT_SQL_DIGEST: 3b491f15bc52ff182a37547ba0ccb3103f658e6d7935303836017fbf5cc0c75c
CURRENT_SQL_DIGEST_TEXT: NULL
                  STATE: Committing
     WAITING_START_TIME: NULL
        MEM_BUFFER_KEYS: 1
       MEM_BUFFER_BYTES: 29
             SESSION_ID: 7
                   USER: root
                     DB: test
        ALL_SQL_DIGESTS: ["3b491f15bc52ff182a37547ba0ccb3103f658e6d7935303836017fbf5cc0c75c"]
1 row in set (0.00 sec)

### 4. What is your TiDB version? (Required)

Release Version: v5.2.0-alpha-562-ge539f9d62
Edition: Community
Git Commit Hash: e539f9d62f8755f7b1894848f8bd8c7bb83db3ca
Git Branch: master
UTC Build Time: 2021-08-09 11:35:07
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by MyonKeminta** [comment]
This is an expected behavior on our current implementation.

* `information_schema.tidb_trx` internally uses `statements_summary` and `statements_summary_history` tables to retrieve the `current_sql_digest_text` information, so it only access only the current TIDB node to retrieve `current_sql_digest_text` information. `cluster_statements_summary` and `cluster_statements_summary_history` is not used,  in order to reduce the overhead.
* Currently, only statements that has been finished will be collected to statement summary tables.

So in this case, the *tidb1* executes the statement "update t set b=12 where a =1;" for the first time and has not yet finished. At this time, it's expected that we cannot get the SQL digest text on this node.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
