### ISSUE TITLE
Audit Plugin API enhancements

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#27268]
## Enhancement

The audit plugin API currently only logs statements on successful completion. This means that long running statements (which SQL injections often are) will not be logged immediately.

Errors are also not logged, which could be generated by privilege errors, SQL injection attempts etc. These are important for anomoly detection systems.

**Comment by djshow832** [comment]
Since errors are generated during the execution, so maybe the approach is to log 2 messages for each statement. One is logged before the execution (and even before the parser) and another is logged (with the error code) after the execution.
Besides, we need to consider the compatibility problem because some commercial users already rely on the plugin.

**Comment by morgo** [comment]
> Since errors are generated during the execution, so maybe the approach is to log 2 messages for each statement. One is logged before the execution (and even before the parser) and another is logged (with the error code) after the execution.

I am curious why you say before parsing? I had thought after parsing might be more useful, since currently we log the digest for statements and not the statement itself.

> Besides, we need to consider the compatibility problem because some commercial users already rely on the plugin.

It is easy to fix this in the plugin before release. The `OnGeneralEvent` already includes the event type (`event plugin.GeneralEvent`), but currently the audit plugin doesn't do anything witrh it.
