### ISSUE TITLE
run sysbench update and select *，sysbench return error

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#27524]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
2tidb、3pd、4tikv：4C、8G mem
1、run sysbench update
     tables：32
     threads：512
2、run select * from sbtest limit 1,100

### 2. What did you expect to see? (Required)
sysbench run normally

### 3. What did you see instead (Required)
sysbench return error
FATAL: mysql_stmt_execute() returned error 8022 (Error: KV error safe to retry Error(Txn(Error(Mvcc(Error(TxnLockNotFound { start_ts: TimeStamp(427235393597079608), commit_ts: TimeStamp(427235470641201166), key: [116, 128, 0, 0, 0, 0, 0, 0, 65, 95, 114, 128, 0, 0, 0, 0, 76, 179, 229] }))))) {tableID=65, handle=5026789} [try again later]) for query 'COMMIT'

### 4. What is your TiDB version? (Required)
Release Version: v5.2.0
Edition: Community
Git Commit Hash: b4aac518c8bdb54bc5628e9cf4a093e006418940
Git Branch: heads/refs/tags/v5.2.0
UTC Build Time: 2021-08-20 15:58:14
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by sticnarf** [comment]
![图片](https://user-images.githubusercontent.com/17217495/130570059-2d0302b5-5b1e-4f87-a6c6-10f75d2a3df3.png)
When write requests take minute-level to finish, the TTL may expire at once and heartbeats may be not able to update the TTL in time.

This reminds us that the throttle time should not be too long. It's better to drop the request earlier rather than let it wait at TiKV.

**Comment by zyguan** [comment]
No update for a long time, feel free to reopen it if the issue still exists.
