### ISSUE TITLE
group_concat returns wrong results after set group_concat_max_len

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#27751]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql>  create table test.t(id int not null, nid int, name char(20) not null, nname char(20), score float not null, nscore float, birth date not null, nbirth date);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test.t values (1,2, '2','2',1.1,1.2, '2021-08-01','2021-08-02'),(2,null,'B',null,2.3,null,'2021-08-12',null),(1,11, '1','11',1.1,1.2, '2021-08-01','2021-08-03'),(2,2,'2','2',2.2,null,'2021-08-4',null),(3,null,'B',null,2.2,null,'2021-08-12',null),(1,2, '2','2',1.1,1.2, '2021-08-01','2021-08-02'),(2,null,'B',null,2.3,null,'2021-08-12',null),(1,11, '1','11',1.1,1.2, '2021-08-01','2021-08-03'),(2,2,'3','33',2.2,null,'2021-08-4',null);
Query OK, 9 rows affected (0.00 sec)
Records: 9  Duplicates: 0  Warnings: 0

mysql> select group_concat(nname order by 1 separator '#' ) from t;
+-----------------------------------------------+
| group_concat(nname order by 1 separator '#' ) |
+-----------------------------------------------+
| 11#11#2#2#2#33                                |
+-----------------------------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
from mysql 8
```
mysql> set @@group_concat_max_len=0; select group_concat(nname order by 1 separator '#' ) from t;
Query OK, 0 rows affected, 1 warning (0.00 sec)

+-----------------------------------------------+
| group_concat(nname order by 1 separator '#' ) |
+-----------------------------------------------+
| 11#1                                          |
+-----------------------------------------------+
```
### 3. What did you see instead (Required)
```
mysql> set @@group_concat_max_len=0; select group_concat(nname order by 1 separator '#' ) from t;
Query OK, 0 rows affected, 1 warning (0.00 sec)

+-----------------------------------------------+
| group_concat(nname order by 1 separator '#' ) |
+-----------------------------------------------+
| 1#11                                          |
+-----------------------------------------------+
```
### 4. What is your TiDB version? (Required)
master

**Comment by birdstorm** [comment]
[reference](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_group_concat_max_len)
`group_concat_max_len` has a minimum value of 4. When TiDB checks whether the length of the return string exceeds the limit of `group_concat_max_len`, it pushes the truncated string into a heap and thus sorts the result.
e.g., max_len=4, the result string is `11#11`. After truncating, the latter value becomes `1` and after the sort, the result string becomes `1#11` instead of `11#1`.

**Comment by birdstorm** [comment]
[reference](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_group_concat_max_len)
`group_concat_max_len` has a minimum value of 4. When TiDB checks whether the length of the return string exceeds the limit of `group_concat_max_len`, it pushes the truncated string into a heap and thus sorts the result.
e.g., max_len=4, the result string is `11#11`. After truncating, the latter value becomes `1` and after the sort, the result string becomes `1#11` instead of `11#1`.
