### ISSUE TITLE
migrate test-infra to testify for `br/pkg/lightning/backend`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28234]
* [x] #29978
* [x] #29979
* [x] #29980
* [x] #29981
* [x] #29982
* [x] #29983

**Comment by gozssky** [comment]
Hi @ArberSephirotheca, I'm working for restructuring the code under `br/pkg/lightning/backend/local`. Meanwhile, the test will be restructured too. I'm not sure if you have already had some work done on this. If you haven't started yet, how about split this task into multiple sub tasks? Since there is much code under `br/pkg/lightning/backend`🤣.

**Comment by ArberSephirotheca** [comment]
@gozssky  Sure, I was looking at the code this week and haven't started the migration. It is indeed a lot of code, so It would be great if I can begin with smaller part.

**Comment by gozssky** [comment]
@tisonkun As discussed above, could you please help to divide this task into multiple subtasks?

**Comment by tisonkun** [comment]
@gozssky @ArberSephirotheca created. Feel free to take subtasks.
