### ISSUE TITLE
INFORMATION_SCHEMA.table_constraints does not show foreign key constraint 

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tidb#28918]
## Bug Report

INFORMATION_SCHEMA.table_constraints does not show foreign key constraint, but GORM will use this table to check if it's needed to create the foreign key when AutoMigrate a model.
https://github.com/go-gorm/gorm/blob/9a5ba376042427be60899f5f93ccdaf0b5a0ef83/migrator/migrator.go#L572

From the code, it seems TiDB only include the primary key and indices, 
https://github.com/pingcap/tidb/blob/fce1a03e40d4aade17793e2da0cd0589d9b25588/executor/infoschema_reader.go#L1596

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create tables with foreign key 
```sql
use test;

 CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `t2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t1_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  CONSTRAINT `fk_t2_t1` FOREIGN KEY (`t1_id`) REFERENCES `t1` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

```

2. check the INFORMATION_SCHEMA.table_constraints info of table t2
```sql
SELECT *  FROM INFORMATION_SCHEMA.table_constraints WHERE constraint_schema = 'test' AND table_name = 't2'
``` 

### 2. What did you expect to see? (Required)

MySQL root@(none):test> SELECT *  FROM INFORMATION_SCHEMA.table_constraints WHERE constraint_schema
                     -> = 'test' AND table_name = 't2';
+--------------------+-------------------+-----------------+--------------+------------+-----------------+
| CONSTRAINT_CATALOG | CONSTRAINT_SCHEMA | CONSTRAINT_NAME | TABLE_SCHEMA | TABLE_NAME | CONSTRAINT_TYPE |
+--------------------+-------------------+-----------------+--------------+------------+-----------------+
| def                | test              | PRIMARY         | test         | t2         | PRIMARY KEY     |
| def                | test              | fk_t2_t1        | test         | t2         | FOREIGN KEY     |
+--------------------+-------------------+-----------------+--------------+------------+-----------------+

### 3. What did you see instead (Required)

mysql> SELECT *  FROM INFORMATION_SCHEMA.table_constraints WHERE constraint_schema = 'cdc_perf' AND table_name = 't2';
+--------------------+-------------------+-----------------+--------------+------------+-----------------+
| CONSTRAINT_CATALOG | CONSTRAINT_SCHEMA | CONSTRAINT_NAME | TABLE_SCHEMA | TABLE_NAME | CONSTRAINT_TYPE |
+--------------------+-------------------+-----------------+--------------+------------+-----------------+
| def                | test          | PRIMARY         | test     | t2         | PRIMARY KEY     |
+--------------------+-------------------+-----------------+--------------+------------+-----------------+

### 4. What is your TiDB version? (Required)

```
| Release Version: v5.2.0
Edition: Community
Git Commit Hash: 9d798d5acfdce77d88e5985e91a85c2c46a46c91
Git Branch: heads/refs/tags/v5.2.0
UTC Build Time: 2021-08-25 02:15:52
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by omaskery** [comment]
Note that this issue affects users of https://github.com/ent/ent as well, as it also uses the `TABLE_CONSTRAINTS` table to identify whether foreign key constraints need adding, and then fails when TiDB refuses to add a duplicate constraint.

We only ran into this problem after upgrading from 4.x to 5.x, so I'm assuming that newer versions of TiDB now store enough information about foreign key constraints to detect duplicates (e.g. in `KEY_COLUMN_USAGE`), or has recently started preventing duplicate foreign key definitions, but doesn't store enough information to prevent systems like Ent or Gorm from attempting to create such duplicates.

It feels like, if TiDB doesn'ts upport foreign key constraints, it should consistently either:
* Populate `KEY_COLUMN_USAGE` and `TABLE_CONSTRAINTS` (and any other such tables) appropriately
* Not populate any such tables, and treat foreign key declarations as no-ops

In `ent` this can be worked around by disabling foreign key constraints when performing migration:

```go
err = client.Schema.Create(ctx, migrate.WithForeignKeys(false))
```

This should be fine if using TiDB, since it doesn't enforce them anyway.

I don't know if Gorm has a similar function.

**Comment by morgo** [comment]
This should be easy to add for compatibility. For a similar PR, see https://github.com/pingcap/tidb/pull/26450
