### ISSUE TITLE
LOCK TABLE T1 write;  does not raise error or warning

### ISSUE THREAD

**Issue by Alkaagr81** [pingcap/tidb#28967]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
--sesson 1
drop table if exists t1,t2,t3,t11,t12;
CREATE TABLE t1 (a tinyint(3), b tinyint(5));
INSERT INTO t1 VALUES (1,1);
LOCK TABLE t1 write;

--session 2
INSERT INTO t1 VALUES (1,2); --lock wait timeout and eventually fail
```

### 2. What did you expect to see? (Required)

This should return an error if not possible:

```sql
mysql> INSERT INTO t1 VALUES (1,2);   --lock wait timeout and eventually fail
```

### 3. What did you see instead (Required)

```sql
--session 1
drop table if exists t1,t2,t3,t11,t12;
CREATE TABLE t1 (a tinyint(3), b tinyint(5));
INSERT INTO t1 VALUES (1,1);
LOCK TABLE t1 write;

--session 2
INSERT INTO t1 VALUES (1,2); --session 2 is still allow to insert data in t1
```
### 4. What is your TiDB version? (Required)

```sql
 Release Version: v5.2.1                                          +
 Edition: Community                                               +
 Git Commit Hash: cd8fb24c5f7ebd9d479ed228bb41848bd5e97445        +
 Git Branch: heads/refs/tags/v5.2.1                               +
 UTC Build Time: 2021-09-08 02:29:53                              +
 GoVersion: go1.16.4                                              +
 Race Enabled: false                                              +
 TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306+
 Check Table Before Drop: false 
(1 row)
```

**Comment by morgo** [comment]
I took a look into this today. It might be that TiDB needs to permit this syntax to work with restores from mysqldump, but it should be possible to at least return a warning when [`tidb_enable_noop_funcs`](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_noop_functions-new-in-v40) is  set to`OFF`. Otherwise users might be led to believe that the table is being locked, and this could lead to data corruption cases.

**Comment by Defined2014** [comment]
The lock/unlock table feature is implemented by #10343 which is controled by `enable-table-lock` in config file.
After discussed with @crazycs520 , he didn't suggest us default enable this function because it will cause performance degradation.
Maybe we could add warning information when `enable-table-lock` equals `false`. What do you think of it? @morgo

**Comment by morgo** [comment]
> The lock/unlock table feature is implemented by #10343 which is controled by `enable-table-lock` in config file. After discussed with @crazycs520 , he didn't suggest us default enable this function because it will cause performance degradation. Maybe we could add warning information when `enable-table-lock` equals `false`. What do you think of it? @morgo

Yes, a warning is much better than noop.

**Comment by jebter** [comment]
Do we need to adjust the severity to moderate？ @morgo @Defined2014

**Comment by morgo** [comment]
> Do we need to adjust the severity to moderate？ @morgo @Defined2014

By triage definition it is critical: TiDB is implying that it is locking tables while giving no feedback to users. This has a high chance of leading to data corruption.
