### ISSUE TITLE
global `sql_auto_is_null`  is not controlled by noop funciton 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#29587]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

MySQL [(none)]> SET sql_auto_is_null = 1;
ERROR 1235 (42000): function sql_auto_is_null has only noop implementation in tidb now, use tidb_enable_noop_functions to enable these functions
MySQL [(none)]> set global sql_auto_is_null = 1;
Query OK, 0 rows affected (0.01 sec)

MySQL [(none)]> select @@tidb_enable_noop_functions;
+------------------------------+
| @@tidb_enable_noop_functions |
+------------------------------+
| OFF                          |
+------------------------------+
1 row in set (0.00 sec)

### 2. What did you expect to see? (Required)
session and global level setting will all be forbidden
### 3. What did you see instead (Required)
global level is allowed
### 4. What is your TiDB version? (Required)
v5.3.0

**Comment by seiya-annie** [comment]
refer to https://github.com/pingcap/tidb/issues/28230,

**Comment by seiya-annie** [comment]
MySQL [(none)]> show global variables like '%noop%';
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_noop_functions | 0     |
+----------------------------+-------+
1 row in set (0.02 sec)

MySQL [(none)]>

**Comment by morgo** [comment]
Thank you for the bug report. This might be an upgrade issue - notice how the value of tidn_enable_noop_functions is `0` in global context. We validate variables when a session is created, which normalizes them.

But I checked, and in global context they are not currently normalized. If this turns out to be the root cause, we should normalize in global scope so we can lessen the permutations the code has to handle.

**Comment by morgo** [comment]
This is confirmed as an upgrade issue. I will take a look.
