### ISSUE TITLE
br restore hang, the dataset is backup with stats

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#30135]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

restore same dataset as #29033, restore a 60GB backup with 2820 tables, --ignore-stats=false

### 2. What did you expect to see? (Required)
finished in half hour

### 3. What did you see instead (Required)
hang at 75.52% after 10 hours

### 4. What is your TiDB version? (Required)

`component br version v5.4.0-nightly-20211117 is already installed`
tidb v5.3.0

**Comment by YuJuncen** [comment]
According to the goroutine dump, it stuck at:
```
goroutine 149949 [semacquire, 830 minutes]:
sync.runtime_Semacquire(0x401c583088)
	/usr/local/go1.16.4/src/runtime/sema.go:56 +0x38
sync.(*WaitGroup).Wait(0x401c583080)
	/usr/local/go1.16.4/src/sync/waitgroup.go:130 +0x74
github.com/pingcap/tidb/br/pkg/restore.(*tikvSender).waitTablesDone(0x40114f6b00, 0x4029144180, 0x8, 0x8)
	/home/jenkins/workspace/build-linux-arm64-4.0/go/src/github.com/pingcap/br/br/pkg/restore/pipeline_items.go:334 +0xb0
github.com/pingcap/tidb/br/pkg/restore.(*tikvSender).restoreWorker.func2(0x4029498900, 0x4028fed510)
	/home/jenkins/workspace/build-linux-arm64-4.0/go/src/github.com/pingcap/br/br/pkg/restore/pipeline_items.go:367 +0x1b0
golang.org/x/sync/errgroup.(*Group).Go.func1(0x4017f9a360, 0x402ae32c60)
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x60
```

The code here "wait" some table to be fully restored and send them to the next step. But it didn't involve some context for exit, so it get stuck at here, then the whole pipeline.

The restore already failed at `[2021/11/24 20:04:56.498 +08:00]` due to a corrupted SST file: `[BR:KV:ErrKVDownloadFailed]download sst failed; Engine Engine("Corruption: Bad table magic number: expected 9863518390377041911, found 0 in `****/import/.temp/889d7ae3-63b9-4be1-8910-e31113cff91e_1301_5_283_write.sst")`.

Download the SST file
`6_2777_560_5e177656a67de4ac3b27d375637a26f4249fc4150399a58a00931a99e3cd6aba_1637594103203_write.sst` and check it, it did get corrupted :(.

```
> rocksdb_sst_dump --command=verify --show_properties --file=./6_2777_560_5e177656a67de4ac3b27d375637a26f4249fc4150399a58a00931a99e3cd6aba_1637594103203_write.sst
options.env is 0x100f0d170
Process ./6_2777_560_5e177656a67de4ac3b27d375637a26f4249fc4150399a58a00931a99e3cd6aba_1637594103203_write.sst
Not able to read table properties
Sst file format: block-based(old version)
./6_2777_560_5e177656a67de4ac3b27d375637a26f4249fc4150399a58a00931a99e3cd6aba_1637594103203_write.sst: Corruption: Bad table magic number: expected 9863518390377041911, found 0 in ./6_2777_560_5e177656a67de4ac3b27d375637a26f4249fc4150399a58a00931a99e3cd6aba_1637594103203_write.sst
./6_2777_560_5e177656a67de4ac3b27d375637a26f4249fc4150399a58a00931a99e3cd6aba_1637594103203_write.sst is not a valid SST file
```

**Comment by fengou1** [comment]
I agreed with Juncen, waitTablesDone does not handle context cancel.
