### ISSUE TITLE
TiDB vs MySQL on single server

### ISSUE THREAD

**Issue by kokizzu** [pingcap/tidb#31879]
## General Question

Is there any improvement plan for debunking [this article](https://www.percona.com/blog/2019/01/24/a-quick-look-into-tidb-performance-on-a-single-server/)
Since most people's use cases are single server at beginning, then scale out when they already got traction/need to grow, that article looks like a dealbreaker for smaller startups to adopt TiDB at early stage (1 TiDB, 1-3 TiKV, 1 PD, 1 TiFlash), they would probably still choose mysql/postgresql (1 master 2 replica instance/VM) then migrate, and migrating databases is quite painful (except for databases that can do automatic logical replication from mysql/postgresql like clickhouse, but still buggy).
If we can take adoption early on for smaller startup, "high performance even on single node and no-migration (from mysql/mariadb) needed to scale out" will be best selling point for TiDB other than "easy scale out and hybrid-HTAP".

**Comment by morgo** [comment]
Hi @kokizzu, thank you for your interest in this :-) I think this blog post raised a few interesting findings, so I want to be careful not to be too critical of it. The results for the write-only test were lower than we expected, and should have improved in recent versions.

It is important to read into this benchmark correctly: it was testing an unsupported install method with a relatively small dataset by TiDB standards (flightstats is about 90GB, TiDB is typically recommended for 1TB+). In many ways it was a best case for MySQL against a worst case for TiDB. If the dataset was larger, and it was comparing against replica sets in MySQL (or Group Replication) TiDB actually becomes more efficient because it will balance (aka schedule) activity across all TiKV nodes.

To maybe paraphrase your question: there might be some users who at a smaller scale will still invest in TiDB because they anticipate growth. You can think of this as like paying for insurance, some users will do it, others might not. The Percona article hilights that overhead, but it is certainly not typical of expected deployments.

**Comment by morgo** [comment]
I'm going to close this issue for now, but please feel free to reopen if you have further questions.

**Comment by morgo** [comment]
I posted about this in more details here: https://tidb-blog.vercel.app/posts/the-most-underrated-tidb-feature
