### ISSUE TITLE
BR support for placement rules

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#32290]
For BR, when creating a full backup placement rules (all placement policies, not just those in use) will be dumped. Upon a full restore of a backup, they will be restored.

On a partial restore (i.e. one table) they will not be restored, since the behavior around restoring the policy first is unclear.

**Comment by lcwangchao** [comment]
- Back up TiDB placement Policies
  - When backuping the entire cluster (using `br backup full`), br will back up the tidb placement policies;
  - Otherwise, While backuping the specified database/table (using `br backup db/table` or [table filter](https://docs.pingcap.com/tidb/stable/use-br-command-line-tool#back-up-with-table-filter)), placement policies are not backed up;
  - policy options in the  `create table` statement will be always backed up in br backup.

**Comment by 3pointer** [comment]
To implement this. we need to do following things.
* [ ] Add a policyInfos field in [`BackupMeta` ](https://github.com/pingcap/kvproto/blob/47a2e9ec6efa20d9572fb92eccad69f091e305fb/proto/brpb.proto#L18)
* [ ] Write policyInfos to `BackupMeta` before `BackupSchemas` when we are in full backup. https://github.com/pingcap/tidb/blob/b9bd5a7d7e4dd00ee730d4cc32ca1de6a905708f/br/pkg/task/backup.go#L454
* [ ] Implement `getPolicyInfos`, `createPolicysWithInfo`,`createPolicyWithInfo` for backup and restore.
* [ ] Restore all policyInfos before create tables during full restoration through `createPolicysWithInfos` API.
* [ ] Restore related policyInfos when create table during table restoration through `createPolicysWithInfo` API.

**Comment by lcwangchao** [comment]
@3pointer I think `getPolicyInfos` , `createPolicysWithInfo` , `createPolicyWithInfo` will be added to the `ddl.DDL` interface  ? For `getPolicyInfos` , the package `meta` also provides a method `meta.ListPolicies` , can you use it instead

**Comment by 3pointer** [comment]
`meta.ListPolicies` is fine.

**Comment by lcwangchao** [comment]
After discussion. We can only provide `createPolicysWithInfo`
