### ISSUE TITLE
The order of system variables is messy.

### ISSUE THREAD

**Issue by CbcWestwolf** [pingcap/tidb#33086]
## Enhancement

The system variables are declared in `sysvar.go`. With the increase in the number of sysvars, their order tends to be messy.

With the introduction of the INSTANCE scope, I think it may be better to re-organize the sysvars by their scopes.

**Comment by morgo** [comment]
I agree it would be useful to be more organized :-) Either by scope or function area (since some variables of the same function will have different scopes).

For user documentation we have them in alphabetical order, but constantly introduce cases where we break the order :( I have a script that I run every few weeks to fix it. You can see the typical bugs introduced in https://github.com/pingcap/docs/pull/7737
