### ISSUE TITLE
MySQL prevents the rename of any role which has been granted , TiDB is not.

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#33710]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop user if exists u1,r1,r11;
CREATE USER u1,r1;
GRANT r1 to u1;
show grants for u1;
RENAME USER r1 to r11;

```
### 2. What did you expect to see? (Required)
```sql
mysql> CREATE USER u1,r1;
Query OK, 0 rows affected (0.00 sec)

mysql> GRANT r1 to u1;
Query OK, 0 rows affected (0.00 sec)

mysql> show grants for u1;
+--------------------------------+
| Grants for u1@%                |
+--------------------------------+
| GRANT USAGE ON *.* TO `u1`@`%` |
| GRANT `r1`@`%` TO `u1`@`%`     |
+--------------------------------+
2 rows in set (0.00 sec)

mysql> RENAME USER r1 to r11;
ERROR 3532 (HY000): Renaming of a role identifier is forbidden
```
### 3. What did you see instead (Required)
```sql
mysql> CREATE USER u1,r1;
Query OK, 0 rows affected (0.00 sec)

mysql> GRANT r1 to u1;
Query OK, 0 rows affected (0.01 sec)

mysql> show grants for u1;
+--------------------------------+
| Grants for u1@%                |
+--------------------------------+
| GRANT USAGE ON *.* TO 'u1'@'%' |
| GRANT 'r1'@'%' TO 'u1'@'%'     |
+--------------------------------+
2 rows in set (0.00 sec)

mysql> RENAME USER r1 to r11;
Query OK, 0 rows affected (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.5.0-alpha-182-gad9430039
Edition: Community
Git Commit Hash: ad9430039f54bb9af78d44831c176bc5eafcbba0
Git Branch: master
UTC Build Time: 2022-03-28 14:04:35
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by littlelittlehorse** [comment]
check it manually,  It does exist, in the example, renaming r1 will fail, but u1 not.

**Comment by littlelittlehorse** [comment]
@morgo Hi morgo, tidb support user name change in the case, but mysql does not.  Do you think need to change it to be consistent with mysql?

**Comment by morgo** [comment]
> @morgo Hi morgo, TiDB support user name change in the case, but MySQL does not. Do you think need to change it to be consistent with MySQL?

I am not sure why MySQL places this restriction. It is likely that it is intentional because @ramanich1 discovered this in a test. It could be security-related (changing a role could create a scenario where the server is tricked into giving more access to a user).
 
> if TiDB is changed to be consistent, will there be any problem with TiDB？

We can never be 100% sure, but I believe the risk is very low. Very few users will rename roles.

**Comment by ymkzpx** [comment]
@bb7133 @zimulala i think this issue only is a compatibility, tidb allow more larger, maybe can remove bug label？

**Comment by bb7133** [comment]
I don't think this is a problem for TiDB since:

1) As @morgo described, very few users will rename roles.
2) TiDB has less restriction compared with MySQL, but the behavior is correct, this is only about compatibility.
3) Role-related operations are not replicated, so we do not need to worry about the compatibility issue when replicating from TiDB to MySQL.

I think we could set this issue to 'won't fix'.
