### ISSUE TITLE
simplify SET GLOBAL code

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#33896]
## Enhancement

Currently to add a GLOBAL variable which needs to execute code (i.e. specifies a SetGlobal func), you also need to add code to `domain/sysvar_cache.go` to ensure that it runs on other tidb server instances.

The code is not DRY, and difficult to test since `sysvar_cache.go` relies on an etcd server being present, which we don't have in the unit tests. This can make it the source of subtle bugs, since the initiating tidb-server runs the SetGlobal func but peers do not.

**Comment by YangKeao** [comment]
I have another question :thinking: . If I'll need a Context (`context.Context`) to access the storage (e.g. set/get something from the pd), what's the best practice? Ideally, this context comes from two places: the statement or the http request (which sets the variable). However, the set/get functions are also used in some other parts directly in the tidb code bases, where there is not a `Context`.

I've tried to add a Context arguments for all related functions, which turns out to be unrealistic (the change is too big!). Could you give me some advice on this scenario? (or simply use a newly created context with deadline?).

I'll access the storage in https://github.com/pingcap/tidb/pull/38276, to set/get an external timestamp in PD.
