### ISSUE TITLE
"references invalid table" when show columns from view

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#34090]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
use test;
drop table if exists t1, t2;
drop view if exists v1;
create table t1 (a int);
insert into t1 values (0), (1), (2), (3), (4);
create table t2 (a int);
insert into t2 values (1), (2), (3), (4), (5);

create view v1 as with t1 as (
  select a from t2 where t2.a=3
  union
  select t2.a+1 from t1,t2 where t1.a=t2.a)
select * from t1;

-- show columns from another db
create database if not exists test1;
use test1;
show columns from test.v1;
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

```
ERROR 1356 (HY000): View 'test.v1' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```

### 4. What is your TiDB version? (Required)

Both 7e170850 (before https://github.com/pingcap/tidb/pull/33991) and 212a6b22 (master) have this problem.

**Comment by likzn** [comment]
I find two information.
1.The actul error is `ErrNoSuchTable`. The error assert do not work .Maybe the type is not correct.I use `infoschema.ErrTableNotExists` and it can judge successfully.The real error msg is `[schema:1146]Table 'test1.t1' doesn't exist
`.The reason is in the second point
https://github.com/pingcap/tidb/blob/6aa143d6db929517e95b697ec9e947e7d8a7c4ba/planner/core/logical_plan_builder.go#L4592-L4601
2.Because the CTE should not add schema in the `preprocess`.And the CTE name is equal selectStms table name in the case(CTE name is t1 and real table name also is t1).So `preprocess` can not add schema into the real table successfuly.
Maybe we need deal with `handleTableName ` separately with` CTE name` and `real table name`.
https://github.com/pingcap/tidb/blob/6aa143d6db929517e95b697ec9e947e7d8a7c4ba/planner/core/preprocess.go#L1431-L1437

**Comment by tangenta** [comment]
For the recursive CTE, it is necessary to skip assigning the schema name. Maybe we need to add a check like

```
if _, ok := p.withName[tn.Name.L] && isRecursive; ok { 
 	return 
 } 
```

@likzn Do you want to fix this issue? If you are interested, please run `/assign` to pick it up.

**Comment by VelocityLight** [comment]
update
