### ISSUE TITLE
lightning: extra slash before gcs files

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#34118]
## Bug Report
import using gcs storage, address like: `gcs://xxx_test/xxx_test3?region=ap-northeast-1`, with no trailing slash, on import:
```
file is filtered by file router"] [path=/test.t1.000000000.csv]
```
configing pattern to: `pattern: ^test\\.t.*$`. has to add another `.*` to the beginning of the pattern to make it import.

### 2. What did you expect to see? (Required)
match the file
### 3. What did you see instead (Required)
failed to match
### 4. What is your TiDB version? (Required)
lightning 5.3.1

**Comment by Ehco1996** [comment]
@D3Hunter 

after some investigation, I think this is not actually a bug, it's because user input `mydumper.files.pattern` config is not right

Whether you enter a url with slash or not, gcs backend will remove the slash for you, see code [here](https://github.com/pingcap/tidb/blob/master/br/pkg/storage/parse.go#L88)

it means for both URL: `gcs://lightning-gcs/gcs_test/?endpoint=http://localhost:21808/storage/v1/`  and
`gcs://lightning-gcs/gcs_test?endpoint=http://localhost:21808/storage/v1/`, you always got the gcs objects with prefix: `gcs`

and when using the  `defaultFileRouteRules`, we also take into account that the file name is with `/` see [here](https://github.com/pingcap/tidb/blob/1d2a0b998deb3cd7b7b49712d66e09186eb06e60/br/pkg/lightning/mydump/router.go#L113)
