### ISSUE TITLE
br/pkg/storage: s3 sdk support to access aliyun oss by ram type

### ISSUE THREAD

**Issue by knull-cn** [pingcap/tidb#34224]
## Feature Request

**Is your feature request related to a problem? Please describe:**

no
**Describe the feature you'd like:**

use s3 sdk, access aliyun oss by ram type: on ram ecs, can auto request the sts token ,then use sts token to access oss.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

the doc at aliyun , example for python : [基于临时凭证，使用Python SDK访问OSS](https://partners-intl.aliyun.com/help/zh/elastic-compute-service/latest/use-ram-roles-to-access-other-alibaba-cloud-services#section-fgc-wkp-1gq)

**Comment by kennytm** [comment]
@knull-cn The implementation #34309 for this will cause all tools (Dumpling, Lightning, BR) running on Aliyun ECS using OSS as storage to *ignore* AK/SK defined in environment variables and `~/.aws/credentials`. This is 

1. undocumented
2. inconsistent with the credential chain for AWS which follows the environment → file → IAM role load order

Please check if this is intentional.

**Comment by knull-cn** [comment]
> @knull-cn The implementation #34309 for this will cause all tools (Dumpling, Lightning, BR) running on Aliyun ECS using OSS as storage to _ignore_ AK/SK defined in environment variables and `~/.aws/credentials`. This is
> 
> 1. undocumented
> 2. inconsistent with the credential chain for AWS which follows the environment → file → IAM role load order
> 
> Please check if this is intentional.

the load order is wrong , this is not intentional
the RD member will reconstruct and fix this bug
