### ISSUE TITLE
Dumpling snapshot failed 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#34529]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a table, insert some data
```
mysql> create database t;
Query OK, 0 rows affected (0.08 sec)
mysql> create table t.t1 (a int);
Query OK, 0 rows affected (0.08 sec)
mysql> insert into t.t1 values (1);
Query OK, 1 row affected (0.01 sec)
```
2. get current time
```
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2022-05-10 06:20:46 |
+---------------------+
1 row in set (0.00 sec)
```
3.  drop database
mysql> drop database t;
Query OK, 0 rows affected (0.20 sec)

4. Use dumpling to export the deleted database, specifying parameter --snapshot "2022-05-10 06:20:46" => dumpling failed with error "Unknown database 't' "
```
/dumpling  -h "src-tidb-tidb.fb-br-debug-p65cb" -P "4000" -u "root" --output "s3://tmp/ttt?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9000&force-path-style=true" --filetype "csv" --filesize "256M" --rows "200" --threads "20" -B t --snapshot "2022-05-10 06:20:46"
[2022/05/10 06:21:28.133 +00:00] [INFO] [conn.go:45] ["cannot execute query"] [retryTime=1] [sql="SHOW CREATE DATABASE `t`"] [args=null] [error="sql: SHOW CREATE DATABASE `t`, args: []: Error 1049: Unknown database 't'"]
```
Notes:
1. This issue is only seem in recent nightly build ( This case was passed in 05/04 CI )
2. After dumpling snapshot failed, I can actually see the database if I connect to tidb and set @@tidb_snapshot="2022-05-10 06:20:46";

```
mysql> set @@tidb_snapshot="2022-05-10 06:20:46";
Query OK, 0 rows affected (0.00 sec)
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| INFORMATION_SCHEMA |
| METRICS_SCHEMA     |
| PERFORMANCE_SCHEMA |
| mysql              |
| t                  |
+--------------------+
5 rows in set (0.00 sec)
```
### 2. What did you expect to see? (Required)
Dumpling snapshot should be successful.
### 3. What did you see instead (Required)
dumpling failed with error "Unknown database 't' "
```
/dumpling  -h "src-tidb-tidb.fb-br-debug-p65cb" -P "4000" -u "root" --output "s3://tmp/ttt?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9000&force-path-style=true" --filetype "csv" --filesize "256M" --rows "200" --threads "20" -B t --snapshot "2022-05-10 06:20:46"
[2022/05/10 06:21:28.133 +00:00] [INFO] [conn.go:45] ["cannot execute query"] [retryTime=1] [sql="SHOW CREATE DATABASE `t`"] [args=null] [error="sql: SHOW CREATE DATABASE `t`, args: []: Error 1049: Unknown database 't'"]
```

### 4. What is your TiDB version? (Required)
/ # /tidb-server -V
Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: 20ecaef36d747a9993fffaf04903e8f7c9dbf527
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-05-09 11:03:05
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by lichunzhu** [comment]
Using the same version of dumpling to export v6.0.0 TiDB is okay. However, using MySQL client to simulate this operation without problems

**Comment by zyguan** [comment]
Introduced by #34263 . `sessionVars.TxnCtx` gets initialized [here](https://github.com/pingcap/tidb/pull/34263/files?diff=split&w=0#diff-10dab83c04a99358d431906d37f48b92be97d50a2719d4ddf81c62d3b03a0aebR3151), it's 'temptable.AttachLocalTemporaryTableInfoSchema(p.Sctx, domain.GetDomain(p.Sctx).InfoSchema()) -> **domain.InfoSchema()**' now, rather than previous 'session.GetInfoSchema() -> **sessionVars.SnapshotInfoschema**'.

Dumpling will execute `SHOW TABLE STATUS FROM ...`, the show stmt triggers a [restricted sql](https://github.com/pingcap/tidb/blob/53f228af451e8b347d60e68a82a5bf9978692c16/executor/show.go#L535-L541) within the current session, as a result, `sessionVars.SnapshotInfoschema` is reset to nil [here](https://github.com/pingcap/tidb/blob/53f228af451e8b347d60e68a82a5bf9978692c16/session/session.go#L1739). After that, when we call `session.GetInfoSchema()`, `sessionVars.TxnCtx.InfoSchema` is returned instead of `sessionVars.SnapshotInfoschema`, thus `drop database` is visible after `SHOW TABLE STATUS FROM ...`. The schema version changed unexpectedly during transaction!

@cfzjywxk @lcwangchao PTAL

**Comment by zyguan** [comment]
The minimal reproducible steps:
```sql
/* test */ use test;
/* test */ drop table if exists t;
/* test */ do sleep(1);
/* test */ do @t := now();
/* test */ create table t (a int);
/* test */ show tables;

/* test */ set tidb_snapshot = @t;
/* test */ show tables; -- empty
/* test */ show table status from test;
/* test */ show tables; -- [t]

/* test */ set tidb_snapshot = @t;
/* test */ start transaction with consistent snapshot;
/* test */ show tables; -- empty
/* test */ show table status from test;
/* test */ show tables; -- [t]
/* test */ rollback;
```
