### ISSUE TITLE
v6.0.0 with default configs upgrade to nightly(v6.1.0), tidb_enable_auto_analyze default value is off

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#34877]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

install a v6.0.0 tidb cluster without doing any configuration
upgrade to nightly(v6.1.0)
check default value of system variable

### 2. What did you expect to see? (Required)
tidb_enable_auto_analyze=ON

### 3. What did you see instead (Required)
tidb_enable_auto_analyze=OFF

performance.run-auto-analyze default value in v6.0.0 is on， why when it convert to the system variable, the value is off？

### 4. What is your TiDB version? (Required)

Git Commit Hash: 388b3c79cc3a313aee59334ebe6fc7dc451769c3
Git Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time: 2022-05-22 15:03:09

**Comment by bb7133** [comment]
So https://github.com/pingcap/tidb/pull/34862 does not fix `run-auto-analyze` because it is a boolean with default as `TRUE`.

We need some other ways.

My proposal is we could enhance [the import process](https://github.com/pingcap/tidb/blob/0cf93b5f51a9fa510e7ccc6937051f42e07ed69b/session/bootstrap.go/#L1839-L1840) by:

Option1> expose [configPath](https://github.com/pingcap/tidb/blob/0cf93b5f51a9fa510e7ccc6937051f42e07ed69b/tidb-server/main.go/#L120) and parse it again, we will be able to judge if an item exists by checking the [MetadData](https://pkg.go.dev/github.com/BurntSushi/toml?utm_source=gopls#MetaData) of unmarshalled result:

```
// MetaData allows access to meta information about TOML data that may not
// be inferrable via reflection. In particular, whether a key has been defined
// and the TOML type of a key.
type MetaData struct {
	mapping map[string]interface{}
	types   map[string]tomlType
	keys    []Key
	decoded map[string]bool
	context Key // Used only during decoding.
}
```

Option2> Similar to 1, but we could encapsulate the codes into a structure in `main` package and expose it as a structure/function like:

```
func IsConfigDefinedInFile(configName string) bool { ... }
```

@morgo WDYT?

**Comment by morgo** [comment]
I agree this is a better fix. I originally tried to do something like this, but it was complicated. There is no functionality in TOML to decode to kv/pairs. It needs to know the type to decode it.

As a temporary fix, we can put `run-auto-analyze` (and other default values) back in `defaultConfig` so that `TRUE` is picked up though.

**Comment by qw4990** [comment]
Config items of `PreparedPlanCache` have this issue as well(see `upgradeToVer91()`)... 🤦 
Please don't forget to update them when fixing this issue 🤦  @morgo ... I think I can help you review these related PRs, and if you need any other help please let me know.

**Comment by morgo** [comment]
> Config items of `PreparedPlanCache` have this issue as well(see `upgradeToVer91()`)... 🤦 Please don't forget to update them when fixing this issue 🤦 @morgo ... I think I can help you review these related PRs, and if you need any other help please let me know.

@qw4990 Are you sure? I don't think they do, because the default values were left in the `defaultConf`.

**Comment by qw4990** [comment]
> > Config items of `PreparedPlanCache` have this issue as well(see `upgradeToVer91()`)... 🤦 Please don't forget to update them when fixing this issue 🤦 @morgo ... I think I can help you review these related PRs, and if you need any other help please let me know.
> 
> @qw4990 Are you sure? I don't think they do, because the default values were left in the `defaultConf`.

Seems I'm wrong... Since the default value of `prep.enable` was changed, I want to use `IsConfigDefinedInFile` to check whether it was set by the user in the config file explicitly like this:
```
if IsConfigDefinedInFile("prep.enable") { 
    importConfig("prep.enable", globalConfig.prep.enable) // use the value from config
} 
else {
    importConfig("prep.enable", new_defualt_prep_enable) // use the new value instead of `defaultConf`
} 
```
But on second thought, I should solve it by updating the default value of `prep.eanble` in `defaultConf` to the new value.
