### ISSUE TITLE
truncate table error，bug？

### ISSUE THREAD

**Issue by lddlww** [pingcap/tidb#35284]
## Bug Report

tiup scale-out pd（three new pd），then scale-in old pd （three old pd）

exec truncate table，throw error：
![image](https://user-images.githubusercontent.com/27006237/172977338-2fd6250f-420a-42b5-ba0e-99e90ce38b30.png)

### 1. Minimal reproduce step (Required)

tiup scale-out new pd，then scale-in old pd

exec truncate table

### 2. What did you expect to see? (Required)
exec success

### 3. What did you see instead (Required)
exec failed

### 4. What is your TiDB version? (Required)
5.3.0

**Comment by Defined2014** [comment]
I think it looks same as https://github.com/pingcap/tidb/issues/35268. 

cc @JmPotato

**Comment by JmPotato** [comment]
> I think it looks same as #35268.
> 
> cc @JmPotato

The deep reason is the same, but this bug seems to come from a different part of the code.

**Comment by JmPotato** [comment]
After reading the code, it seems that this problem is caused by "scale-in the old PD servers too early". TiDB sets its `AutoSyncInterval` config to 30s for the etcd client to update the member list periodically. If you scale in the old PD serves before the next updating. It will cause the TiDB server to never know the new scaled-out PD servers' URLs until rebooting. This problem could be prevented by transferring the PD leader to the new scaled-out PD server and waiting for at least 30s first.

**Comment by lddlww** [comment]
> This problem could be prevented by transferring the PD leader to the new scaled-out PD server

using tiup to scale in old pd nodes, it can auto transfer the pd leader to new pd node , is it right?

**Comment by lddlww** [comment]
oh, the mean you are that i have to wait at least 30s before transfer pd leader to new pd node？

**Comment by JmPotato** [comment]
> > This problem could be prevented by transferring the PD leader to the new scaled-out PD server
> 
> using tiup to scale in old pd nodes, it can auto transfer the pd leader to new pd node , is it right?

I am not sure about this, we better use `pd-ctl` to transfer the leader manually.

> oh, the mean you are that i have to wait at least 30s before transfer pd leader to new pd node？

No, I mean we should wait for at least 30s **after** the leader transfer.

**Comment by lddlww** [comment]
thank you very much
