### ISSUE TITLE
set @@session.tidb_enforce_mpp=1 when tiflash top, tidb-server throw errors

### ISSUE THREAD

**Issue by lddlww** [pingcap/tidb#36111]
## Bug Report
set @@session.tidb_enforce_mpp=1 when tiflash top, tidb-server throw errors

### 1. Minimal reproduce step (Required)
tiup cluster stop test -R tiflash
mysql> set @@session.tidb_enforce_mpp=1; select count(*) from tiflash_table;

### 2. What did you expect to see? (Required)
select success

### 3. What did you see instead (Required)
ERROR 9012 (HY000): TiFlash server timeout

### 4. What is your TiDB version? (Required)
5.3.0

**Comment by lddlww** [comment]
it result in all select block when set @@session.tidb_enforce_mpp=1;

**Comment by lddlww** [comment]
when i set global tidb_allow_mpp=off , it does nothing

**Comment by lddlww** [comment]
when is set @ssesion.tidb_enforce_mpp=0 ; but cbo select tiflash storage to get data which result in error also

**Comment by zanmato1984** [comment]
This is an expected behavior. As long as the plan is made to read from tiflash, and the only tiflash node is down, timeout happens.

There are 2 caveats in this case:
1. Planner will make plan regardless of the liveness of tiflash node, it only checks if there is available tiflash replica for that specific table;
2. If you create 2 tiflash nodes and 2 tiflash replicas, when 1 tiflash node down, the executor will make the read to the other living tiflash node.

Does above answer the question?

**Comment by lddlww** [comment]
yes，thanks；that's mean i have to guarantee tiflash robust

**Comment by zanmato1984** [comment]
Closing.
