### ISSUE TITLE
`read-only` for `lc_messages` breaks compatible with `phpmyadmin`

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#38231]
## Bug Report

see details from https://github.com/pingcap/tidb/pull/33708#issuecomment-1260738467

**Comment by morgo** [comment]
There are a few ways you could fix this:
1. Change it back to a noop
2. Protect it by [noop-functions](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_noop_functions-new-in-v40)
3. Instead of read-only, write a validation func so that it only errors when trying to set it to something other than en_US.
4. Same as (3) but instead of an error return a warning and refuse changes to other than en_US.

I don't love noops (they are confusing to debug), but I think (4) is a safe enough tradeoff for this variable.

@williamdes @kvtb what do you think?

**Comment by williamdes** [comment]
I would vote for `Change it back to a noop` so no apps should be broken by that behavior

**Comment by djshow832** [comment]
I agree with `Change it back to a noop`. Protecting it by noop-functions also needs the user to set `tidb_enable_noop_functions` to true. Considering the user upgrades TiDB, it breaks compatibility.

**Comment by Defined2014** [comment]
Agree with `Change it back to a noop`, so maybe we could revert https://github.com/pingcap/tidb/pull/33708
