### ISSUE TITLE
Why DDL state change requires waiting for 2 * lease.

### ISSUE THREAD

**Issue by UndefinedSy** [pingcap/tidb#38251]
## General Question

I'm learning about the online schema change implementation and I've found an  
interesting design point.  
As described in *Online, Asynchronous Schema Change in F1*, we should keep all   
servers in a compatible state. And each server should update its meta information   
after each lease.

My question is: why we wait for 2 leases in every state change? Since server will   
reject service if it can not update its meta after a lease time, I think waiting  for  
1 * lease is enough.

**Comment by ljluestc** [comment]
Fault Tolerance: In a distributed system like TiDB, there can be transient network issues, server delays, or other unexpected events that might cause a delay in updating meta information. Waiting for 2 leases provides a buffer to handle such temporary disruptions without immediately affecting the system's availability or consistency.

Consistency Across Servers: Keeping all servers in a compatible state is crucial for the system's health. If each server updated its meta information after just 1 lease, there could be cases where one server has already updated its meta while another server is yet to do so. Waiting for 2 leases ensures that most servers have a consistent view of the system's state before proceeding with the next state change.

Reducing the Impact of Clock Drift: Clock synchronization among servers can sometimes vary due to clock drift. Waiting for 2 leases accounts for potential variations in server clocks, ensuring that state transitions are executed more consistently across the cluster.

Preventing Rapid State Changes: If the system waits for only 1 lease, rapid state changes could occur if there are frequent transient issues. This could lead to unnecessary disruptions and increase the likelihood of inconsistent states.
