### ISSUE TITLE
Tiflash replica is not available when a tiflash node is down

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/tidb#38484]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. depoly a tidb cluster with 2 tiflash node
2. create a table t(id int);
3. let one of the tiflash down
4. alter table t set tiflash replica 1
5. select * from information_schema.TIFLASH_REPLICA;  The value of AVAILABLE if always 0，and tiflash can not be used for handing query.

### 2. What did you expect to see? (Required)

Because there are two tiflash nodes，tiflash should be available even one of them is down. 

### 3. What did you see instead (Required)

Tiflash replica of table t is always unavailable untile the down tiflash node is up again. 

### 4. What is your TiDB version? (Required)

master

**Comment by jiyfhust** [comment]
https://github.com/pingcap/tidb/blob/2b3b80906774a8d1fb0a07d834bbda1ebcbe3ffa/ddl/ddl_tiflash_api.go#L368

When a tiflash node is down，CollectTiFlashStatus return error, then it fails to get tiflash progress.

https://github.com/pingcap/tidb/blob/2b3b80906774a8d1fb0a07d834bbda1ebcbe3ffa/ddl/ddl_tiflash_api.go#L570

The tableInfo of table t can't be set available。

So:
1. Is it need to check tiflash node status before CollectTiFlashStatus?
2. If skip CollectTiFlashStatus from the down tiflash node
   * The available state can be set in the case
   * The progress of other table may be <1 when the down tiflash node have region replicas of the table

How to solve it properly?

**Comment by CalvinNeo** [comment]
The original design might be:
1. If `sync-status` is not available, it may be due to a TiFlash crash, or a temporarily network problem.
2. If TiFlash crashed, then this store will be down on PD.
3. If there is a network problem, then some regions is still stored in this TiFlash store, we just lose track of them. If we just don't count them, our stat info might be wrong, which can lead to a sharp decrease of TiFlash sync progress, or even affect the `Available` field in later TiDB versions.

**Comment by jiyfhust** [comment]
> 3\. stored

Yes.  Is there a proper way to solve it? When a tiflash is down, CollectTiFlashStatus  is always fail.

**Comment by jiyfhust** [comment]
@CalvinNeo 

Yes.  Is there a proper way to solve it? When a tiflash is down, CollectTiFlashStatus  is always fail.

**Comment by CalvinNeo** [comment]
If a tiflash is down and unrecoverable, I think maybe we need to firstly make it work again or just evict it from the cluster. /cc @hehechen

**Comment by hehechen** [comment]
If TiFlash crashed, I think we can assume that there are 0 peers on the down TiFlash. And after `max-store-down-time
`, PD will add peers at other TiFlash nodes, so it will become `available` finally.
But for network problem, I think we can't just simply assume that there are 0 peers on the down TiFlash, because this will cause the progress to keep changing when the network is unstable.

I think TiDB can get TiFlash stores state from PD, if `CollectTiFlashStatus` failed, check if the state of TiFlash store is `down`, and assume that there are 0 peers on the `down` TiFlash.

**Comment by jiyfhust** [comment]
how about this:
1. if tiflash is down or disconnected, just skip CollectTiFlashStatus of the tiflash，because we can not CollectTiFlashStatus successfully on a not normal tiflash node.
2. if the tiflash is up, then CollectTiFlashStatus on the node.  If it fails，log an error and assume that there are 0 peer on the tiflash, and continue to CollectTiFlashStatus on other tiflashs. 
3. when finish get the progress, compare it with the old value, only update it in the case the new value is greater than  the old one. this can avoid the progress to keep changing when the network is unstable.   But if all tiflash nodes are up, and CollectTiFlashStatus  success, always update the progress.

what do you think? @CalvinNeo @hehechen

**Comment by jiyfhust** [comment]
another questioin, can we set tiflash replica available as soon as possible?
If a table is set tiflash replica 3, when a replica is synced, then set it available.
we can judge if a replica is finished by this way:
1. get table regions count from pd as regionCount
2. calculate all region peers on tiflash, but calcaute as a map, key is regionId, val is region peer count, is len(map) == regionCount, then we assume all regions have at least one region peer on tiflash node.

**Comment by jiyfhust** [comment]
another questioin, can we set tiflash replica available as soon as possible?
If a table is set tiflash replica 3, when a replica is synced, then set it available.
we can judge if a replica is finished by this way:
1. get table regions count from pd as regionCount
2. calculate all region peers on tiflash, but calcaute as a map, key is regionId, val is region peer count, is len(map) == regionCount, then we assume all regions have at least one region peer on tiflash node.

**Comment by hehechen** [comment]
> another questioin, can we set tiflash replica available as soon as possible? If a table is set tiflash replica 3, when a replica is synced, then set it available. we can judge if a replica is finished by this way:
> 
> 1. get table regions count from pd as regionCount
> 2. calculate all region peers on tiflash, but calcaute as a map, key is regionId, val is region peer count, is len(map) == regionCount, then we assume all regions have at least one region peer on tiflash node.

Currently the optimizer will not avoid the TiFlash nodes that have not finished replicating, so we can't set the table `available` if **one** replica is synced.

**Comment by hehechen** [comment]
> how about this:
> 
> 1. if tiflash is down or disconnected, just skip CollectTiFlashStatus of the tiflash，because we can not CollectTiFlashStatus successfully on a not normal tiflash node.
> 2. if the tiflash is up, then CollectTiFlashStatus on the node.  If it fails，log an error and assume that there are 0 peer on the tiflash, and continue to CollectTiFlashStatus on other tiflashs.
> 3. when finish get the progress, compare it with the old value, only update it in the case the new value is greater than  the old one. this can avoid the progress to keep changing when the network is unstable.   But if all tiflash nodes are up, and CollectTiFlashStatus  success, always update the progress.
> 
> what do you think? @CalvinNeo @hehechen

I don't think that only update `progress` in the case the new value is greater than the old one is a good idea. Because `progress` may decrease when TiFlash write throughput can't keep up with TiKV.


> I think TiDB can get TiFlash stores state from PD, if CollectTiFlashStatus failed, check if the state of TiFlash store is Down, and assume that there are 0 peer on the Down TiFlash.

In other cases, for example, TiFlash store status is `UP` or `disconnected`, we can assume that there is a network problem, I think we can keep the existing logic unchanged, don't update `progress` and retry in the next ticker.

**Comment by CalvinNeo** [comment]
> 1. CollectTiFlashStatus

IMO, if there is only one TiFlash node, or one TiFlash replica, we'd better find out if the store is in a network jitter(which is assumed to be recovered in a short time), or crashed as quickly as possible. Since if the only node/replica is down, and we take a long time to discover, then queries may be blocked for quite a long time.

**Comment by CalvinNeo** [comment]
> If TiFlash crashed, I think we can assume that there are 0 peer on the down TiFlash. And after `max-store-down-time `, PD will add peers at other TiFlash nodes, so it will become `available` finally. But for network problem, I think we can't just simply assume that there are 0 peer on the down TiFlash, because this will cause the progress to keep changing when the network is unstable.
> 
> I think TiDB can get TiFlash stores state from PD, if `CollectTiFlashStatus` failed, check if the state of TiFlash store is `Down`, and assume that there are 0 peer on the `Down` TiFlash.

IMO, if there is only one TiFlash node, or one TiFlash replica, we'd better find out if the store is in a network jitter(which is assumed to be recovered in a short time), or crashed as quickly as possible. Since if the only node/replica is down, and we take a long time to discover, then queries may be blocked for quite a long time.
