### ISSUE TITLE
lighting  import is hang when single import single table with duplicate 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#39042]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

modify lightning import file to add duplicate line
use lightning import to target cluster

### 2. What did you expect to see? (Required)
ignore duplicate line, and import successfully
### 3. What did you see instead (Required)
import is hang
### 4. What is your TiDB version? (Required)

/ # ./tidb-lightning -V
Release Version: v6.4.0
Git Commit Hash: dbca4159ef871800ac8e364957572dcae736e647
Git Branch: heads/refs/tags/v6.4.0
Go Version: go1.19.2
UTC Build Time: 2022-11-09 10:38:32
Race Enabled: false
/ #

**Comment by seiya-annie** [comment]
[lightning-hang.log.gz](https://github.com/pingcap/tidb/files/9977251/lightning-hang.log.gz)
[tidb-lightning.toml.gz](https://github.com/pingcap/tidb/files/9977252/tidb-lightning.toml.gz)
[tidb.log.gz](https://github.com/pingcap/tidb/files/9977253/tidb.log.gz)
[tikv.log.gz](https://github.com/pingcap/tidb/files/9977254/tikv.log.gz)

**Comment by buchuitoudegou** [comment]
The root cause is supposed to be that:
![tFffgs5UFu](https://user-images.githubusercontent.com/25972139/201045889-37c97f3a-d839-4949-974e-a2c0107c55c3.jpg)

The TiKV store client is used as an etcd client when:
![87fece0b-2216-42c9-a6ac-8832ad738f83](https://user-images.githubusercontent.com/25972139/201046032-9085a4d8-39ca-4b15-a16d-af6dd8c267d2.jpeg)

Using this client to allocate globally unique incr id will cause dead loop:
![image](https://user-images.githubusercontent.com/25972139/201046273-52f9b415-ea00-4b56-9271-65f5a8619204.png)
