### ISSUE TITLE
br: v6.5 is twice slower than v6.1 when restoring ossinsight dataset

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#40025]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
    export AWS_ACCESS_KEY_ID=minioadmin AWS_SECRET_ACCESS_KEY=minioadmin
    tiup br:v6.5 restore db --db=gharchive_dev --pd "pd-peer.testbed-perftest-x5rpv:2379" \
        --storage "s3://perftest/ossinsight-2tiflash" \
        --s3.endpoint "http://172.16.6.59:9000" \
        --send-credentials-to-tikv=true \
		--check-requirements=false --checksum-concurrency 128
```

![image](https://user-images.githubusercontent.com/2316425/208351945-4684dae8-ba70-4a00-b9ea-63b278d156a0.png)

### 2. What did you expect to see? (Required)
v6.5 should not be slower than v6.1

### 3. What did you see instead (Required)
~2x slower

### 4. What is your TiDB version? (Required)

v6.5

**Comment by breezewish** [comment]
![203fc527-5ec4-4240-b0a1-2a4242604311](https://user-images.githubusercontent.com/1916485/208610151-7614e2cb-3eba-4850-aebc-a881aafcf1d1.jpeg)

According to the detailed metrics, actually TiFlash restores several times faster. The major reason of this issue is that in v6.1.1 BR exits early. At the moment when BR exited, TiFlash restore was not finished yet.

**Comment by dbsid** [comment]
In this case there is 2 TiFlash involved. It turns out that in v6.1.3, it's a false positive, although br return in 4300s, the TiFlash takes over 6 hours to complete the replicas. In v6.5, the TiFlash takes around 3 hours to complete the replicas. v6.5 is 56% faster than v6.1 actually.
