### ISSUE TITLE
Function des_encrypt, des_decrypt not supported

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#4055]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
select des_encrypt('hello');
select des_decrypt(NULL);
```

2. What did you expect to see?

```
des_encrypt('hello')
??2nV??}
des_decrypt(NULL)
NULL
```

3. What did you see instead?

```
ERROR 1305 (42000) at line 1: FUNCTION DES_ENCRYPT does not exist
ERROR 1305 (42000): FUNCTION DES_DECRYPT does not exist
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
DES_ENCRYPT and DES_DECRYPT are deprecated since 5.7.6.

**Comment by kennytm** [comment]
I'd like to dispute the priority of this issue. 

MySQL's `DES_ENCRYPT(plaintext, keystr)` function is actually a 3DES in CBC mode (`des-ede3-cbc`). It will compute `MD5(keystr)`, then use the first 24 bytes as the key and the last 8 bytes as the IV. A `0xff` will be prefixed to the encrypted result. 

Since the key and IV cannot be specified directly, it makes `DES_ENCRYPT` useless outside of MySQL. For instance we can't write a SQL version of Vitess's sharding hash function https://github.com/vitessio/vitess/blob/f0bf54c76ab1b21e66cf49ca5675a4b7a26ffa8e/go/vt/vtgate/vindexes/hash.go#L137 in MySQL unless someone can  find the preimage front the md5 of all zeroes.

**Comment by nullnotnil** [comment]
These functions were removed in MySQL 8.0 because they are no longer considered safe. If they are to be added, we should consider hiding them behind a flag.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
