### ISSUE TITLE
Cryptographic Padding Oracle

### ISSUE THREAD

**Issue by hihihuhu** [pingcap/tidb#40962]
## Enhancement

in https://github.com/pingcap/tidb/blob/master/util/encrypt/aes.go

The application's `AES_DECRYPT` implementation decrypts data in a manner that does not preclude queries being abused as a padding oracle, potentially allowing users to decrypt data stored in the system. Encryption is performed using unauthenticated AES in CBC mode with PKCS#7 padding and returns discernible padding errors to users:

[`encrypt.PKCS7Unpad`](https://github.com/pingcap/tidb/blob/master/util/encrypt/aes.go#L99) function returned a distinct difference when encountering invalid padding appended to a plaintext message. 

then [`encrypt.aesDecrypt`](https://github.com/pingcap/tidb/blob/master/util/encrypt/aes.go#L243) private function encounters an error while attempting to strip padding from the decrypted plaintext, it will propagate the error to the up-stack calling function.]

then [`encrypt.AESDecryptWithCBC`](https://github.com/pingcap/tidb/blob/master/util/encrypt/aes.go#L167) public function did not swallow or otherwise negate the padding error, instead propagating it to the up-stack calling function and potentially to the user initiating the database query.

For any ciphertext, if padding is correct, the application will successfully decrypt the ciphertext and continue execution. If padding is not correct, the decryption method will throw an exception. This results in the server leaking information about whether padding is correct or not. An attacker can abuse this weakness to decrypt data by modifying individual ciphertext bytes and checking whether the token decrypts successfully. If the token does not successfully decrypt, the guessed byte value was incorrect; and vice versa for a correct guess

**Comment by TopScrew** [comment]
I understand that there are several prerequisites for the exploitation of Padding Oracle:
1. The attacker has access to the ciphertext and the initialization vector corresponding to the ciphertextiv 
2. The attacker can frequently trigger the decryption process of the ciphertext and can catch the error exceptions

Analysis of several call points from AESDecryptWithCBC shows that the error has been handled by the caller during delivery and does not continue to spread to the user. Please provide the specific drawback call points so that we can quickly confirm the vulnerability.

**Comment by Calvin-Zou** [comment]
Location:

`tidb/util/encrypt/aes.go`

Description:
The application's `AES_DECRYPT` implementation decrypts data in a manner that does not preclude queries being abused as a padding oracle, potentially allowing users to decrypt data stored in the system. Encryption is performed using unauthenticated AES in CBC mode with PKCS#7 padding and returns discernible padding errors to users:

~~~golang
// PKCS7Unpad unpads data using PKCS7.
// See http://tools.ietf.org/html/rfc2315.
func PKCS7Unpad(data []byte, blockSize int) ([]byte, error) {
length := len(data)
if length == 0

{ return nil, errors.New("Invalid padding size") }
if length%blockSize != 0 { return nil, errors.New("Invalid padding size") }

pad := data[length-1]
padLen := int(pad)
if padLen > blockSize || padLen == 0

{ return nil, errors.New("Invalid padding size") }

// TODO: Fix timing attack here.
for _, v := range data[length-padLen : length-1] {
if v != pad

{ return nil, errors.New("Invalid padding") }

}
return data[:length-padLen], nil
}
~~~
[Listing - The `encrypt.PKCS7Unpad` function returned a distinct difference when encountering invalid padding appended to a plaintext message.]

It appeared to the testing team that the `encrypt.AESDecryptWithCBC` public function implemented the database's MySQL `AES_DECRYPT()` functionality, exposing a padding oracle to database users when this functionality was misused in SQL queries.

~~~golang
// aesDecrypt decrypts data using AES.
func aesDecrypt(cryptStr []byte, mode cipher.BlockMode) ([]byte, error) {
blockSize := mode.BlockSize()
if len(cryptStr)%blockSize != 0

{ return nil, errors.New("Corrupted data") }

data := make([]byte, len(cryptStr))
mode.CryptBlocks(data, cryptStr)
plain, err := PKCS7Unpad(data, blockSize)
if err != nil

{ return nil, err }

return plain, nil
}
~~~
[Listing - In the event that the `encrypt.aesDecrypt` private function encounters an error while attempting to strip padding from the decrypted plaintext, it will propagate the error to the up-stack calling function.]

~~~golang
// AESDecryptWithCBC decrypts data using AES with CBC mode.
func AESDecryptWithCBC(cryptStr, key []byte, iv []byte) ([]byte, error) {
cb, err := aes.NewCipher(key)
if err != nil

{ return nil, errors.Trace(err) }

mode := cipher.NewCBCDecrypter(cb, iv)
return aesDecrypt(cryptStr, mode)
}
~~~
[Listing - The `encrypt.AESDecryptWithCBC` public function did not swallow or otherwise negate the padding error, instead propagating it to the up-stack calling function and potentially to the user initiating the database query.]

For any ciphertext, if padding is correct, the application will successfully decrypt the ciphertext and continue execution. If padding is not correct, the decryption method will throw an exception. This results in the server leaking information about whether padding is correct or not. An attacker can abuse this weakness to decrypt data by modifying individual ciphertext bytes and checking whether the token decrypts successfully. If the token does not successfully decrypt, the guessed byte value was incorrect; and vice versa for a correct guess.

Impact:
An attacker can use the application as an oracle to decrypt encrypted payloads.

Reproduction steps:

NCC Recommendation:
Encryption should use an authenticated mode such as GCM.

If using AES in GCM mode is not feasible, ensure ciphertext is authenticated with an HMAC-SHA256 and verified using a function that compares authentication codes in constant-time. If ciphertext does not pass authentication, do not further process or attempt to decrypt the ciphertext.

**Comment by Calvin-Zou** [comment]
Added more data points from NCC.

**Comment by bb7133** [comment]
Hi @hihihuhu @Calvin-Zou , thanks for reporting this.

The usage of  [AESDecryptWithCBC](https://github.com/pingcap/tidb/blob/master/util/encrypt/aes.go#L167) is the built-in function [AES_DECRYPT()](https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_aes-decrypt) when [block_encryption_mode](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_block_encryption_mode) is set to `CBC`:

```
SET block_encryption_mode = 'aes-256-cbc';
```

So, if I were correct: when a potential attacker is able to use this vulnerability, it means that he/she has got the authentication for data access of the database already and the key has been leaked(a much more serious incident compared with this).

**Comment by bb7133** [comment]
And if you think this is vulnerable, you could try other modes by setting [block_encryption_mode](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_block_encryption_mode), the current support ones are ['ecb', 'cbc', 'ofb' and 'cfb'](https://github.com/pingcap/tidb/blob/568cbca3f97b8f642dcc5a53752dc563901a6c8a/expression/builtin_encryption.go#L90-L104).

> NCC Recommendation:
> Encryption should use an authenticated mode such as GCM.

We do have some other internal encryption modes like '[CTR](https://github.com/pingcap/tidb/pull/28200)' which is used by BR, but it is not exported to the end-users. If you're interested in 'GCM', IMO it can be adopted as well.

You suggestions are appreciated.

**Comment by hihihuhu** [comment]
thanks for the reply! we don't see a practical way to exploit this despite it may have issue such as timing attack, the concern is, in general, it would be better to use widely used library instead of implement in house because it is hard to get it right. but again, since we don't find a way to exploit it, please feel free to close it and improve later. thanks!

**Comment by dveeden** [comment]
@hihihuhu thanks for reporting this. Let's close this for now as suggested.
