### ISSUE TITLE
What's expected behavior for generated columns that are assigned with invalid values?

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#41665]
## General Question

I try the following statement in TiDB 8.0.32, in which a CREATE TABLE statement creates a table with an INT column c0 and a generated `BOOL` column c1 that is expected always be 255 (designed to make it overflow). The CREATE TABLE statement executes successfully without reporting any errors.
```SQL
CREATE TABLE t0(c0 INT, c1 BOOL AS (255) VIRTUAL);
```
I then try to insert some values into it by the following statement. The INSERT statement executes successfully with reporting three warnings.
```SQL
INSERT IGNORE INTO t0(c0) VALUES (0), (1), (2);
```
And the final table content is 
```SQL
+------+------+
| c0   | c1   |
+------+------+
|    0 |  127 |
|    1 |  127 |
|    2 |  127 |
+------+------+
```

I have three questions:
* Is the final table content expected?
* Is it possible to report errors when creating such tables?
* Is it possible to report errors when inserting such tables?

I think such tables should not be created. Hope for your replies.

**Comment by bb7133** [comment]
Hi Jason,

> I try the following statement in TiDB 8.0.32

We don't have TiDB 8.0.32, do you mean 'MySQL 8.0.32' or some other versions of TiDB?

> Is the final table content expected?

Yes, since TiDB aims to be compatible with MySQL, and if you try those SQLs in MySQL, the behaviors are the same.

**Comment by bb7133** [comment]
> Is it possible to report errors when creating such tables?
> Is it possible to report errors when inserting such tables?

It depends:

* For now, I didn't find a way to make TiDB/MySQL report an error: SQL mode([MySQL manual](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html) / [TiDB manual](https://docs.pingcap.com/tidb/stable/sql-mode/)) is a variable that usually controls the error/warning behavior when invalid values are encountered. But I found that for your case, SQL mode is not related.

* It is possible for TiDB to implement something new that controls it(for example, a system variable called `tidb_invalid_values_for_generated_column`). But it depends if this is important/useful for general usage. Also, usually when we introduce things that doesn't exist in MySQL, we need to think carefully because the data migrations between TiDB/MySQL are common for TiDB users.

**Comment by xiongjiwei** [comment]
From MySQL [doc](https://dev.mysql.com/doc/refman/8.0/en/insert.html):
> Data conversions that would trigger errors abort the statement if IGNORE is not specified. With IGNORE, invalid values are adjusted to the closest values and inserted; warnings are produced but the statement does not abort. You can determine with the [mysql_info()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-info.html) C API function how many rows were actually inserted into the table.

it is expected behavior

**Comment by sayJason** [comment]
> Hi Jason,
> 
> > I try the following statement in TiDB 8.0.32
> 
> We don't have TiDB 8.0.32, do you mean 'MySQL 8.0.32' or some other versions of TiDB?
> 
> > Is the final table content expected?
> 
> Yes, since TiDB aims to be compatible with MySQL, and if you try those SQLs in MySQL, the behaviors are the same.

Sorry, the tidb version is 5.7.25-TiDB-v6.6.0.

**Comment by sayJason** [comment]
Thanks for all your replies. I get the answer.
