### ISSUE TITLE
multi-column RANGE COLUMNS partitioning  prune looks strange

### ISSUE THREAD

**Issue by shiyuhang0** [pingcap/tidb#42216]
## Bug Report

The partition prune in multi-column RANGE COLUMNS looks strange. Don't known if it is a bug

### 1. Minimal reproduce step (Required)

DDL
```
CREATE TABLE tk (
  valid_until datetime,
  name varchar(255) CHARACTER SET ascii,
  notes text
)
PARTITION BY RANGE COLUMNS(name,valid_until)
(PARTITION `p2022-g` VALUES LESS THAN ('G','2023-01-01 00:00:00'),
 PARTITION `p2023-g` VALUES LESS THAN ('G','2024-01-01 00:00:00'),
 PARTITION `p2024-g` VALUES LESS THAN ('G','2025-01-01 00:00:00'),
 PARTITION `p2022-m` VALUES LESS THAN ('M','2023-01-01 00:00:00'),
 PARTITION `p2023-m` VALUES LESS THAN ('M','2024-01-01 00:00:00'),
 PARTITION `p2024-m` VALUES LESS THAN ('M','2025-01-01 00:00:00'),
 PARTITION `p2022-s` VALUES LESS THAN ('S','2023-01-01 00:00:00'),
 PARTITION `p2023-s` VALUES LESS THAN ('S','2024-01-01 00:00:00'),
 PARTITION `p2024-s` VALUES LESS THAN ('S','2025-01-01 00:00:00'),
 PARTITION `p2022-` VALUES LESS THAN (0x7f,'2023-01-01 00:00:00'),
 PARTITION `p2023-` VALUES LESS THAN (0x7f,'2024-01-01 00:00:00'),
 PARTITION `p2024-` VALUES LESS THAN (0x7f,'2025-01-01 00:00:00'))
```

Query

```
select * from tk where name = 'G'
```
<img width="681" alt="image" src="https://user-images.githubusercontent.com/52435083/224983545-b9715fb9-5b0b-4cbf-b5eb-84aaa599853b.png">

why is p2023-g selected?  I think this query's range is  ('G','')， why can the p2023-g contain this range?

### 4. What is your TiDB version? (Required)
v6.5.0

**Comment by mjonss** [comment]
> Why p2023-g and p2024-g are not selected? explain select * from tk where name = 'A'
Because the LESS THAN sorts first on the first column and then on the second column.

**Comment by aytrack** [comment]
Here is the doc of mysql describe from mysql. For range columns partition 

> Placement of rows into partitions is determined by comparing the tuple from a row to be inserted that matches the column list in the COLUMNS clause with the tuples used in the VALUES LESS THAN clauses to define partitions of the table. Because we are comparing tuples (that is, lists or sets of values) rather than scalar values, the semantics of VALUES LESS THAN as used with RANGE COLUMNS partitions differs somewhat from the case with simple RANGE partitions. In RANGE partitioning, a row generating an expression value that is equal to a limiting value in a VALUES LESS THAN is never placed in the corresponding partition; however, when using RANGE COLUMNS partitioning, it is sometimes possible for a row whose partitioning column list's first element is equal in value to the that of the first element in a VALUES LESS THAN value list to be placed in the corresponding partition.

**Comment by mjonss** [comment]
As I would explain it, it simply means that the expression needs to be LESS THAN the whole tuple.
Take the partitioning example above and check which partitions can have values `where name = 'G'` (and note that valid_until is not restricted):
p2022-g has rows with name = 'G' and valid_until < 2023-01-01 00:00:00 (or where name < 'G'), like ('A', '2029-01-02') or ('G', '2022-12-31')
p2023-g has rows with name = 'G' and valid_until < 2024-01-01 00:00:00 (it can only have name = 'G') like ('G', '2023-06-08')
p2024-g has rows with name = 'G' and valid_until < 2025-01-01 00:00:00 (it can only have name = 'G') like ('G', '2024-08-09')
p2022-m has rows with name = 'M' and valid_until < 2023-01-01 00:00:00 (or where name < 'M')

So as you can see, the example would give a bad distribution, and will not work as explained, since dropping partition `p2022-m` would remove all values where name < 'M' and > 'G' regardless of valid_until.

 Also if the order would been `valid_until,name` the same issue would occur, like if the table definition was:
```
PARTITION BY RANGE COLUMNS(valid_until,name)
(PARTITION `p2022-g` VALUES LESS THAN ('2023-01-01 00:00:00','G'),
 PARTITION `p2022-m` VALUES LESS THAN ('2023-01-01 00:00:00','M'),
 PARTITION `p2023-g` VALUES LESS THAN ('2024-01-01 00:00:00','G'),
 PARTITION `p2024-g` VALUES LESS THAN ('2025-01-01 00:00:00','G'),
...
```
Then only values with `valid_until` = '2023-01-01 00:00:00' and name >= 'G' and name < 'M' would fit into p2022-m partition.

Notice that if we want to be able to truncate or drop data where a specific column is less, then that column needs to be the first listed columns in the RANGE COLUMNS list. Or every combination of the previous listed columns must be defined in the list of partitions, like if it was an tinyint (0-255) each of the values needs to have its own set of partitions like:
```
PARTITION `p0-2022` VALUES LESS THAN (0,'2023-01-01'),
PARTITION `p0-2023` VALUES LESS THAN (0,'2024-01-01'),
...
PARTITION `p1-2022` VALUES LESS THAN (1,'2023-01-01'),
PARTITION `p1-2023` VALUES LESS THAN (1,'2024-01-01'),
...
PARTITION `p255-2022` VALUES LESS THAN (255,'2023-01-01'),
PARTITION `p255-2023` VALUES LESS THAN (255,'2024-01-01'),
PARTITION `p255-Max` VALUES LESS THAN (255,MAXVALUE),
```

So we should probably remove the example, or improve the explanation.

**Comment by shiyuhang0** [comment]
1. As you described:
```
p2022-m has rows with name = 'M' and valid_until < 2023-01-01 00:00:00 (or where name < 'M')
```
I think 
```
p2022-s has rows with name = 'S' and valid_until < 2023-01-01 00:00:00 (or where name < 'S')
```
For this SQL `select * from tk where name = 'G'.` Why p2022-m  is selected but p2022-s is not?

2. If the where condition does not contain valid_until. what value will be the tuple (name, valid_until) when we need to compare with the partition expression? for example, is the ('G',empty) <  ('G','2024-01-01 00:00:00') - p2023-g

**Comment by mjonss** [comment]
1. It first sorts/compares column by column, so if there is a LESS THAN already at first column it will not check the other columns (i.e. 'G' < 'M' so p2022-m is as far as it needs to check). It will only check the next column if the previous column is '=', like 'G' = 'G' (which is why p2022-g, p2023-g, p2024-g is also included).

2. if the list of columns in the RANGE COLUMNS list is c1, c2, ... cN and only c1..cM (where M<N) is given, then it must assume that c(M+1) can be any value, so c(M+1) must be compared as it is the maximum value the column can have.

So if we have partitions defined as:
```
CREATE TABLE tExample
(a tinyint unsigned,
 b tinyint unsigned)
PARTITION BY RANGE COLUMNS (a,b)
(PARTITION p0 VALUES LESS THAN (10,255),
 PARTITION p1 VALUES LESS THAN (11,MAXVALUE),
 PARTITION p2 VALUES LESS THAN (MAXVALUE,1))
```

Then `where a = 10` will include p0 and p1, since (10,255) is in p1. But `where a = 11` only needs p1 (TiDB does include p2, which is reported as https://github.com/pingcap/tidb/issues/42273 ).

A technical detail is that MAXVALUE compares higher than any other value, so once one of the columns in a partition definition is set as MAXVALUE, the following columns does not matter, Which is why there cannot be any partition after p2, since they will all compare the same.

**Comment by shiyuhang0** [comment]
I do not have any questions now! Thank you!

**Comment by shiyuhang0** [comment]
I think this issue can be closed for it does not point to any bug.
