### ISSUE TITLE
ddl: compared with v6.6.0, v7.0.0 has 10% - 13% performance regression

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#42456]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a TiDB cluster and restore the data of ossinsight workload
2. add index `alter table github_events add index test_idx(repo_id,type,action,closed_at,actor_login)`

### 2. What did you expect to see? (Required)
No performance regression
### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/84501897/226772934-c4c00d04-15a8-460a-a68a-5f67fc242d8e.png)

### 4. What is your TiDB version? (Required)

v7.0.0

**Comment by lance6716** [comment]
The root cause is

after https://github.com/pingcap/tidb/pull/40692 , I moved "generating job" logic into the single thread producer, and in one round after all job is generated we send them to consumer

https://github.com/pingcap/tidb/blob/4e30a64a669d54a099b0f5f456ad651c48541c06/br/pkg/lightning/backend/local/local.go#L1398-L1426

however, in old code generating job is scattered in multiple worker that runs concurrently

The CPU profile can locate this problem. in timestamp 1680237360
![image](https://user-images.githubusercontent.com/1689766/229057050-a3eac955-6029-4fbd-a3ce-2220115da4b9.png)

3 minutes later:
![image](https://user-images.githubusercontent.com/1689766/229056847-cbfbc7af-dce4-462c-854a-ae5aa53be391.png)
