### ISSUE TITLE
The performance of Hzbank drop 9% - 13% with Plan Cache Miss OPS increases

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#43320]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster and set `set global tidb_enable_top_sql=on;set global tidb_prepared_plan_cache_size=1000;` 
2. run the hzbank workload 

### 2. What did you expect to see? (Required)
No performance regression
![image](https://user-images.githubusercontent.com/84501897/233824152-41fae0d3-6fe2-49e4-8460-cc2fa1a95d3b.png)

### 3. What did you see instead (Required)
1. Plan Cache Miss OPS increases from 1.1k to 25k
3. The avg Compile duration increases from 82us to 209us

![image](https://user-images.githubusercontent.com/84501897/233824185-0599a911-6443-43ba-affe-703cfbb93353.png)

### 4. What is your TiDB version? (Required)

good commit https://github.com/pingcap/tidb/commit/9a02bbcddc95735dc51342356386a2a1b7b2da5e
bad commit https://github.com/pingcap/tidb/commit/cd33faf209b67582a548a8bd916570fd44297bbd

**Comment by qw4990** [comment]
![b6a88aad-bc9e-47f9-ba9b-d1a533fd4e1b](https://user-images.githubusercontent.com/7499936/233837147-e009407e-3927-4de5-aa5c-d4caf516d331.jpeg)

**Comment by qw4990** [comment]
The root cause is that we updated the variable name used to control the plan cache size:
![c503aa1e-da76-4be9-af6c-a8c25717c20b](https://user-images.githubusercontent.com/7499936/234203562-f405c0d6-f85e-4083-9348-aafabecdb44e.jpeg)

So we have to use `set global tidb_session_plan_cache_size=1000` instead of `set global tidb_prepared_plan_cache_size = 1000` to set the cache size before executing this benchmark.
