### ISSUE TITLE
Fix integration compilation failure of client-go

### ISSUE THREAD

**Issue by MyonKeminta** [pingcap/tidb#44591]
## Enhancement

* https://github.com/tikv/client-go/pull/830 updated pd's version of client-go which addes the GetMinTS interface
* TiDB references an older version of PD so the mock PD client in unistore doesn't have GetMinTS
* The integration tests in client-go repo requires unistore in TiDB repo
* The integration tests in https://github.com/tikv/client-go/pull/830 can't pass compilation since it references an older version of TiDB whose unistore doesn't implement GetMinTS which is required by the new version of PD that's referenced by client-go at the same time
* https://github.com/tikv/client-go/pull/830 merged with the compilation error

What's the purpose of our CI tests?

To fix it:

1. Update PD dependency of TiDB repo, also update client-go since it has another interface change.
2. Update TiDB dependency of client-go repo

Who'd like to do the time wasting job?

**Comment by MyonKeminta** [comment]
Fixed by https://github.com/pingcap/tidb/pull/44593 and https://github.com/tikv/client-go/pull/835 after wasting at least 3 different persons' time.

**Comment by CabinfeverB** [comment]
Sorry.
Because the cse needs to add the GetMinTS interface, but it is not used in tidb master, so it is not modified in client-go and tidb master. However, I want to upgrade pd client in tidb master, I must first modify it in client-go and then modify tidb. But because https://github.com/pingcap/tidb/pull/44339 hasn't been merged, led to the compatibility test have not been repaired. In the future, I will first mention a PR in tidb to fix it separately.
