### ISSUE TITLE
Can't find a proper physical plan for this query when rollup

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#45274]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tpcds 10 scale with tiflash replica
query 14 raises error for `ERROR 1815 (HY000) at line 2: Internal : Can't find a proper physical plan for this query`
### 4. What is your TiDB version? (Required)

Release Version: v7.3.0-alpha
Edition: Community
Git Commit Hash: 2b3abcdc74832eed9a71c6a025898cdc13d2e7d2
Git Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time: 2023-07-08 11:11:32
GoVersion: go1.20.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by AilinKid** [comment]
this is make sense, as show the modified sql without rollup keyword, let's see its plan like:
![image](https://github.com/pingcap/tidb/assets/15825830/bcf44c29-774b-446d-9dbb-763b0a78c690)
we can see the hash-join 978 has already been kept in the tidb execution layer, because one of it's children is about cte reading which is only current supported by TiDB yet, leading upward plan can only be RootTaskType, while Expand operation can only be planned at tiflash node, so it's contradiction.

so it's expected now.
