### ISSUE TITLE
Too many issues in connecting a cluster (prisma)

### ISSUE THREAD

**Issue by ashutosh887** [pingcap/tidb#45628]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
when trying to connect prisma to a TiDB Cluster

### 2. What did you expect to see? (Required)
I wanted to connect my application to the cluster but insted it ditn't get connected and I got a lot of bugs and breaking errors

### 3. What did you see instead (Required)
Error: Schema engine error:
Connections using insecure transport are prohibited. See https://docs.pingcap.com/tidbcloud/secure-connections-to-serverless-tier-clusters

My datasource in schema.prisma looked something like this
datasource db {
  provider = "mysql" 
  url      = "mysql://username.root:password@gateway.xyz-central-1.prod.aws.tidbcloud.com:4000/test?sslminversion=TLSv1.2&sslrejectunauthorized=false"
}

### 4. What is your TiDB version? (Required)
I don't know

**Comment by ashutosh887** [comment]
@gregwebs @foobar @weekface @tirsen 
I request you to have a look at this on urgent basis

**Comment by djshow832** [comment]
The client must enable TLS with the serverless cluster. Are you sure it's enabled?

**Comment by ashutosh887** [comment]
Yes I have added
I would like to propose a section docs for `connecting with prisma` as I could not find it!

cc: @jebter @djshow832 @sunxiaoguang

**Comment by bb7133** [comment]
@ashutosh887 Could we close this issue?

**Comment by zhangyangyu** [comment]
@ashutosh887 hello, I think the problem is your ssl properties in the URL is wrong. You can use `sslaccept=strict` in the URL to connect to TiDB Serverless from [the doc](https://www.prisma.io/docs/concepts/database-connectors/mysql).

This repo is for the open source TiDB kernel so it's not the right place to ask for questions about TiDB Cloud. The doc repo is https://github.com/pingcap/docs.

And we are currently optimizing connection doc for TiDB Serverless. I guarantee the situation will be improved soon.

**Comment by ashutosh887** [comment]
Sure Thanks @zhangyangyu @bb7133
