### ISSUE TITLE
add maxvalue list partition error info changed

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#45763]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t;
create table t (a int, b varchar(10)) partition by list (a) (
partition p0 values in (-100),
partition p3 values in (0)
);
alter table t add partition (
partition p1 values in (-101)
);
alter table t add partition (
partition p4 values in (-1)
);
alter table t add partition (
partition p5 values in (maxvalue)
);
```

### 2. What did you expect to see? (Required)
```sql
[16:49:30]MySQL root:test> alter table t add partition ( partition p5 values in (maxvalue) );
(1064, "Cannot use MAXVALUE as value in VALUES IN near 'maxvalue) )' at line 1")
```
### 3. What did you see instead (Required)
introduced by #41537
```sql
[16:50:07]TiDB root:test> alter table t add partition ( partition p5 values in (maxvalue) );
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 62 near "maxvalue) )" ')
```
### 4. What is your TiDB version? (Required)
v7.3.0(4220dfa819525ba214396666), master(1bf82bbaaa71a86a5b3245e7b902e92deba78ce)

**Comment by mjonss** [comment]
This happens because I changed the parser, so 'VALUES IN' cannot have MAXVALUE, instead of parsing it and then issue an error. It is only the error message that has changed, the error code is still the same.

It also still points to the same part of the query string `'maxvalue)\n)' which should be helpful enough, so I will close this as will not fix.
