### ISSUE TITLE
before tidb.runStmt return error, need to rollback the current transaction

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#463]
In tidb.runStmt, if encount some error in any exec func, you need to rollback the current transaction, otherwise, the txn.UnionStore.Dirty will contain some discard data..

https://github.com/pingcap/tidb/blob/d7c3cc47916db41552b88fb55f2cf0156be4bea1/tidb.go#L171

**Comment by shenli** [comment]
Thanks for your report.
If encounter any error when running stmt, we will call txn.Rollback, and it will close UnionStore.
https://github.com/pingcap/tidb/blob/master/store/localstore/txn.go#L252
So may be not an issue.

**Comment by winkyao** [comment]
Example:

```
[wink@centos test_sqls]$ cat tmp.sql
CREATE DATABASE IF NOT EXISTS `test`;
USE test;
DROP TABLE IF EXISTS `nosharding_test`;
CREATE TABLE `nosharding_test` (
      `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
      `test1` int(5) UNIQUE,
      PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

[wink@centos test_sqls]$ mysql -h 127.0.0.1 -P 4000 -u root -D test < tmp.sql
[wink@centos test_sqls]$ mysql -h 127.0.0.1 -P 4000 -u root -D test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10003
Server version: 5.5.31-TiDB-1.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> desc nosharding_test;
+-------+------------------+------+------+---------+----------------+
| Field | Type             | Null | Key  | Default | Extra          |
+-------+------------------+------+------+---------+----------------+
| id    | int(11) UNSIGNED | NO   | PRI  | NULL    | auto_increment |
| test1 | int(5)           | YES  | UNI  | NULL    |                |
+-------+------------------+------+------+---------+----------------+
2 rows in set (0.00 sec)

mysql> insert into nosharding_test(id, test1) values(1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into nosharding_test(id, test1) values(2, 1);
ERROR 1105 (HY000): Error: key already exist
mysql> insert into nosharding_test(id, test1) values(2, 2);
ERROR 1105 (HY000): Error: key already exist
mysql> select * from nosharding_test;
+----+-------+
| id | test1 |
+----+-------+
|  1 |     1 |
+----+-------+
1 row in set (0.01 sec)

mysql> insert into nosharding_test(id, test1) values(2, 2);
ERROR 1105 (HY000): Error: key already exist
mysql>
```

**Comment by ngaut** [comment]
Good catch! @winkyao

**Comment by ngaut** [comment]
Do you think you can fix it ? @winkyao

**Comment by winkyao** [comment]
@ngaut yes. I'll fix it later.

**Comment by shenli** [comment]
@winkyao @disksing 
I think this issue is already fixed in the latest master. @disksing checks duplicate before modify unistore. So we do not need to worry about dirty data.

The following is my test log:
➜  interpreter git:(disksing/interpreter-commit-error) ✗ ./interpreter 
Welcome to the TiDB.
Version:
Git Commit Hash: 88047a0efce72c9c51d553338ead0e1f40171e0b
UTC Build Time:  2015-11-28 05:05:22

tidb> USE test;
Query OK, 0 row affected (0.00 sec)
tidb> DROP TABLE IF EXISTS `nosharding_test`;
Query OK, 0 row affected (0.00 sec)
tidb> CREATE TABLE `nosharding_test` (
   ->       `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
   ->       `test1` int(5) UNIQUE,
   ->       PRIMARY KEY (`id`)
   -> )ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 row affected (0.01 sec)
tidb> desc nosharding_test;
+-------+------------------+------+-----+---------+----------------+
| Field | Type             | Null | Key | Default | Extra          |
+-------+------------------+------+-----+---------+----------------+
| id    | int(11) UNSIGNED | NO   | PRI | NULL    | auto_increment |
| test1 | int(5)           | YES  | UNI | NULL    |                |
+-------+------------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)
tidb> insert into nosharding_test(id, test1) values(1, 1);
Query OK, 1 row affected (0.00 sec)
tidb> insert into nosharding_test(id, test1) values(2, 1);
Query OK, 1 row affected (0.00 sec)
2015/11/28 13:07:55 main.go:240: [error] /Users/shenli/workspace/go/src/github.com/pingcap/tidb/kv/iter.go:27: Error: key already exist
/Users/shenli/workspace/go/src/github.com/pingcap/tidb/kv/union_store.go:168: 
/Users/shenli/workspace/go/src/github.com/pingcap/tidb/store/localstore/txn.go:196: 
/Users/shenli/workspace/go/src/github.com/pingcap/tidb/store/localstore/txn.go:247: 
/Users/shenli/workspace/go/src/github.com/pingcap/tidb/session.go:169: 
/Users/shenli/workspace/go/src/github.com/pingcap/tidb/tidb.go:231: 
/Users/shenli/workspace/go/src/github.com/pingcap/tidb/session.go:393: 
/Users/shenli/workspace/go/src/github.com/pingcap/tidb/driver.go:253:  
tidb> insert into nosharding_test(id, test1) values(2, 2);
Query OK, 1 row affected (0.00 sec)
tidb> select * from nosharding_test;
+----+-------+
| id | test1 |
+----+-------+
| 1  | 1     |
| 2  | 2     |
+----+-------+
2 rows in set (0.00 sec)
tidb>
