### ISSUE TITLE
crc32Checksum is inconsistency after import into finished which was injected ddl owner network partition

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#48649]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run import into
2、 inject ddl owner network partition

case config：
      tag: "ha-test-import-into"
      cases:
        - name: "ha_tidb(ddl-owner)_to_all_network_partition"
          warmUpTime: 1m
          faultType: network_partition
          selector: "tidb(ddl-owner)_to_all"
          period: "@every 5m"
          faultDuration: 3m
          faultTotalRunTime: 30m
          importInto:
            - db: "importtest"
              schema: "CREATE TABLE `user_data1` (
                `uid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                `data` mediumblob NOT NULL,
                `update_data` blob NOT NULL,
                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `update_time` datetime DEFAULT NULL,
                PRIMARY KEY (`uid`) /*T![clustered_index] CLUSTERED */,
                KEY `k_1` (`update_time`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5850196;"
              cmd: "import into user_data1 from 's3://qe-testing/brie/lightning-mhy-100G-csv/sysbench.user_data1.000001*.csv?access-key=AKLTwRZn26DMQ1KAOqZBwb2N\u0026secret-access-key=OGpscvlaU8gJCOIMZsCDJJZvhVWt8urXjQRBuQ6u\u0026endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com\u0026force-path-style=false\u0026region=Beijing\u0026provider=ks' WITH DETACHED,thread=8,skip_rows=1"
              timeout: 120m
              crc32Checksum: 3582177512

### 2. What did you expect to see? (Required)
crc32Checksum is consistency

### 3. What did you see instead (Required)
crc32Checksum is inconsistency after import into finished which was injected ddl owner network partition

operatorLogs:
[2023-11-15 22:51:28] ###### start import into
import into user_data1 from 's3://qe-testing/brie/lightning-mhy-100G-csv/sysbench.user_data1.000001*.csv?access-key=AKLTwRZn26DMQ1KAOqZBwb2N&secret-access-key=OGpscvlaU8gJCOIMZsCDJJZvhVWt8urXjQRBuQ6u&endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com&force-path-style=false&region=Beijing&provider=ks' WITH DETACHED,thread=8,skip_rows=1
[2023-11-15 22:51:28] ###### wait for import job to finish
[2023-11-15 23:13:08] ###### import job finished
select id, step, status from mysql.tidb_import_jobs where start_time >= '2023-11-15 22:51:28'
jobId: 60005, step: , status: finished
import done, it takes: 21m40.447941577s

[2023/11/15 23:23:01.405 +08:00] [INFO] [client.go:826] ["Get table checksum"] [database=importtest] [table=user_data1] ["table crc32 checksum"=244735121]
ImportIntoConsistencyCheck failed: user_data1 expected cCrc32Checksum is 3582177512, the actual is 244735121

### 4. What is your TiDB version? (Required)
git hash：151b5b1df9d595bf0b568ff82f2ea2e13ae3eddb

**Comment by D3Hunter** [comment]
one subtask is skipped(run but finished immediately), here is the timeline

|  | Tidb 0 | Tidb 1 |
| --- | --- | --- |
| 22:51:29 | dispatcher generate encode&sort subtask |  |
| 22:51:30 | Got 60035 and run | Got 60036 and run |
| 22:53:25 |  | Dispatcher start |
| 22:53:32 |  | Move 60035 to me Task state is set to pending |
| 22:54:11 | Dispatcher exit |  |
| 22:55:38 | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel  There're many pd errors during this time range |  |
| 23:01:21 | Dispatcher start |  |
| 23:01:30 | Move 60035 and 60036 to me  |  |
| 23:01:30 | Run 60035 |  |
| 23:01:31 |  | Dispatcher exit |
| 23:03:28 |  | 60036 finished (we didn't check exec-id when updated, and set state directly. |
| 23:03:42 |  | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel  |
| 23:09:17 |  | Dispatcher start |
| 23:09:38 |  | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel  Still logging [scheduler.go:108] ["scheduler canceled"]，and many [ERROR] [pd.go:236] ["updateTS error"] [txnScope=global] [error="context canceled"] errors in between GetFirstSubtaskInStates didn't use ctx of scheduler, so it cannot see it being cancelled. The scheduler run loop must be blocked on GetFirstSubtaskInStates. |
| 23:09:40 |  | Move 60035 to me |
| 23:09:40 |  | Run 60035 |
| 23:09:41 |  | Finish 60035 Since scheduler runCtx is cancelled, workers in WorkerPool all exist, and AsyncOperator.Wait don't return error. So the subtask just finished without error. |
| 23:09:41 |  | dispatcher skip merge-sort Start generate write&ingest  subtask |
| 23:11:39 | Dispatcher exit |  |
| 23:12:36 | Finish 60035 This place didn't check state of subtask, so it will update too. |  |
