### ISSUE TITLE
mv index doesn't be selected

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#50220]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

/** Q15 **/
SELECT
  `item_primary_key`,
  `created_time`
FROM
  items
WHERE
  (
    ? member of (`feed_profile_ids`)
    AND (`items`.`merchant_item_set_id` = ?)
    AND (`items`.`point_of_sale_country` = ?)
  )
LIMIT
  200

### 2. What did you expect to see? (Required)
index:feed_profile_ids  can be selected
### 3. What did you see instead (Required)
[ce62f7c5a2850490a6232b147a0f6ffdd0178e1c2be8c5dc465dfb8c4044c0aa.txt](https://github.com/pingcap/tidb/files/13868406/ce62f7c5a2850490a6232b147a0f6ffdd0178e1c2be8c5dc465dfb8c4044c0aa.txt)

### 4. What is your TiDB version? (Required)

v7.5.0

**Comment by seiya-annie** [comment]
7.5.0 upgrade to 7.6.0, but mv index can't selected in Q15 and Q8

**Comment by time-and-fate** [comment]
This issue involves two problems:
1. In v7.5.0, tidb still doesn't support using different indexes to build index merge path for mv index. This is improved in v7.6.0 by https://github.com/pingcap/tidb/pull/47671.
2. In v7.6.0, sometimes tidb doesn't use all usable indexes to build index merge path. After more testing and investigation, for some cases, there are some inaccurate estimation and costing. For this case, it's expected. Because choose more indexes doesn't necessarily mean better performance and might cause worse performance, and choosing the most selective indexes is more important.
