### ISSUE TITLE
100T global sort on GCS is slow due to checking old BR object hierarchy

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#50533]
At the beginning of the ingest step
![image](https://github.com/pingcap/tidb/assets/1689766/91fccc89-bef3-4b06-a1f6-cfc29cd33973)
![image](https://github.com/pingcap/tidb/assets/1689766/b0baccfa-4131-4288-a402-9849e4da107d)

Don't know how long it will last

**Comment by kennytm** [comment]
This check was created to fix pingcap/br#675 for BR v4.0.8. Given our compatibility strategy I think #50534 can be cherry-picked to v6.x.x the earliest?

We've got an issue where the customer using **TiCDC v7.5** with GCS as redo log storage got a DeadlineExceeded error because this check takes over 5 minutes in total.

**Comment by lance6716** [comment]
@kennytm I have created the cherry-pick PRs. Please notify the cherry-pick triage role of TiCDC to approve them.
