### ISSUE TITLE
ADMIN CHECKSUM TABLE does not block GC

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#50920]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> admin checksum table `test`.`item`;
ERROR 9006 (HY000): GC life time is shorter than transaction duration, transaction starts at 2024-02-02 03:00:18.594 +0000 UTC, GC safe point is 2024-02-02 03:03:47.245 +0000 UTC
```

a workaround is put this statement into BEGIN COMMIT

**Comment by jiyfhust** [comment]
The reason is `ChecksumTableExec` do the time-cost work in [Open](https://github.com/pingcap/tidb/blob/1438892b9fed5efc6fae8df8d44c239368ced262/pkg/executor/checksum.go#L46).
Here [open is called](https://github.com/pingcap/tidb/blob/1438892b9fed5efc6fae8df8d44c239368ced262/pkg/executor/adapter.go#L521)
Here [ProcessInfo is set](https://github.com/pingcap/tidb/blob/1438892b9fed5efc6fae8df8d44c239368ced262/pkg/executor/adapter.go#L541) 

So the `gc work` can't see the `StartTs` of `CheckSum`.
