### ISSUE TITLE
v7.5.0 TopN didn't push down to tiflash automacically

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#51417]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
PlanReplayer will upload later
The v6.5 plan replayer

[replayer_6zWOqxGRVsofNStOfVDHkg==_1706863530448743995.zip](https://github.com/pingcap/tidb/files/14445930/replayer_6zWOqxGRVsofNStOfVDHkg._1706863530448743995.zip)

The v7.5 plan replayer

[replayer_rAcz2i2c3RTvr2JAtRLMZg==_1706858656592619125.zip](https://github.com/pingcap/tidb/files/14445937/replayer_rAcz2i2c3RTvr2JAtRLMZg._1706858656592619125.zip)

### 2. What did you expect to see? (Required)
TopN should be pushed down to tiflash for both v7.5.0 and v6.5.4
### 3. What did you see instead (Required)
![636b52e2-c304-4732-ae9a-bfe6a9671909](https://github.com/pingcap/tidb/assets/7493273/aa345133-3dcd-43b5-890d-51c3540f4a2d)

### 4. What is your TiDB version? (Required)
v7.5.0

**Comment by guo-shaoge** [comment]
@elsa0520 please help upload the plan replayer, and remember not to expose client information.

**Comment by elsa0520** [comment]
In the 7.5 version,  the estrows of "HashAgg_37" is 17xxx which is smaller than the topn limit 20000. So if we push this topn down to the tiflash, it will not filter any rows in tiflash moreover one more topn operator overhead.
This is the directly reaon why optimizer doesn't push down topn to tiflash .
![image](https://github.com/pingcap/tidb/assets/111482174/c3d087e7-30d6-417a-b272-88f325f58949)

**Comment by elsa0520** [comment]
Further analysis revealed that the statistic of 6.5 is not consistent with the statistic of 7.5.
v6.5 stats.json
![dd2c6349-7f1d-43f4-b191-699f862e3c2b](https://github.com/pingcap/tidb/assets/111482174/43a9f7b8-1329-4e7a-8413-3100d50b3d58)
v7.4 stats.json
![587e7caa-ccb6-42aa-973f-9d318123994f](https://github.com/pingcap/tidb/assets/111482174/b0ae38f9-6905-4dbb-8530-4e3a2b9479d9)

This is why the selection and HashAgg estrows are difference.

When we load the v6.5 stats in the v7.5 cluster, the v7.5 can also push down the topn to tiflash.
**So the reason why 7.5 was not pushed down topn is because the stats changed.**

**Comment by elsa0520** [comment]
## Why the stats is difference but the data is same ?

Sampling has randomness. So stats from samples, like histograms and topn would likely be different even on the same data. But row count, null count and ndv should not be different.
