### ISSUE TITLE
when to use Partitioned Table in TiDB

### ISSUE THREAD

**Issue by pengbiaobeyond** [pingcap/tidb#51628]
分区表在达到什么数据量才会使用，有没有啥数据的数字指标

**Comment by dveeden** [comment]
@mjonss

**Comment by mjonss** [comment]
> (from google translate) When the amount of data reaches a partition table, it will be used. Is there any numerical indicator of the data?

Partitioning is not needed to be used due to size, since TiDB will automatically split tables and indexes into [Regions](https://docs.pingcap.com/tidb/stable/tidb-storage#region) around 100MB, so one can say that TiDB is automatically partitioning your data by range (but it also splits indexes by range separately, while if using table partitioning also the indexes would be per partition as well). I prefer to say that TiDB 'distributes' the data, others call this transparent sharding :)

In MySQL, if a table is very large, so the primary key, or other unique indexes does not fit into memory, partitioning can be used to make the indexes smaller, so the hottest part fits in memory and thus is not slowed down due to disk fetches during index lookups, which is needed also for writes. But this is not applicable to TiDB.

There are a few use cases for [table partitioning](https://docs.pingcap.com/tidb/stable/partitioned-table) in TiDB:
- `ALTER TABLE t DROP PARTITION p` => Deleting data as a DDL atomically, very efficient, similar to DROP TABLE. Instead of doing it as a big delete or batched deletes, which has much higher overhead due to transaction handling.
- Data management, like [EXCHANGE PARTITION](https://docs.pingcap.com/tidb/stable/partitioned-table#partition-management) for quickly importing data that is already prepared in a table, or for archiving a whole partition.
- Partition Pruning => Only read the matching partitions, if the partitioning columns is part of the WHERE expression. Note that an INDEX is usually more performant than using partitioning, except when TiFlash is used for the query, since TiFlash is not using any indexes (the optimizer would use TiKV and an index there if it is considered to be cheaper/faster). So for any type of scans, Partition Pruning is beneficial, but maybe an index could be better.
- Hot spots => if you know your data and hot spots are an issue, then one can use table partitioning for spreading out the hot spots. Note, maybe [SHARD_ROW_ID_BITS](https://docs.pingcap.com/tidb/stable/shard-row-id-bits) is also an alternative, or changing the primary key (especially if it is composite, then rearranging the order may help).

Some references for table partitioning in MySQL (valid to some degree also for TiDB): https://mysql.rjweb.org/doc.php/partitionmaint

Current implementation in both MySQL and TiDB uses 'Local indexes', meaning all other indexes than the clustered primary key index is also partitioned the same way as the table, which results in one secondary key lookup per each matching partition (after partition pruning). So queries that does not use the partitioning columns will need to search every partition. Meaning secondary index lookups in that case will be slower the more partitions a table have, since it needs to do an index lookup for each partition. TiDB is working on an experimental implementation of Global Index, where a [unique] secondary index will not be partitioned, but stored as a whole for the full table. That also will remove the limitation of 'every unique index, including the PK, must include every partitioning column'.
