### ISSUE TITLE
*: pull/49161 caused performance regression

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#51956]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`make bench-daily TO=/path/to/file.json`
https://github.com/pingcap/tidb/blob/master/Makefile#L299

### 2. What did you expect to see? (Required)
No performance regression
### 3. What did you see instead (Required)
https://github.com/pingcap/tidb/pull/49161 caused regression in TiDB go-bench BenchmarkExplainTableLookup (26%) and BenchmarkExplainStringIndexScan (18%)
![image](https://github.com/pingcap/tidb/assets/84501897/6dd7e1a9-4bf2-49e7-8e77-6311025ed82e)
![image](https://github.com/pingcap/tidb/assets/84501897/d08b2210-3bca-4e5a-bb43-db60d63797e5)

### 4. What is your TiDB version? (Required)

pr https://github.com/pingcap/tidb/pull/49161

**Comment by mjonss** [comment]
The reason for this is that EXPLAIN now also calls the build the target plan, to get the correct pruning information.

See
https://github.com/pingcap/tidb/blob/93b96e9c8f6dc7ea109d611c8159130d0483784a/pkg/executor/builder.go#L1215-L1217

This is to conform to the higher level of design, where the partitioning pruning should be done in the executor building phase, to allow the plan cache to reuse the same execution plan, even if some parameters change, like changing the matching partitions.

@Yui-Song can this performance regression in EXPLAIN be accepted, with the above explanation?
I.e. the refactoring/fix for table partitioning to conform to the higher level Optimizer design and to support Plan Cache.

**Comment by mjonss** [comment]
I verified the regression, by this simple patch against current master, 93b96e9c8f6dc7ea109d611c8159130d0483784a, and it does increase the time and allocated bytes for both benchmarks:
```diff
diff --git a/pkg/executor/builder.go b/pkg/executor/builder.go
index aa43633b1c..424d4ed7ea 100644
--- a/pkg/executor/builder.go
+++ b/pkg/executor/builder.go
@@ -1211,10 +1211,10 @@ func (b *executorBuilder) buildExplain(v *plannercore.Explain) exec.Executor {
                if b.ctx.GetSessionVars().StmtCtx.RuntimeStatsColl == nil {
                        b.ctx.GetSessionVars().StmtCtx.RuntimeStatsColl = execdetails.NewRuntimeStatsColl(nil)
                }
+               explainExec.analyzeExec = b.build(v.TargetPlan)
        }
        // Needs to build the target plan, even if not executing it
        // to get partition pruning.
-       explainExec.analyzeExec = b.build(v.TargetPlan)
        return explainExec
 }
```

**Comment by mjonss** [comment]
To give more context about the change and the impact of `EXPLAIN` performance.

The [change above](https://github.com/pingcap/tidb/issues/51956#issuecomment-2009441578) is needed, since #49161 moved the partitioning pruning from creation of the `[Batch]PointGetPlan`, to the building of the `[Batch]PointGetExec`. So it can reuse the cached plan and update the pruned partitions when building the `exec.Executor`, including updating the pruned partitions in the cached plan, so it can be presented through `EXPLAIN`. This matches the design and flow of the TiDB planner and execution, and how the plan cache works.

So to be able to support plan cache for partitioned tables, the EXPLAIN also needs to build the `exec.Executor` from the cached plan (which will also update the pruning information in the cached plan), so the pruning information can be reflected when EXPLAINing a query.

@bb7133 Is this performance regression for EXPLAIN acceptable, given we now gain performance through the plan cache also for partitioned tables?

Can we close close this issue?

**Comment by bb7133** [comment]
> @bb7133 Is this performance regression for EXPLAIN acceptable, given we now gain performance through the plan cache also for partitioned tables?

@mjonss @Yui-Song Yes, the performance of EXPLAIN is quite acceptable, and Mattias has described the root cause with a reasonable explanation. I don't think EXPLAIN matters to any real-world workloads.

So I think we could close this issue with 'won't fix' label.

**Comment by Yui-Song** [comment]
> > @bb7133 Is this performance regression for EXPLAIN acceptable, given we now gain performance through the plan cache also for partitioned tables?
> 
> @mjonss @Yui-Song Yes, the performance of EXPLAIN is quite acceptable, and Mattias has described the root cause with a reasonable explanation. I don't think EXPLAIN matters to any real-world workloads.
> 
> So I think we could close this issue with 'won't fix' label.

LGTM
