### ISSUE TITLE
TiDB hangs when adding some constraints with JSON_SCHEMA_VALID() function

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#54273]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
SET GLOBAL tidb_enable_check_constraint=ON;
CREATE TABLE t1 (id INT AUTO_INCREMENT PRIMARY KEY);
INSERT INTO t1 VALUES (1), (2);
ALTER TABLE t1 ADD COLUMN jcol1 JSON;
ALTER TABLE t1 ADD COLUMN jcol2 JSON;
ALTER TABLE t1 ADD CONSTRAINT CHECK (json_schema_valid('{
                    "type": "object",
                    "properties": {
                      "id": {
                      "type": "integer"
                      },
                      "name": {
                      "type": "string"
                      },
                      "price": {
                      "type": "number",
                      "minimum": 0,
                      "exclusiveMinimum": true
                      }
                    },
                    "required": ["id","name","price"]}',`jcol1`));
```

### 2. What did you expect to see? (Required)
`ALTER TABLE t1 ADD CONSTRAINT ...` run successfully.

### 3. What did you see instead (Required)
This DDL failed with ~500 retries shown in the following logs:
```
[2024/06/26 22:19:06.037 -07:00] [WARN] [ddl_worker.go:1156] ["run DDL job error"] [worker="worker 22, tp general"] [category=ddl] [jobID=111] [conn=2097156] [error="error unmarshaling properties from json: error unmarshaling exclusiveMinimum from json: json: cannot unmarshal bool into Go value of type jsonschema.ExclusiveMinimum"]
[2024/06/26 22:19:06.039 -07:00] [INFO] [ddl_worker.go:1005] ["run DDL job failed, sleeps a while then retries it."] [worker="worker 22, tp general"] [category=ddl] [jobID=111] [conn=2097156] [waitTime=1s] [error="error unmarshaling properties from json: error unmarshaling exclusiveMinimum from json: json: cannot unmarshal bool into Go value of type jsonschema.ExclusiveMinimum"]
```

### 4. What is your TiDB version? (Required)
Server version: 8.0.11-TiDB-v8.2.0-alpha-318-g1870d5f098

**Comment by dveeden** [comment]
What happens here is that `JSON_SCHEMA_VALID()` is expecting a number for `exclusiveMinimum`, but a boolean is supplied. This causes `error unmarshaling properties from json: error unmarshaling exclusiveMinimum from json: json: cannot unmarshal bool into Go value of type jsonschema.ExclusiveMinimum`. This is because Oracle MySQL is using an older version of the standard as already explained in #54207 and https://bugs.mysql.com/bug.php?id=106454.

However because `errorIsRetryable()` is returing `true` for this error this is retried many times before giving up and returning an error.

This could be because:
- `errorIsRetryable()` needing to be updated for this
- The error from `JSON_SCHEMA_VALID()` not being one that `errorIsRetryable()` is expecting.

Quick hack to fix/demonstrate this:

```patch
diff --git a/pkg/ddl/index.go b/pkg/ddl/index.go
index d66b258024..e15e3df1b3 100644
--- a/pkg/ddl/index.go
+++ b/pkg/ddl/index.go
@@ -1007,6 +1007,9 @@ func errorIsRetryable(err error, job *model.Job) bool {
                _, ok := dbterror.ReorgRetryableErrCodes[sqlErr.Code]
                return ok
        }
+       if strings.Contains(err.Error(), "error unmarshaling") {
+               return false
+       }
        // For the unknown errors, we should retry.
        return true
 }
```
