### ISSUE TITLE
The Connection Count panel in the Grafana dashboard is inaccurate.

### ISSUE THREAD

**Issue by finalkira000** [pingcap/tidb#54428]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
<img width="992" alt="image" src="https://github.com/pingcap/tidb/assets/13897489/243b01d5-8f5b-48ac-b524-e346bcfdca73">

### 2. What did you expect to see? (Required)
Accurately reflect the number of connections.

### 3. What did you see instead (Required)
bug
### 4. What is your TiDB version? (Required)
7.5.1，7.5.2

**Comment by djshow832** [comment]
https://github.com/pingcap/tidb/issues/51889

**Comment by mayjiang0203** [comment]
One CT hit a similar issue at https://asktug.com/t/topic/1028444.

**Comment by dbakit** [comment]
- SQL 统计
<img width="1259" alt="image" src="https://github.com/pingcap/tidb/assets/11706450/cac1f080-3ca0-406c-aa7d-1a4a6daa3473">
- prometheus 数据
![image](https://github.com/pingcap/tidb/assets/11706450/32f63820-c1cd-424f-a5eb-898655bd8cf6)

对比下来，感觉是 default 这个 RESOURCE_GROUP 的数据有异常，最明显的是245结尾那个 tidb-server 节点，default 的总连接数竟然是个负数

**Comment by YangKeao** [comment]
Oops, I may have found the issue: if the connection is closed before handshaking successfully, it will decrease the connection count for 1. Because when the connection is closed, the connection count is always decreased, but it'll increase only after successful handshake.

I'm not sure whether it's actually the issue you are facing now, but I'll try to fix it.
