### ISSUE TITLE
Do not disconnect if drop resource groups

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#54453]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run workload like sysbench

2. drop the resource group which is used by sysbench

```
mysql> ALTER USER 'user1' RESOURCE GROUP default;
Query OK, 0 rows affected (0.06 sec)

mysql> select * from information_schema.resource_groups;
+---------+------------+----------+-----------+-------------+------------+
| NAME    | RU_PER_SEC | PRIORITY | BURSTABLE | QUERY_LIMIT | BACKGROUND |
+---------+------------+----------+-----------+-------------+------------+
| default | UNLIMITED  | MEDIUM   | YES       | NULL        | NULL       |
| rg1     | 100000000  | HIGH     | NO        | NULL        | NULL       |
+---------+------------+----------+-----------+-------------+------------+
2 rows in set (0.06 sec)

mysql> DROP resource group rg1;
Query OK, 0 rows affected (0.56 sec)
```

### 2. What did you expect to see? (Required)

sysbench no disconnect

### 3. What did you see instead (Required)

![image](https://github.com/pingcap/tidb/assets/6428910/54f2e783-35f8-44cb-b952-ffe075f13da2)

**Comment by nolouch** [comment]
PM: we can let the old connect use the `default` group in this situation.

**Comment by lhy1024** [comment]
@JmPotato, could you please help reopen this issue and take a look? I reproduced the remaining case locally on an unmodified TiUP Playground running TiDB v8.5.7. The key condition is that the existing connection remains idle until the tombstone resource-group controller is cleaned up.

I do not have permission to reopen this issue myself.

## Confirmed local reproduction

Environment:

```text
tiup playground v8.5.7 --db 1 --pd 1 --kv 1 --tiflash 0 --without-monitor
SELECT VERSION(): 8.0.11-TiDB-v8.5.7
tidb_enable_resource_control: ON
```

Initial setup as `root`:

```sql
CREATE DATABASE gtoc8677;
CREATE TABLE gtoc8677.person1 (id INT PRIMARY KEY);
INSERT INTO gtoc8677.person1 VALUES (1), (2);

CREATE RESOURCE GROUP rg1 RU_PER_SEC = 1000;
CREATE USER 'usr1'@'%' IDENTIFIED BY 'testpass' RESOURCE GROUP rg1;
GRANT SELECT ON gtoc8677.* TO 'usr1'@'%';
```

Open session A as `usr1` and keep this physical connection open:

```sql
SELECT CONNECTION_ID(), COUNT(1) FROM gtoc8677.person1;
```

Result:

```text
CONNECTION_ID(): 339738632
COUNT(1): 2
```

From session B as `root`:

```sql
ALTER USER 'usr1'@'%' RESOURCE GROUP default;
DROP RESOURCE GROUP rg1;
```

At this point, `mysql.user` records `default`, but the existing session still records `rg1`:

```text
mysql.user.User_attributes.resource_group: default
INFORMATION_SCHEMA.PROCESSLIST.RESOURCE_GROUP: rg1
```

An immediate table query in session A still succeeds. The TiDB log confirms that the deleted group has been replaced by a tombstone controller backed by the default group:

```text
[controller.go:534] ["[resource group controller] default resource group controller cost created for tombstone"] [name=rg1]
```

Now leave session A idle until the next resource-group cleanup tick. The default cleanup interval is five minutes, so this takes at most five minutes. After `resource_manager_client_resource_group_status{name="rg1",resource_group="rg1"}` disappears from the TiDB metrics, run the following in the same session A:

```sql
SELECT COUNT(1) FROM gtoc8677.person1;
SELECT VERSION();
SELECT COUNT(1) FROM gtoc8677.person1;
```

Actual result:

```text
ERROR 8249 (HY000): Unknown resource group 'rg1'
8.0.11-TiDB-v8.5.7
ERROR 8249 (HY000): Unknown resource group 'rg1'
```

The connection remains alive. `SELECT VERSION()` succeeds because it does not access TiKV, while both table queries enter the resource-control request path and fail.

Observed local timeline:

```text
20:23:44  rg1 controller created
20:24:08  rg1 replaced by a tombstone controller after DROP RESOURCE GROUP
20:24:13  immediate table queries still succeeded
~20:27:55 tombstone controller removed by the cleanup tick
20:28:33  the same physical connection returned ERROR 8249 for table queries
```

`BEGIN` is not required. I tested both autocommit and an explicit transaction. Both work before cleanup and fail after the tombstone controller is removed.

## Verification that the original fix is present

TiDB v8.5.7 pins the PD client in [`go.mod`](https://github.com/pingcap/tidb/blob/v8.5.7/go.mod#L123) to:

```text
github.com/tikv/pd/client v0.0.0-20260609141937-b01426f6b08b
```

The pinned PD commit `b01426f6b08b` is a descendant of both original fix merge commits:

- tikv/pd#8387: `0c7dc0bb5cf78fa77d9fa5d1f119714617a41f6b`
- tikv/pd#8402: `5ec6af4030195f9e69d786193085c4326a4baeeb`

The TiDB v8.5.7 tag commit `202b7f47286a1109b5c957401d34c9358d130ae0` is also a descendant of the pingcap/tidb#54621 merge commit `0e5e9ee8b45eab7b2e42b0415fd2d8ff08ee7d38`.

This is therefore an incomplete-fix case, not a missing backport.

## Confirmed remaining path

The local result matches the following code path in the PD client pinned by v8.5.7:

1. The delete event creates a default-backed tombstone controller for `rg1` in [`tombstoneGroupCostController`](https://github.com/tikv/pd/blob/b01426f6b08b/client/resource_group/controller/controller.go#L501-L535). Requests continue to work while that controller exists.
2. [`cleanUpResourceGroup`](https://github.com/tikv/pd/blob/b01426f6b08b/client/resource_group/controller/controller.go#L538-L550) deletes an idle tombstone controller on a cleanup tick. The default interval is five minutes.
3. The existing TiDB session still carries `rg1`. On its next table query, [`tryGetResourceGroupController`](https://github.com/tikv/pd/blob/b01426f6b08b/client/resource_group/controller/controller.go#L461-L482) misses the local controller, queries the provider for the already deleted group, and returns `NewResourceGroupNotExistErr("rg1")`. This path does not fall back to `default`.
4. TiDB maps that error to `ERROR 8249 (HY000): Unknown resource group 'rg1'`.

The expected behavior from this issue should continue after tombstone cleanup: an existing session retaining a deleted resource-group name should use `default` instead of failing.

Could you please help confirm the intended lifetime/fallback behavior and extend the regression test to cover an idle existing connection after tombstone cleanup? The existing `fastCleanup` failpoint in the PD client should make this case practical to test without waiting five minutes.

The support case reports the same symptom on v8.5.6. No fixed version has been confirmed yet.
