### ISSUE TITLE
query is very slow when keep order is true

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#54969]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://github.com/pingcap/tidb/blob/0abf3ae75a83edc4d7124c607130826536595f25/pkg/store/copr/coprocessor.go#L222-L256

This code is intended to make memory usage more efficient. The basic idea is when keep order is true, there is no need to start too many cop workers to receive data, because we want the data to return by order. 

However, if selection pushdown occurs, it may require reading many rows to get the desired data. In that case, keeping the concurrency level too low can significantly slow down performance.

### 4. What is your TiDB version? (Required)
master

**Comment by guo-shaoge** [comment]
introduced by https://github.com/pingcap/tidb/pull/35975

**Comment by tiancaiamao** [comment]
Maybe we can simply relax the restraction of concurrency when the cop request goes to tiflash.
Because in the tiflash scanerio, the tidb memory usage is not the top concern.


Other changes need more expirements, like here you mentioned:

> However, if selection pushdown occurs, it may require reading many rows to get the desired data. In that case, keeping the concurrency level too low can significantly slow down performance.

If the selection pushdown filter a lot data, the cop response packet is small enough, then increase concurrency would not increase the memory usage ... but it's more difficult to predicate how large the return packet would be.

**Comment by winoros** [comment]
More than 2 oncalls are related to this problem. 
Just change the severity to ensure we will not forget to bring it to the later minor releases.
