### ISSUE TITLE
Tidb and tikv can't start.

### ISSUE THREAD

**Issue by haoyougen** [pingcap/tidb#5681]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
 I changed the pd server from 2 servers to 3 new servers. 
Then a new cluster id generated, and tikv can't connect to the new cluster. 
tidb also have the connection problem. 
[session.go:1113: [fatal] check bootstrapped err [tikv:9001]PD server timeout[try again later]]
tidb version: 1.0.6

**Comment by haoyougen** [comment]
The tikv error msg is 
[[ERROR] cluster ID mismatch: local_id 6501639174036732112 remote_id 6512386590412789559. you are trying to connect to another cluster, please reconnect to the correct PD]

**Comment by zimulala** [comment]
PTAL @disksing

**Comment by haoyougen** [comment]
got the solution ,

**Comment by disksing** [comment]
Hi @haoyougen , as PD stores some of the most critical data of a tidb cluster, you should not just drop the pd-servers and create some new pd-servers to replace them. In order to migrate a 2 node pd-server cluster to 3 nodes, you will need to start a new pd-server to join the old cluster. Please refer our document for more details: https://github.com/pingcap/docs/blob/eb24e29479981ecc69036114b71d437944576814/op-guide/horizontal-scale.md#pd

**Comment by Freyayan** [comment]
这种情况下能通过修改pd id来解决问题吗？

**Comment by disksing** [comment]
@Freyayan , you cannot just modify pd' id, please refer the link above.
