### ISSUE TITLE
JDBC DatabaseMetaData.getTables table name case sensitivity issue

### ISSUE THREAD

**Issue by SonixLegend** [pingcap/tidb#6628]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I used Activiti workflow on my project, and I have run it via MySQL. Now I have migrated it to TiDB.
PS: the global variable lower_case_table_names = 1

2. What did you expect to see?
I wanna it run successfully on TiDB as on MySQL.

3. What did you see instead?
But when Activiti startup, it will check tables exsits. It use DatabaseMetaData.getTables to check tables with upper case table name. It can get resultset record on MySQL, but TiDB can't match the name.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.0-rc.4-182-g7f2b3bd Git Commit Hash: 7f2b3bd8999f1ce99528260d239b4d1da64c3303 Git Branch: master UTC Build Time: 2018-05-11 02:51:14 GoVersion: go version go1.10.2 linux/amd64 Race Enabled: false TiKV Min Version: 2.0.0-rc.4.1

**Comment by jackysp** [comment]
Thanks for your feedback! PTAL @winkyao

**Comment by SonixLegend** [comment]
@winkyao OK, but I have tried changing the value to 2, it still can't work for me, I got the same error messsage.

**Comment by XuHuaiyu** [comment]
@SonixLegend hi, what's the return result of `select @@lower_case_table_names ` in MySQL?

**Comment by SonixLegend** [comment]
@XuHuaiyu The result is 1, because I set it.

**Comment by XuHuaiyu** [comment]
@SonixLegend Does MySQL works well with `set @@lower_case_table_names = 2`?

**Comment by SonixLegend** [comment]
@XuHuaiyu No, I change the mysql variable to 2, it's the names of all tables have upper case errors on MySQL. But tidb didn't have the errors via same variable value 2, just the jdbc api has the error. I think I couldn't understand the tidb case rule. >_<
PS: I used mariadb jdbc driver.

**Comment by lysu** [comment]
@SonixLegend Hello~plz help us execute this cmds and take a look for result

- connect to tidb
- `show full tables from [your db name] like 'act_%'`
- `show full tables from [your db name] like 'ACT_%'`
-  add break point at [databaseMetaData.getTables](https://github.com/Activiti/Activiti/blob/126e89911d49c6ec0ab3f222baeea2a256e24c0d/activiti-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSession.java#L1173), and watch `tableName`, is upper or lower case?

**Comment by SonixLegend** [comment]
@lysu I mean if I set lower_case_table_names with 2 on MySQL, there are no exist table errors on any sqls with upper case table name, because the table names have been lower case in the database schema. And when I set the same variable on TiDB, it's work well even if lower case table names in the database.

**Comment by SonixLegend** [comment]
> show full tables from test like 'act_%'

'act_ge_bytearray', 'BASE TABLE'
'act_ge_property', 'BASE TABLE'
'act_hi_actinst', 'BASE TABLE'
'act_hi_attachment', 'BASE TABLE'
'act_hi_comment', 'BASE TABLE'
'act_hi_detail', 'BASE TABLE'
'act_hi_identitylink', 'BASE TABLE'
'act_hi_procinst', 'BASE TABLE'
'act_hi_taskinst', 'BASE TABLE'
'act_hi_varinst', 'BASE TABLE'
'act_id_group', 'BASE TABLE'
'act_id_info', 'BASE TABLE'
'act_id_membership', 'BASE TABLE'
'act_id_user', 'BASE TABLE'
'act_re_deployment', 'BASE TABLE'
'act_re_model', 'BASE TABLE'
'act_re_procdef', 'BASE TABLE'
'act_ru_event_subscr', 'BASE TABLE'
'act_ru_execution', 'BASE TABLE'
'act_ru_identitylink', 'BASE TABLE'
'act_ru_job', 'BASE TABLE'
'act_ru_task', 'BASE TABLE'
'act_ru_variable', 'BASE TABLE'

> show full tables from test like 'ACT_%'

0 row return

> add break point at databaseMetaData.getTables, and try a debug execution to watch tableName, is upper or lower case?

If I use upper case, it's no row from resultset. But I use lower case table name, it has one row result from resultset.

**Comment by lysu** [comment]
@SonixLegend

## why and what happen

> if I set lower_case_table_names with 2 on MySQL, there are no exist table errors on any sqls with upper case table name, because the table names have been lower case in the database schema

Maybe mysql doesn't set `lower_case_table_names=2` success as u think(u can try `select @@lower_case_table_names;` will see 0?). It seems [mysql code](https://github.com/mysql/mysql-server/blob/8.0/sql/mysqld.cc#L4078) execute in linux will set 0 when u give 2, so u got `no exist table errors`

> And when I set the same variable on TiDB, it's work well even if lower case table names in the database.

tidb force use `2`, and table name comparisons are not case sensitive, e.g. `select * from ABC` will get data in `abc` table.

> But when Activiti startup, it will check tables exsits. It use DatabaseMetaData.getTables to check tables with upper case table name

`DatabaseMetaData.getTables` will send `show full tables from [dbname] like '[tablename]' ` to mysql, and Activiti framework will use uppser-case tablename.

`like xxx` is a string selection operation, and differ to table lookup logic, so `collation` will take mainly affact instead of `lower_case_table_names`

In MySQL, u maybe use case insensitive collation like `utf8_general_ci`(as I guess), so mysql will select table names with case insensitive.

In TiDB,  we force use case sensitive collation utf8_bin, so tidb will select table name with case sensitive.

So, TiDB use upper-case will not get no result when real table name is lower case.

## Workaround
For shortly, we have no plan to support `lower_case_table_names=1` and `utf8_general_ci`(but maybe in future). and I know modify Activiti framework source code is not very suitable for u.

Maybe rename Activiti's table name to upper case in TiDB is easiest way for current, then both `select from table` and `show  talenames like` will work well.

**Comment by SonixLegend** [comment]
@lysu OK, you have explained the reason and the solution. Thanks for your help. I just closed the check switch, not change table names. ^_^
