### ISSUE TITLE
machine_benchmark iops check failed

### ISSUE THREAD

**Issue by maoluanjuan** [pingcap/tidb#6641]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
ansible-playbook bootstrap.yml
2. What did you expect to see?
 All goes wel

3. What did you see instead?
 "msg": "run command on server: cd /usr/local/system/tidb/deploy && LANG='en_US.UTF-8' ./fio -ioengine=libaio -bs=32k -direct=1 -thread -rw=randread -size=10G -filename=fio_randread_test.txt -name='PingCAP' -iodepth=4 -runtime=60 | awk -F, '/iops/{print $3}' | awk -F'=' '{print $2}', and the result is 5058."
}
but if i use bs=4k instead bs=32k, the iops is 20000, so what should i do?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
ansible 2.5.3
  config file = /usr/local/system/tidb/tidb-ansible/ansible.cfg
  configured module search path = [u'/home/tidb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

centos 7.4
ssd 800G

**Comment by jackysp** [comment]
Thanks for your feedback, @maoluanjuan ! PTAL @LinuxGit

**Comment by LinuxGit** [comment]
When you deploy TiDB using Ansible, you need to use SSD disks for the data directory of TiKV and PD nodes, we recommend NVMe SSD. It seems that your SSD's preformance is under our standard. bs=32k is just one our benchmark test factor, we'll increase iops standard if we using bs=4k. You can also try https://github.com/pingcap/tidb-docker-compose for testing functionality.

**Comment by ivanjoy42** [comment]
I got the same problem. Just ignore it.

my test result:
randread
bs=64m iops=7
bs=8m iops=59
bs=1m iops=476
bs=64k iops=6892
bs=8k iops=37975

randwrite
64m iops=6
bs=8m  iops=50
bs=1m  iops=404
bs=64k iops=6001
bs=8k iops=33413

hp server unknown ssd 800G

**Comment by loveleon** [comment]
using ssd is just recommond suggestion ? It's not a necessary compulsive requirement.So we can use (eg,SAS)for using.

**Comment by aeoluswing** [comment]
The machine benchmark results show the different performance about disks via fio,i'm not sure SAS can be competent for kv component because of the requirement of a very high iops.

Further more,different bs argument in fio test has a great influence on the result:
bs=32k randread iops=8000
bs=8k randread iops=36792
bs=4k randread iops=45337
(RAID0-SSD:intel SSD D3-S4510 SERIES 960GB)
So,if you have already used SSD but fio test failed,you can modify this argument in `fio_randread.yml`,`fio_randread_write.yml` and `fio_randread_write_latency.yml`.
