### ISSUE TITLE
use the smaller table to build hash table for hash join

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#6868]
## 1. What did you do?

For **left outer join** or **right outer join**, we chose the inner table to build the hash table for hash join currently. In fact, we can chose a smaller one to build the hash table even if it is the outer table.

Take this as an example:

```sql
drop table if exists t1, t2;
create table t1(a bigint, b bigint); -- the smaller one
create table t2(a bigint, b bigint); -- the bigger  one
select * from t1 left outer join t2 on t1.a = t2.a;
```

For now we chose `t2` to build the hash table even if it may contain more records than `t1`, which can somehow possibly cause the following problems:
1. more probably to run out of memory
2. worse hash conflict, and the worse the conflict is, the more probe time may take.

If we chose the smaller table `t1` to build hash table, we can avoid these problem.

## 2. What did you expect to see?

use the smaller table to build hash table and do hash join

## 3. What did you see instead?

```sql
TiDB(localhost:4000) > desc select * from t1 left outer join t2 on t1.a = t2.a;
+----------------+----------------+------------------------------+------+-------------------------------------------------------------------------+----------+
| id             | parents        | children                     | task | operator info                                                           | count    |
+----------------+----------------+------------------------------+------+-------------------------------------------------------------------------+----------+
| TableScan_7    |                |                              | cop  | table:t1, range:[-inf,+inf], keep order:false                           | 10000.00 |
| TableReader_8  | HashLeftJoin_6 |                              | root | data:TableScan_7                                                        | 10000.00 |
| TableScan_9    |                |                              | cop  | table:t2, range:[-inf,+inf], keep order:false                           | 10000.00 |
| TableReader_10 | HashLeftJoin_6 |                              | root | data:TableScan_9                                                        | 10000.00 |
| HashLeftJoin_6 |                | TableReader_8,TableReader_10 | root | left outer join, inner:TableReader_10, equal:[eq(test.t1.a, test.t2.a)] | 12500.00 |
+----------------+----------------+------------------------------+------+-------------------------------------------------------------------------+----------+
5 rows in set (0.00 sec)
```

## 4. What version of TiDB are you using?

```sh
➜ ./bin/tidb-server -V
Release Version: v2.1.0-alpha-55-g5022b5b2
Git Commit Hash: 5022b5b2cc31ef64b4115482aaf44a50a6618024
Git Branch: master
UTC Build Time: 2018-06-20 10:20:04
GoVersion: go version go1.10 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-c4133d3ef0f099f8716a916c198390b26293ec00
```

-----

## Seperate the problem into two parts:
- [ ] implement the execution part #12882
- [ ] generate the plan #12883

**Comment by vikingM** [comment]
It means we should compare the two tables' size when exhausting hash join plans,then using the small table to be inner??

**Comment by zz-jason** [comment]
> It means we should compare the two tables' size when exhausting hash join plans,then using the small table to be inner??

@vikingM Yes. When executing, if the hash table is the outer one, we can use another map to record whether an outer row is matched with any inner rows, output these un-matched outer rows when all the inner rows are fetched out.

**Comment by wuudjac** [comment]
Hi, I've implemented a rough version of this enhancement some time ago here:

[tidb](https://github.com/wuudjac/tidb/commit/eab41e26e1b2b831b5d165f1a4fcd3a4bba9f182)
[parser](https://github.com/wuudjac/parser/commit/31e68775c447083b7a92114fbe9148e4f32538a1)

However, while resolving recent upstream conflicts, I found the newly introduced `tryToMatchOuters()` interface in #11922  is not suitable for this `HashJoinExec`.

The reason why it suits `IndexNestedLoopHashJoin` is because:

1. The inner chunk fetched by worker contains all potential matched join keys for outer chunk, so the data on both sides to be joined can be limited in a single join worker.
2. Because of 1., `outerRowStatus` and the hash table are isolated into different join workers, making it safe to append `outerRowStatus` in `tryToMatchOuters()` implementation of all joiner types.

But in `HashJoinExec`, the potential matched join keys distribute in different chunks (workers), and the hash table is thus global. For joiners which concurrently probe hash table, appending `outerRowStatus` is not thread safe to get a correct result in the end.

In my implementation of this issue, I used a global safe-on-set bitmap to record the outer rows matched, but found it hard to integrate with `tryToMatchOuters()` interface.

https://github.com/wuudjac/tidb/blob/eab41e26e1b2b831b5d165f1a4fcd3a4bba9f182/executor/join.go#L446-L454

In summation, I think the `tryToMatchOuters` interface needs to be considored or refined to suit more generally join procedures like `HashJoinExec`. Since this issue is now assigned to @fzhedu, please treat my previous work as  some reference and kind remind in your development, thanks.

**Comment by fzhedu** [comment]
> a global safe-on-set bitmap to record the outer rows matched

Thanks for your contributions. If taking a globally safe map like in your way, the map only needs to record whether a row get matched, instead of finally passing other conditions and outputing results. So  putting the mapping codes after [here](https://github.com/wuudjac/tidb/blob/eab41e26e1b2b831b5d165f1a4fcd3a4bba9f182/executor/join.go#L427) is ok. Such way does not consider the NULL problem. If this is considered, merging the local results from `tryToMatchOuters` with global map is ok.

**Comment by wuudjac** [comment]
@fzhedu I think your idea of merging local `outerRowStatus` from different join workers into global bitmap is practicable, it suits joiners like `LeftOuterJoiner`.

However, for semi joiners, it should append matched rows into join result no more than once. In current `tryToMatchOuters()` implementation e.g. `semiJoiner`, it will instantly append join result when it finds matched row:
https://github.com/pingcap/tidb/blob/29a19617259e3b236703aeed5f71f254cceccff0/executor/joiner.go#L264-L288

So if there are duplicate join keys across different inner chunks (workers), for example:

| outer chunk |
|---|
| 1 |

| inner chunk 1 |
|---|
| 1 |

| inner chunk 2 |
|---|
| 1 |

The final semi join result will be like this:

| join result |
|---|
| 1 |
| 1 |

This "global only once" constraint of semi joiners can be accomplished based on [return value of the global bitmap](https://github.com/wuudjac/tidb/blob/eab41e26e1b2b831b5d165f1a4fcd3a4bba9f182/util/bitmap/concurrent.go#L44-L47), so I think joiner's `tryToMatchOuters()` still needs to be refined to collabrate with executor's constraint implementation.

**Comment by fzhedu** [comment]
@wuudjac Thank you for pointing out the duplicated cases in the semi join. But for this issue, we just consider the left/right outer join, and defer the implementation for the semi join, because we are designing a perfect way to solve the NULL cases for the semi join and anti join.

**Comment by SunRunAway** [comment]
Fixed by @fzhedu 
planner: #12883 
executor: #12882
