### ISSUE TITLE
tidb does not support session timeout

### ISSUE THREAD

**Issue by aylen** [pingcap/tidb#7047]
Use jdbc to connect to tidb. After executing the timeout, perform RPC on the mysql server through jdbc protocol, and call mysql “KILL QUERY” command to end the operation of the current connection.because tidb does not support this command,When migrating from mysql to tidb, you need to modify a lot of existing code, can support the official mysql protocol roll operation

**Comment by lamxTyler** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
See here https://github.com/pingcap/docs/blob/master/FAQ.md  or [(中文 here)](https://github.com/pingcap/docs-cn/blob/master/FAQ.md)

> Can kill be executed in TiDB?
> You can kill DML statements. First use show processlist to find the ID corresponding with the session, and then run kill tidb [session id].

> Does TiDB support session timeout?
> Currently, TiDB does not support session timeout in the database level. If you want to implement session timeout, use the session ID started by side records in the absence of LB (Load Balancing), and customize the session timeout on the application. After timeout, kill SQL using kill tidb [session id] on the node that starts the query. It is currently recommended to implement session timeout using applications. When the timeout time is reached, the application layer reports an exception and continues to execute subsequent program segments.


@aylen

**Comment by morgo** [comment]
TiDB recently added support for `wait_timeout`, so connections will idle out and close.  I've created an issue for the docs to update the FAQ: https://github.com/pingcap/docs/issues/888

In regards to a MySQL compatible `KILL`, because TiDB connection IDs are local to a server, there is actually some risk that if deployed behind a load balancer (recommended) you could kill a connection of the same server ID on a different server!  This is the rationale behind changing the syntax to `KILL TIDB x`.  There is a server option called `compatible-kill-query` which you can enable if you are not using a load balancer / can guarantee you are routing to the correct server.  I have an issue open in docs to update this too: https://github.com/pingcap/docs/issues/831

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
