### ISSUE TITLE
Can not upgrade tidb cluster from v1.0.3 to master using ansible

### ISSUE THREAD

**Issue by imtbkcat** [pingcap/tidb#7320]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

ansible-playbook rolling_update.yml
from v1.0.3 to v2.1.0 beta

2. What did you expect to see?

rolling update finished successfully

3. What did you see instead?

TASK [start TiDB by supervise] *************************************************

TASK [start TiDB by systemd] ***************************************************
changed: [TiDB1-1]

TASK [wait for TiDB up] ********************************************************
fatal: [TiDB1-1]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string TiDB in 127.0.0.1:10080"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/tidb/another/tidb-ansible/retry_files/rolling_update.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=40   changed=5    unreachable=0    failed=0
TiDB1-1                    : ok=30   changed=5    unreachable=0    failed=1
TiDB1-2                    : ok=9    changed=0    unreachable=0    failed=0
TiKV1-1                    : ok=50   changed=5    unreachable=0    failed=0
TiKV1-2                    : ok=50   changed=5    unreachable=0    failed=0

ERROR MESSAGE SUMMARY **********************************************************
[TiDB1-1]: Ansible FAILED! => playbook: rolling_update.yml; TASK: wait for TiDB up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string TiDB in 127.0.0.1:10080"}
Ask for help:
Contact us: support@pingcap.com
It seems that you encounter some problems. You can send an email to the above email address, attached with the tidb-ansible/inventory.ini and tidb-ansible/log/ansible.log files and the error message, or new issue on https://github.com/pingcap/tidb-ansible/issues. We'll try our best to help you deploy a TiDB cluster. Thanks. :-)

2018/08/08 17:11:19 Rolling update Failed, reading /data1/deploy1/log/ for detail
exit status 1

tidb.log:

2018/08/08 17:06:28.915 domain.go:103: [info] [ddl] diff load InfoSchema from version 28 to 29 in 5.032533ms, tableIDs [63]
2018/08/08 17:06:28.916 domain.go:320: [warning] [ddl] loading schema takes a long time 89.283181ms
2018/08/08 17:06:29.772 ddl.go:503: [info] [ddl] DDL job ID:64 is finished
2018/08/08 17:06:29.772 domain.go:413: [info] [ddl] on DDL change, must reload
2018/08/08 17:06:29.773 adapter.go:363: [warning] [SLOW_QUERY] cost_time:2.094684463s succ:true con:0 user:<nil> txn_start_ts:402055282751176705 database: sql:CREATE TABLE IF NOT EXISTS mysql.gc_delete_range_done (   job_id BIGINT NOT NULL COMMENT "the DDL job ID",   element_id BIGINT NOT NULL COMMENT "the schema element ID",   start_key VARCHAR(255) NOT NULL COMMENT "encoded in hex",   end_key VARCHAR(255) NOT NULL COMMENT "encoded in hex",   ts BIGINT NOT NULL COMMENT "timestamp in int64",   UNIQUE KEY delete_range_done_index (job_id, element_id)  );
2018/08/08 17:06:29.773 session.go:1404: [info] [CRUCIAL OPERATION] con:0 schema_ver:29 ALTER TABLE mysql.gc_delete_range DROP INDEX job_id (by <nil>).
2018/08/08 17:06:29.773 session.go:957: [info] con:0 schema_ver:29 NewTxn() inside a transaction auto commit: 402055283275464774
2018/08/08 17:06:29.784 ddl.go:471: [info] [ddl] start DDL job ID:65, Type:drop index, State:none, SchemaState:none, SchemaID:3, TableID:47, RowCount:0, ArgLen:1, start time: 2018-08-08 17:06:29.741 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0, Query:ALTER TABLE mysql.gc_delete_range DROP INDEX job_id
2018/08/08 17:06:30.589 domain.go:103: [info] [ddl] diff load InfoSchema from version 29 to 30 in 3.381911ms, tableIDs [47]
2018/08/08 17:06:30.658 domain.go:103: [info] [ddl] diff load InfoSchema from version 30 to 31 in 2.835496ms, tableIDs [47]
2018/08/08 17:06:30.805 domain.go:103: [info] [ddl] diff load InfoSchema from version 31 to 32 in 2.000424ms, tableIDs [47]
2018/08/08 17:06:30.806 domain.go:320: [warning] [ddl] loading schema takes a long time 79.313411ms
2018/08/08 17:06:30.906 domain.go:103: [info] [ddl] diff load InfoSchema from version 32 to 33 in 6.15162ms, tableIDs [47]
2018/08/08 17:06:31.786 ddl.go:503: [info] [ddl] DDL job ID:65 is finished
2018/08/08 17:06:31.786 domain.go:413: [info] [ddl] on DDL change, must reload
2018/08/08 17:06:31.788 adapter.go:363: [warning] [SLOW_QUERY] cost_time:2.014401641s succ:true con:0 user:<nil> txn_start_ts:402055283275464775 database: sql:ALTER TABLE mysql.gc_delete_range DROP INDEX job_id
2018/08/08 17:06:31.788 session.go:1404: [info] [CRUCIAL OPERATION] con:0 schema_ver:33 ALTER TABLE mysql.gc_delete_range ADD UNIQUE INDEX delete_range_index (job_id, element_id) (by <nil>).
2018/08/08 17:06:31.788 session.go:957: [info] con:0 schema_ver:33 NewTxn() inside a transaction auto commit: 402055283799752783
2018/08/08 17:06:31.807 ddl.go:471: [info] [ddl] start DDL job ID:66, Type:add index, State:none, SchemaState:none, SchemaID:3, TableID:47, RowCount:0, ArgLen:4, start time: 2018-08-08 17:06:31.741 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0, Query:ALTER TABLE mysql.gc_delete_range ADD UNIQUE INDEX delete_range_index (job_id, element_id)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v1.0.3

**Comment by imtbkcat** [comment]
Upgrade from v1.0.3 to v2.0.3, then from v2.0.3 to master is avaible.

**Comment by zimulala** [comment]
@imtbkcat 
Two servers are upgraded separately. At first, the TiDB1-1 upgrades from version 1.0.3 to master. Then the TiDB1-2 becomes the DDL owner. TiDB1-1 need to do bootstrap and the bootstrap has an operation of "add index". The operation of "add index" be put into the add-index queue. But at that time, the TiDB1-2 can't handle jobs in the add-index queue. So In the bootstrap, this index-adding operation can't be handled by the DDL owner. At last, the TiDB1-1 can't process the bootstrap normally.
At this time, we can kill the process of TiDB1-2. Then TiDB1-1 will become the DDL owner. The latest version of TiDB can handle the jobs in the add-index queue.

**Comment by evancao77** [comment]
I don't quite understand, so I need to operate to solve this problem

**Comment by evancao77** [comment]
@zimulala @zimulala

**Comment by zimulala** [comment]
@evancao77 
What problem did you encounter?

**Comment by zimulala** [comment]
@evancao77 
Your problem is different from the current issue. This issue exists when upgrading from version 1.0.3 to version 2.1 and later. Your problem is 

>Release Version: v1.0.8-1-gaacba4a upgrade to 2.0.8


Your problem is because of the error of `[ddl:-1]tikv aborts txn: Txn(Engine(Other(StringError("[src/storage/mod.rs:499]: oneshot canceled"))))`. Do you know how this error happened in TiKV?@breeswish

**Comment by evancao77** [comment]
@zimulala 
the tikv log ，is this proplem
2018/11/06 19:58:18.806 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:18.997 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:18.998 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:18.999 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.004 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.004 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.004 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.021 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.022 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.026 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.026 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.271 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.273 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.274 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.275 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.276 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.362 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.362 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/11/06 19:58:19.362 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))

**Comment by evancao77** [comment]
tikv2:
2018/11/06 20:14:48.983 size.rs:81: [INFO] [region 775853] approximate size 155852772 >= 150994944, need to do split check
2018/11/06 20:14:49.574 size.rs:81: [INFO] [region 611637] approximate size 152812615 >= 150994944, need to do split check
2018/11/06 20:14:50.155 size.rs:81: [INFO] [region 572833] approximate size 209376252 >= 150994944, need to do split check
2018/11/06 20:14:50.781 size.rs:81: [INFO] [region 590585] approximate size 162866954 >= 150994944, need to do split check
2018/11/06 20:14:51.720 size.rs:81: [INFO] [region 616357] approximate size 151497597 >= 150994944, need to do split check
2018/11/06 20:14:52.261 size.rs:81: [INFO] [region 759565] approximate size 154434356 >= 150994944, need to do split check
2018/11/06 20:14:52.788 size.rs:81: [INFO] [region 593489] approximate size 156949209 >= 150994944, need to do split check
2018/11/06 20:14:53.298 size.rs:81: [INFO] [region 798309] approximate size 159565042 >= 150994944, need to do split check
2018/11/06 20:14:54.033 size.rs:81: [INFO] [region 740313] approximate size 166116062 >= 150994944, need to do split check
2018/11/06 20:14:54.651 size.rs:81: [INFO] [region 415705] approximate size 153457493 >= 150994944, need to do split check
2018/11/06 20:14:55.336 size.rs:81: [INFO] [region 345845] approximate size 186614252 >= 150994944, need to do split check
2018/11/06 20:14:56.284 size.rs:81: [INFO] [region 696889] approximate size 164326732 >= 150994944, need to do split check
2018/11/06 20:14:56.941 size.rs:81: [INFO] [region 751309] approximate size 169040390 >= 150994944, need to do split check
2018/11/06 20:14:57.869 size.rs:81: [INFO] [region 579745] approximate size 204073026 >= 150994944, need to do split check
2018/11/06 20:14:58.520 size.rs:81: [INFO] [region 615689] approximate size 152211753 >= 150994944, need to do split check
2018/11/06 20:14:59.048 size.rs:81: [INFO] [region 273705] approximate size 160400886 >= 150994944, need to do split check

**Comment by breeswish** [comment]
"oneshot canceled" usually means that the TiKV instance is going to be closed so that requests are not processed. But I don't have ideas why it occurs here.

**Comment by evancao77** [comment]
How do I solve this problem and restart tidb?  I can't start the tidb node.

**Comment by zimulala** [comment]
PTAL @breeswish
