### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by iakisey** [pingcap/tidb#7578]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
programer

2. What did you expect to see?
![371535815214_ pic](https://user-images.githubusercontent.com/20331418/44947327-2cf10b00-ae3e-11e8-98e5-bad41e7eaf4d.jpg)

3. What did you see instead?
![381535815342_ pic](https://user-images.githubusercontent.com/20331418/44947332-367a7300-ae3e-11e8-8919-0e3013285d9d.jpg)
![391535815362_ pic_hd](https://user-images.githubusercontent.com/20331418/44947334-3c705400-ae3e-11e8-9374-bba61f3a4555.jpg)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 Release Version: v2.1.0-rc.1-7-g38c939f

**Comment by zhexuany** [comment]
Thanks for your reporting. We will investigate this. @zz-jason PTAL when you have time.

**Comment by mccxj** [comment]
mini testcase:
```
create table t(c enum('a'));
insert into t values('a');
select c,count(1) from t group by c;
```

**Comment by tiancaiamao** [comment]
It's around here:
https://github.com/pingcap/tidb/pull/7268/files#diff-2ed8f699513f49aaaf408561a56aa2e7L477

The old code evaluate using type.Datum, and enum type info would be handle properly.
After the change, we'll use chunk.Chunk instead of types.Datum, the eval type is always using string.

When the chunk execution finish, the column data stored in the chunk is string (it **should be** converted to enum somewhere), but the schema expect the column data to be a enum, so the panic happen.

PTAL @zz-jason

**Comment by zz-jason** [comment]
In the type infer phase, the result type for function `first_row(enum)` is inferred to string, and the column type in the schema should also be changed to string. 

In a word, the type of the column in the schema should be reset after creating an aggregate function descriptor through the function `aggregation.NewAggFuncDesc()`

**Comment by mccxj** [comment]
@zz-jason duplicate with https://github.com/pingcap/tidb/issues/7307

**Comment by zz-jason** [comment]
@mccxj Got it! Thanks!
