### ISSUE TITLE
`Cast(unsigned arg as decimal)` doesn't work properly

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#7778]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select cast(18446744073709551615 as decimal(65, 0));
```

or
```
create table tt(a bigint unsigned);
insert into tt values(18446744073709551615);
select cast(a as decimal(65, 0)) from tt;
```

2. What did you expect to see?

return 18446744073709551615.

3. What did you see instead?

-1 returned.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master which commit is 56713821ffc6819fa6bda7f8fbbeb7555cd65e19

**Comment by zz-jason** [comment]
```sql
drop table t;
create table t(a bigint unsigned);
insert into t values(18446744073709551615);
```
```sql
TiDB(localhost:4000) > select cast(a as decimal) from t;
+--------------------+
| cast(a as decimal) |
+--------------------+
|                 -1 |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by AndrewDi** [comment]
It seems like [https://github.com/pingcap/tidb/blob/eb0c6636cd0c8688cd351793838e476ac951d2f2/expression/constant.go#L141](https://github.com/pingcap/tidb/blob/eb0c6636cd0c8688cd351793838e476ac951d2f2/expression/constant.go#L141) force convert usigned int to signed int, and hit integer overflow, we may need to add new function to handle unsigned int.

**Comment by AndrewDi** [comment]
> @AndrewDi
> Since `unsigned` is treated as a flag in MySQL, TiDB does this too currently.
> The direct reason of this bug is that we forget to set the `UnsignedFlag` of `CAST`'s `fieldtype` to true somewhere.

You are right, but I think there are two problems here:[https://github.com/pingcap/tidb/blob/eb0c6636cd0c8688cd351793838e476ac951d2f2/expression/builtin_cast.go#L483-L501](https://github.com/pingcap/tidb/blob/eb0c6636cd0c8688cd351793838e476ac951d2f2/expression/builtin_cast.go#L483-L501)
1. evalDecimal has handle cast unsigned int here, but due to UnsignedFlag has never been set, so it will never go into [https://github.com/pingcap/tidb/blob/eb0c6636cd0c8688cd351793838e476ac951d2f2/expression/builtin_cast.go#L493-L495](https://github.com/pingcap/tidb/blob/eb0c6636cd0c8688cd351793838e476ac951d2f2/expression/builtin_cast.go#L493-L495).

2. `val, isNull, err := b.args[0].EvalInt(b.ctx, row)` has lost unsigned value before.

**Comment by winoros** [comment]
@AndrewDi 
Though it's a `int64`. We can use `uint64(val)` to easily get the correct unsigned value.

So if the unsigned flag is not lost, the behavior will always be right.

Add yes, a new function to handle unsigned should be a good idea. But it will be a lot of code change. So it may not be the best solution to this bug.
