### ISSUE TITLE
SHOW CREATE TABLE should show added foreign keys

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#8349]
## Bug Report

See #8303: I do not know how to create a proper Entity-Relationship diagram with TiDB due to this issue.
Additionally, it may not be possible to retrieve the name of an added foreign key (needed for dropping it).

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Created a table, then as a separate step added foreign keys, then ran `SHOW CREATE <table>`.

2. What did you expect to see?

Foreign keys among the output.

3. What did you see instead?

No foreign keys.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

pingcap/tidb:v2.1.0-rc.4

**Comment by shenli** [comment]
@gregwebs When TiDB show table list, it will not consider the foreign key dependency between tables. So if we print foreign key in ShowCreateTable result, you may meet error when restoring the data into MySQL. So we ignore the foreign key info.

**Comment by gregwebs** [comment]
I see how the current behavior is convenient. Changing the order of tables on restore to match foreign key dependencies is a possibility. However, in the general case foreign keys may be circular. So can we add: `SET FOREIGN_KEY_CHECKS=0;` to the restore SQL?

**Comment by morgo** [comment]
I chatted with @gregwebs.  I think the following makes sense with foreign keys:
1. Change the default of `foreign_key_checks` to `OFF` (side note: in MySQL it is a boolean option; in TiDB it is a numeric value).
2. Add validation, so that setting `foreign_key_checks` to `ON` (or 1 etc.) results in a warning ('unsupported in TiDB).
3. Document it on mysql-compatibility, differences in defaults.

**Comment by morgo** [comment]
I've [created a PR](https://github.com/pingcap/tidb/pull/8358) to change the default `foreign_key_checks` to `OFF`.

I suggest updating this issue to be a 2-part feature request:
1. Disable foreign key DDL validation when `foreign_key_checks=OFF` (might be a bit controversial, since the other PR refuses to set this value to anything other than `OFF`; thus validation can never be enabled).
2. Show foreign keys in `SHOW CREATE TABLE` statements.

**Comment by gregwebs** [comment]
Nice PR, I agree with the general approach. If I understand the Disable foreign key DDL validation suggestion properly, then I definitely don't like it. At a minimum I would like what MySQL has (don't check CREATE, but check ALTER or re-creation). But we should also consider creating a separate variable for foreign key DDL validation.

**Comment by morgo** [comment]
Relates to https://github.com/pingcap/tidb/issues/1691

**Comment by nishantc7** [comment]
The EER Diagram still doesn't show foreign key relationships for MySQL Workbench
