### ISSUE TITLE
Foreign key enforcement should be separate for DML And DDL

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#8484]
## Feature Request

We merged https://github.com/pingcap/tidb/pull/8358 to master.
This sets `foreign_key_checks=OFF`.
This means we will lose DDL validation.
The root problem is that `foreign_key_checks` works for both DML and DDL.

I discussed with @morgo  that I had some new thoughts on this issue. We should consider using `foreign_key_checks=ON` to represent just DDL. In that case we would default it to ON (current master checks foreign key validity) and turn it OFF during a restore operation.

Actually enforcing foreign keys (DML) would still not be done. We would plan to create a TIDB specific workflow for foreign key enforcement. This would probably start with a separate configuration variable (useful to turn foreign keys on in a dev environment, etc to check for data integrity). The ideal end goal  would be to turn individual keys on and off, perhaps even for specific operations (INSERT/UPDATE). Some table have terabytes of data, but not all of them!

This is a break in compatibility with MySQL. However, we can never be compatible until we actually enforce foreign keys in DML, and it seems unrealistic (for large production workloads) that we can do this with this single variable.

There is a complication here: restore operations. These generally set `foreign_key_checks=OFF` for the duration of the restore. Unfortunately we will need to respect that setting for both DML and DDL. So we have two settings:

* OFF: DDL + DML off
* ON: DDL on, DML not specified (currently off)

The first action if this long-term vision is agreed upon is to reverse the variable setting here and to update the docs: https://github.com/pingcap/tidb/pull/8358
It is possible that we could now produce a warning when the variable is set to OFF staging that DML is not enforced as in MySQL (it is safe to be ON if you are not doing a restore).

The next action would be to produce a proper design for selective DML enforcement.

**Comment by gregwebs** [comment]
AFAICT we do not actually disable foreign key DDL checks for foreign_key_checks=OFF on master righ tnow. I think this would break restore workflows?

**Comment by nullnotnil** [comment]
I investigated the behavior of foreign key checks for https://github.com/pingcap/tidb/pull/18360

The PR #8358 did not specifically modify how TiDB handled checks for DDL, it changed the default to advertise what TiDB does more accurately. It also added a feature to "refuse" to allow setting it to ON, since TiDB does not have such capability. There is now a feature request to relax this refusal in https://github.com/pingcap/tidb/issues/18641 (with the caveat being that TiDB is lying to applications)

I suggest that this issue be merged or revisited after DML enforcement for foreign keys has been added, since it is not meaningful until then. The feature request to track this is https://github.com/pingcap/tidb/issues/18209
