### ISSUE TITLE
support 'show processlist  where' sql 

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb#9171]
## Feature Request

**Is your feature request related to a problem? Please describe:**

sql like 'show processlist  where mem > 256' can help DBAs troubleshoot problems more quickly and conveniently. sometimes the  result of 'show processlist' is tedious. it's hard to find the useful item.

**Describe the feature you'd like:**

support 'show processlist  where' sql 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by morgo** [comment]
Hi @zhuboshuai 

The mem column was dropped from `SHOW PROCESSLIST` in master, because it is not fully MySQL compatible (and only includes memory from some operators).  Adding this syntax extension could also create compatibility problems with MySQL if they add syntax down the line, and TiDB differs.

In MySQL there was previously an `information_schema.processlist` table which could be filtered, but this has moved to `performance_schema` / `select * from sys.session`.  With TiDB now supporting views, we could add something similar to `sys.session` which can be filtered with SQL.  What do you think?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to reopen if you have additional questions. Thanks!
