### ISSUE TITLE
Support join reorder for LEFT JOIN

### ISSUE THREAD

**Issue by xzh12** [pingcap/tidb#9268]
## Question
```sql
explain analyze SELECT 
		*
		FROM dzqd_order_main c
		left join
		dzqd_order_entry entry on c.f_number = entry.f_number
		left join
		dzqd_order_cus cus on c.f_number = cus.f_number
		
		where 1=1
		and entry.f_CRM_Uer_No ='17717595275'
		GROUP BY c.f_number
		order by c.f_createtime desc
		limit 10
```
		
![image](https://user-images.githubusercontent.com/5847962/52550435-14384880-2e13-11e9-9a85-1bb05b27a933.png)

```sql		
explain analyze SELECT 
		*
		FROM dzqd_order_main c
		left join
		dzqd_order_cus cus on c.f_number = cus.f_number
		left join
		dzqd_order_entry entry on c.f_number = entry.f_number
		
		where 1=1
		and entry.f_CRM_Uer_No ='17717595275'
		GROUP BY c.f_number
		order by c.f_createtime desc
		limit 10
```
				
![image](https://user-images.githubusercontent.com/5847962/52550417-07b3f000-2e13-11e9-9499-92bb3360fbb0.png)

two sql, one <1s,anothr >7s ,just the order of left join is different。
who can told me why???
thk.

**Comment by zz-jason** [comment]
@xzh12 Because the two queries have different join order.

For both queries, because the predicate `entry.f_CRM_Uer_No ='17717595275'` is null-rejective, `xxx left join entry` is converted to `xxx inner join entry`

For query 1, the join order is:
1. `c` inner join `entry`(**Index Join**), the join results in 6 rows according to the output of `explain analyze`
2. then left outer join `cus`(**Index Join**), the join results in 1 row according to the output of `explain analyze`

For query 2, the join order is:
1. `c` left outer join `cus`(**Merge Join**), the join results in 490,335 rows, takes 11s according to the output of `explain analyze`.
2. then inner join `entry`(**Hash Join**), `entry` is chosen to be the inner table to build hash table.

**Comment by eurekaka** [comment]
@xzh12 thanks for the feedback.

The join order matters regarding query performance. For the first SQL, table `entry` has only 6 rows returned from KV layer after applying `entry.f_CRM_Uer_No ='17717595275'` filter, and the outer join involving table `entry` can be simplified to inner join because of the above filter, so `entry` inner join `c` is cheap and fast;
For the second SQL, `entry` is joined at last, and join result of `c` and `cus` is pretty large compared with 6.

**Comment by zz-jason** [comment]
We should consider outer joins in the join reorder algorithm. /cc @eurekaka, @winoros

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
