### ISSUE TITLE
How to use TiDB as backup of MySQL

### ISSUE THREAD

**Issue by leshalv** [pingcap/tidb#9691]
使用TiDB做MySQL备份方案，如果MySQL出现问题，如何使用TiDB进行对MySQL的数据恢复呢？
我目前没有看到类似文章，如果有请推荐下，谢谢

**Comment by lamxTyler** [comment]
Thanks for your feedback! PTAL @amyangfei

**Comment by amyangfei** [comment]
You can find plenty of use cases from [PingCAP use case](https://pingcap.com/cases-cn/)

Many users deploy a TiDB cluster as backup of MySQL with the help TiDB ecosystem tools, including mydumper, loader, syncer, TiDB-DM, etc.  You can find usage of these tools from official doc: https://pingcap.com/docs/

As for restore data from TiDB to MySQL, this is not commonly used, because MySQL has master-slave architecture which is suitable for high availability requirement. However you can use mydumper to dump data files from TiDB and then use some tools, such as mysqldump, loader to restore data back to MySQL.

**Comment by leshalv** [comment]
OK 好了，目前的遇到了新问题我不知道是不是bug，我批量完成了，我从tidb对一条记录进行了更改，然后我又在原始数据库对此条记录进行了修改，tidb并没有体现出我的修改，我想是不是一个bug或者本身设计上就是这样考虑的呢？

**Comment by amyangfei** [comment]
Firstly what synchronization architecture in your environment? is it `MySQL -> syncer -> TiDB or MySQL -> DM -> TiDB`
Secondly what do you mean by `tidb并没有体现出我的修改`? If you want each update in MySQL can be synchronized to TiDB, why did you update a record in TiDB ?
