### ISSUE TITLE
support online config item reloading

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#9891]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, in order to update a config item, our DBA has to modify the config file, stop the cluster, and restart the cluster. This workflow has the following cons:
1. DBAs have to file an application to restart the cluster
2. The restart progress can take a long time if the cluster contains a lot of servers
3. There might be a lot of alerts about "server is down"

**Describe the feature you'd like:**

It's better to support online config reloading, without restarting any cluster server. DBAs don't need to file an application to restart clusters, life is easier.

**sub tasks:**

- [ ] support online config reloading for section "performance" (#9892)

**Comment by morgo** [comment]
The MySQL server does this in a different way, which I actually prefer: `SET PERSIST name=value`.

Using a config file assumes that users have a login to the server, or a config management system.  Because there are multiple choices, it makes it hard to describe how to change a setting in the documentation too (describing `set persist` is easy).

Where this is a little bit nuanced though, is that in TiDB global MySQL variables always apply to the whole cluster.  Versus the configuration file which only applies to an individual tidb instance.  I would like to see us extend variables to cover `INSTANCE` scope: https://github.com/pingcap/tidb/issues/9298

**Comment by qw4990** [comment]
After discussing, we decided to not support online config reading on TiDB, and the main reason is that using SQL variables can already control TiDB's behavior online, which conflicts with online config reading.
If we support these two features both, our users will be confused about which feature they should use.
Here is a [Chinese document](https://docs.google.com/document/d/1BN5FGhX4jP6k9goLYVrAvfwo0wSImPTWwNXGr-e014k/edit?usp=sharing) about our discussion.
